<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Categorical Data Analysis | Statistical Foundations</title>
  <meta name="description" content="Chapter 7 Categorical Data Analysis | Statistical Foundations" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Categorical Data Analysis | Statistical Foundations" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="IAA-Faculty/statistical_foundations" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Categorical Data Analysis | Statistical Foundations" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="model-building-and-scoring-for-prediction.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a style="font-weight:bold, text-align:center" href="https://github.com/IAA-Faculty/statistical_foundations/">Statistical Foundations</a>
<img src="./img/iaaicon.png" alt="IAA"  class="center"</li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#authors"><i class="fa fa-check"></i>Authors</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#structure-of-the-book"><i class="fa fa-check"></i>Structure of the book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro-stat.html"><a href="intro-stat.html"><i class="fa fa-check"></i><b>1</b> Introduction to Statistics</a>
<ul>
<li class="chapter" data-level="1.0.1" data-path="intro-stat.html"><a href="intro-stat.html#python-code"><i class="fa fa-check"></i><b>1.0.1</b> Python Code:</a></li>
<li class="chapter" data-level="1.1" data-path="intro-stat.html"><a href="intro-stat.html#eda"><i class="fa fa-check"></i><b>1.1</b> Exploratory Data Analysis (EDA)</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="intro-stat.html"><a href="intro-stat.html#vartypes"><i class="fa fa-check"></i><b>1.1.1</b> Types of Variables</a></li>
<li class="chapter" data-level="1.1.2" data-path="intro-stat.html"><a href="intro-stat.html#nominal-variables"><i class="fa fa-check"></i><b>1.1.2</b> Nominal Variables</a></li>
<li class="chapter" data-level="1.1.3" data-path="intro-stat.html"><a href="intro-stat.html#python-code-1"><i class="fa fa-check"></i><b>1.1.3</b> Python Code</a></li>
<li class="chapter" data-level="1.1.4" data-path="intro-stat.html"><a href="intro-stat.html#interval-variables"><i class="fa fa-check"></i><b>1.1.4</b> Interval Variables</a></li>
<li class="chapter" data-level="1.1.5" data-path="intro-stat.html"><a href="intro-stat.html#ordinal-variables"><i class="fa fa-check"></i><b>1.1.5</b> Ordinal Variables</a></li>
<li class="chapter" data-level="1.1.6" data-path="intro-stat.html"><a href="intro-stat.html#distributions"><i class="fa fa-check"></i><b>1.1.6</b> Distributions</a></li>
<li class="chapter" data-level="1.1.7" data-path="intro-stat.html"><a href="intro-stat.html#python-code-2"><i class="fa fa-check"></i><b>1.1.7</b> Python code:</a></li>
<li class="chapter" data-level="1.1.8" data-path="intro-stat.html"><a href="intro-stat.html#location"><i class="fa fa-check"></i><b>1.1.8</b> Location</a></li>
<li class="chapter" data-level="1.1.9" data-path="intro-stat.html"><a href="intro-stat.html#spread"><i class="fa fa-check"></i><b>1.1.9</b> Spread</a></li>
<li class="chapter" data-level="1.1.10" data-path="intro-stat.html"><a href="intro-stat.html#shape"><i class="fa fa-check"></i><b>1.1.10</b> Shape</a></li>
<li class="chapter" data-level="1.1.11" data-path="intro-stat.html"><a href="intro-stat.html#python-code-3"><i class="fa fa-check"></i><b>1.1.11</b> Python code:</a></li>
<li class="chapter" data-level="1.1.12" data-path="intro-stat.html"><a href="intro-stat.html#normal"><i class="fa fa-check"></i><b>1.1.12</b> The Normal Distribution</a></li>
<li class="chapter" data-level="1.1.13" data-path="intro-stat.html"><a href="intro-stat.html#skew"><i class="fa fa-check"></i><b>1.1.13</b> Skewness</a></li>
<li class="chapter" data-level="1.1.14" data-path="intro-stat.html"><a href="intro-stat.html#kurt"><i class="fa fa-check"></i><b>1.1.14</b> Kurtosis</a></li>
<li class="chapter" data-level="1.1.15" data-path="intro-stat.html"><a href="intro-stat.html#graphdist"><i class="fa fa-check"></i><b>1.1.15</b> Graphical Displays of Distributions</a></li>
<li class="chapter" data-level="1.1.16" data-path="intro-stat.html"><a href="intro-stat.html#histograms"><i class="fa fa-check"></i><b>1.1.16</b> Histograms</a></li>
<li class="chapter" data-level="1.1.17" data-path="intro-stat.html"><a href="intro-stat.html#python-code-4"><i class="fa fa-check"></i><b>1.1.17</b> Python Code:</a></li>
<li class="chapter" data-level="1.1.18" data-path="intro-stat.html"><a href="intro-stat.html#normal-probability-plots-qq-plots"><i class="fa fa-check"></i><b>1.1.18</b> Normal probability plots (QQ Plots)</a></li>
<li class="chapter" data-level="1.1.19" data-path="intro-stat.html"><a href="intro-stat.html#python-code-5"><i class="fa fa-check"></i><b>1.1.19</b> Python code:</a></li>
<li class="chapter" data-level="1.1.20" data-path="intro-stat.html"><a href="intro-stat.html#box-plots"><i class="fa fa-check"></i><b>1.1.20</b> Box Plots</a></li>
<li class="chapter" data-level="1.1.21" data-path="intro-stat.html"><a href="intro-stat.html#python-code-6"><i class="fa fa-check"></i><b>1.1.21</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="intro-stat.html"><a href="intro-stat.html#pointest"><i class="fa fa-check"></i><b>1.2</b> Point Estimates</a></li>
<li class="chapter" data-level="1.3" data-path="intro-stat.html"><a href="intro-stat.html#ci"><i class="fa fa-check"></i><b>1.3</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="intro-stat.html"><a href="intro-stat.html#python-code-7"><i class="fa fa-check"></i><b>1.3.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="intro-stat.html"><a href="intro-stat.html#hypotest"><i class="fa fa-check"></i><b>1.4</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="intro-stat.html"><a href="intro-stat.html#onesample"><i class="fa fa-check"></i><b>1.4.1</b> One-Sample T-Test</a></li>
<li class="chapter" data-level="1.4.2" data-path="intro-stat.html"><a href="intro-stat.html#python-code-8"><i class="fa fa-check"></i><b>1.4.2</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="intro-stat.html"><a href="intro-stat.html#two-sample-t-tests"><i class="fa fa-check"></i><b>1.5</b> Two-Sample t-tests</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="intro-stat.html"><a href="intro-stat.html#testnorm"><i class="fa fa-check"></i><b>1.5.1</b> Testing Normality of Groups</a></li>
<li class="chapter" data-level="1.5.2" data-path="intro-stat.html"><a href="intro-stat.html#ftest"><i class="fa fa-check"></i><b>1.5.2</b> Testing Equality of Variances</a></li>
<li class="chapter" data-level="1.5.3" data-path="intro-stat.html"><a href="intro-stat.html#tsttest"><i class="fa fa-check"></i><b>1.5.3</b> Testing Equality of Means</a></li>
<li class="chapter" data-level="1.5.4" data-path="intro-stat.html"><a href="intro-stat.html#python-code-9"><i class="fa fa-check"></i><b>1.5.4</b> Python Code</a></li>
<li class="chapter" data-level="1.5.5" data-path="intro-stat.html"><a href="intro-stat.html#wilcoxon"><i class="fa fa-check"></i><b>1.5.5</b> Mann-Whitney-Wilcoxon Test</a></li>
<li class="chapter" data-level="1.5.6" data-path="intro-stat.html"><a href="intro-stat.html#python-code-10"><i class="fa fa-check"></i><b>1.5.6</b> Python Code</a></li>
<li class="chapter" data-level="1.5.7" data-path="intro-stat.html"><a href="intro-stat.html#bootstrap"><i class="fa fa-check"></i><b>1.5.7</b> Bootstrap</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="slr.html"><a href="slr.html"><i class="fa fa-check"></i><b>2</b> Introduction to ANOVA and Linear Regression</a>
<ul>
<li class="chapter" data-level="2.1" data-path="slr.html"><a href="slr.html#evp"><i class="fa fa-check"></i><b>2.1</b> Predictive vs. Explanatory</a></li>
<li class="chapter" data-level="2.2" data-path="slr.html"><a href="slr.html#trainvalidtest"><i class="fa fa-check"></i><b>2.2</b> Honest Assessment</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="slr.html"><a href="slr.html#python-code-11"><i class="fa fa-check"></i><b>2.2.1</b> Python Code:</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="slr.html"><a href="slr.html#bivariate-eda"><i class="fa fa-check"></i><b>2.3</b> Bivariate EDA</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="slr.html"><a href="slr.html#continuous-continuous-associations"><i class="fa fa-check"></i><b>2.3.1</b> Continuous-Continuous Associations</a></li>
<li class="chapter" data-level="2.3.2" data-path="slr.html"><a href="slr.html#continuous-categorical-associations"><i class="fa fa-check"></i><b>2.3.2</b> Continuous-Categorical Associations</a></li>
<li class="chapter" data-level="2.3.3" data-path="slr.html"><a href="slr.html#python-code-12"><i class="fa fa-check"></i><b>2.3.3</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="slr.html"><a href="slr.html#oneway"><i class="fa fa-check"></i><b>2.4</b> One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="slr.html"><a href="slr.html#python-code-13"><i class="fa fa-check"></i><b>2.4.1</b> Python Code</a></li>
<li class="chapter" data-level="2.4.2" data-path="slr.html"><a href="slr.html#kruskal"><i class="fa fa-check"></i><b>2.4.2</b> Kruskal-Wallis</a></li>
<li class="chapter" data-level="2.4.3" data-path="slr.html"><a href="slr.html#python-code-14"><i class="fa fa-check"></i><b>2.4.3</b> Python Code:</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="slr.html"><a href="slr.html#posthoc"><i class="fa fa-check"></i><b>2.5</b> ANOVA Post-hoc Testing</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="slr.html"><a href="slr.html#tukey"><i class="fa fa-check"></i><b>2.5.1</b> Tukey-Kramer</a></li>
<li class="chapter" data-level="2.5.2" data-path="slr.html"><a href="slr.html#dunnett"><i class="fa fa-check"></i><b>2.5.2</b> Dunnett’s Test</a></li>
<li class="chapter" data-level="2.5.3" data-path="slr.html"><a href="slr.html#python-code-15"><i class="fa fa-check"></i><b>2.5.3</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="slr.html"><a href="slr.html#cor"><i class="fa fa-check"></i><b>2.6</b> Pearson Correlation</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="slr.html"><a href="slr.html#testcor"><i class="fa fa-check"></i><b>2.6.1</b> Statistical Test</a></li>
<li class="chapter" data-level="2.6.2" data-path="slr.html"><a href="slr.html#effect-of-anomalous-observations"><i class="fa fa-check"></i><b>2.6.2</b> Effect of Anomalous Observations</a></li>
<li class="chapter" data-level="2.6.3" data-path="slr.html"><a href="slr.html#the-correlation-matrix"><i class="fa fa-check"></i><b>2.6.3</b> The Correlation Matrix</a></li>
<li class="chapter" data-level="2.6.4" data-path="slr.html"><a href="slr.html#python-code-16"><i class="fa fa-check"></i><b>2.6.4</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="slr.html"><a href="slr.html#simple-linear-regression"><i class="fa fa-check"></i><b>2.7</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="slr.html"><a href="slr.html#slrassumptions"><i class="fa fa-check"></i><b>2.7.1</b> Assumptions of Linear Regression</a></li>
<li class="chapter" data-level="2.7.2" data-path="slr.html"><a href="slr.html#testing-for-association"><i class="fa fa-check"></i><b>2.7.2</b> Testing for Association</a></li>
<li class="chapter" data-level="2.7.3" data-path="slr.html"><a href="slr.html#python-code-17"><i class="fa fa-check"></i><b>2.7.3</b> Python Code</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mlr.html"><a href="mlr.html"><i class="fa fa-check"></i><b>3</b> Complex ANOVA and Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="mlr.html"><a href="mlr.html#two-way-anova"><i class="fa fa-check"></i><b>3.1</b> Two-Way ANOVA</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="mlr.html"><a href="mlr.html#exploration"><i class="fa fa-check"></i><b>3.1.1</b> Exploration</a></li>
<li class="chapter" data-level="3.1.2" data-path="mlr.html"><a href="mlr.html#model"><i class="fa fa-check"></i><b>3.1.2</b> Model</a></li>
<li class="chapter" data-level="3.1.3" data-path="mlr.html"><a href="mlr.html#post-hoc-testing"><i class="fa fa-check"></i><b>3.1.3</b> Post-Hoc Testing</a></li>
<li class="chapter" data-level="3.1.4" data-path="mlr.html"><a href="mlr.html#python-code-18"><i class="fa fa-check"></i><b>3.1.4</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="mlr.html"><a href="mlr.html#two-way-anova-with-interactions"><i class="fa fa-check"></i><b>3.2</b> Two-Way ANOVA with Interactions</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="mlr.html"><a href="mlr.html#post-hoc-testing-1"><i class="fa fa-check"></i><b>3.2.1</b> Post-Hoc Testing</a></li>
<li class="chapter" data-level="3.2.2" data-path="mlr.html"><a href="mlr.html#assumptions"><i class="fa fa-check"></i><b>3.2.2</b> Assumptions</a></li>
<li class="chapter" data-level="3.2.3" data-path="mlr.html"><a href="mlr.html#python-code-19"><i class="fa fa-check"></i><b>3.2.3</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="mlr.html"><a href="mlr.html#randomized-block-design"><i class="fa fa-check"></i><b>3.3</b> Randomized Block Design</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="mlr.html"><a href="mlr.html#garlic-bulb-weight-example"><i class="fa fa-check"></i><b>3.3.1</b> Garlic Bulb Weight Example</a></li>
<li class="chapter" data-level="3.3.2" data-path="mlr.html"><a href="mlr.html#assumptions-1"><i class="fa fa-check"></i><b>3.3.2</b> Assumptions</a></li>
<li class="chapter" data-level="3.3.3" data-path="mlr.html"><a href="mlr.html#python-code-20"><i class="fa fa-check"></i><b>3.3.3</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="mlr.html"><a href="mlr.html#multiple-linear-regression"><i class="fa fa-check"></i><b>3.4</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="mlr.html"><a href="mlr.html#model-structure"><i class="fa fa-check"></i><b>3.4.1</b> Model Structure</a></li>
<li class="chapter" data-level="3.4.2" data-path="mlr.html"><a href="mlr.html#global-local-inference"><i class="fa fa-check"></i><b>3.4.2</b> Global &amp; Local Inference</a></li>
<li class="chapter" data-level="3.4.3" data-path="mlr.html"><a href="mlr.html#assumptions-2"><i class="fa fa-check"></i><b>3.4.3</b> Assumptions</a></li>
<li class="chapter" data-level="3.4.4" data-path="mlr.html"><a href="mlr.html#multiple-coefficients-of-determination"><i class="fa fa-check"></i><b>3.4.4</b> Multiple Coefficients of Determination</a></li>
<li class="chapter" data-level="3.4.5" data-path="mlr.html"><a href="mlr.html#categorical-predictor-variables"><i class="fa fa-check"></i><b>3.4.5</b> Categorical Predictor Variables</a></li>
<li class="chapter" data-level="3.4.6" data-path="mlr.html"><a href="mlr.html#python-code-21"><i class="fa fa-check"></i><b>3.4.6</b> Python Code</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="model-selection.html"><a href="model-selection.html"><i class="fa fa-check"></i><b>4</b> Model Selection</a>
<ul>
<li class="chapter" data-level="4.1" data-path="model-selection.html"><a href="model-selection.html#selection-criteria"><i class="fa fa-check"></i><b>4.1</b> Selection Criteria</a></li>
<li class="chapter" data-level="4.2" data-path="model-selection.html"><a href="model-selection.html#stepwise-selection"><i class="fa fa-check"></i><b>4.2</b> Stepwise Selection</a>
<ul>
<li class="chapter" data-level="" data-path="model-selection.html"><a href="model-selection.html#forward"><i class="fa fa-check"></i>Forward</a></li>
<li class="chapter" data-level="" data-path="model-selection.html"><a href="model-selection.html#backward"><i class="fa fa-check"></i>Backward</a></li>
<li class="chapter" data-level="" data-path="model-selection.html"><a href="model-selection.html#stepwise"><i class="fa fa-check"></i>Stepwise</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="model-selection.html"><a href="model-selection.html#significance-levels"><i class="fa fa-check"></i><b>4.3</b> Significance Levels</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="model-selection.html"><a href="model-selection.html#python-code-22"><i class="fa fa-check"></i><b>4.3.1</b> Python Code</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="diag.html"><a href="diag.html"><i class="fa fa-check"></i><b>5</b> Diagnostics</a>
<ul>
<li class="chapter" data-level="5.0.1" data-path="diag.html"><a href="diag.html#python-code-23"><i class="fa fa-check"></i><b>5.0.1</b> Python Code:</a></li>
<li class="chapter" data-level="5.1" data-path="diag.html"><a href="diag.html#examining-residuals"><i class="fa fa-check"></i><b>5.1</b> Examining Residuals</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="diag.html"><a href="diag.html#python-code-24"><i class="fa fa-check"></i><b>5.1.1</b> Python Code:</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="diag.html"><a href="diag.html#misspecified-model"><i class="fa fa-check"></i><b>5.2</b> Misspecified Model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="diag.html"><a href="diag.html#python-code-25"><i class="fa fa-check"></i><b>5.2.1</b> Python Code:</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="diag.html"><a href="diag.html#constant-variance"><i class="fa fa-check"></i><b>5.3</b> Constant Variance</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="diag.html"><a href="diag.html#python-code-26"><i class="fa fa-check"></i><b>5.3.1</b> Python Code:</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="diag.html"><a href="diag.html#normality"><i class="fa fa-check"></i><b>5.4</b> Normality</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="diag.html"><a href="diag.html#python-code-27"><i class="fa fa-check"></i><b>5.4.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="diag.html"><a href="diag.html#correlated-errors"><i class="fa fa-check"></i><b>5.5</b> Correlated Errors</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="diag.html"><a href="diag.html#python-code-28"><i class="fa fa-check"></i><b>5.5.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="diag.html"><a href="diag.html#influential-observations-and-outliers"><i class="fa fa-check"></i><b>5.6</b> Influential Observations and Outliers</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="diag.html"><a href="diag.html#python-code-29"><i class="fa fa-check"></i><b>5.6.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="diag.html"><a href="diag.html#multicollinearity"><i class="fa fa-check"></i><b>5.7</b> Multicollinearity</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="diag.html"><a href="diag.html#python-code-30"><i class="fa fa-check"></i><b>5.7.1</b> Python Code</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html"><i class="fa fa-check"></i><b>6</b> Model Building and Scoring for Prediction</a>
<ul>
<li class="chapter" data-level="6.1" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#regularized-regression"><i class="fa fa-check"></i><b>6.1</b> Regularized Regression</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#penalties-in-models"><i class="fa fa-check"></i><b>6.1.1</b> Penalties in Models</a></li>
<li class="chapter" data-level="6.1.2" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#ridge-regression"><i class="fa fa-check"></i><b>6.1.2</b> Ridge Regression</a></li>
<li class="chapter" data-level="6.1.3" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#lasso"><i class="fa fa-check"></i><b>6.1.3</b> LASSO</a></li>
<li class="chapter" data-level="6.1.4" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#elastic-net"><i class="fa fa-check"></i><b>6.1.4</b> Elastic Net</a></li>
<li class="chapter" data-level="6.1.5" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#python-code-31"><i class="fa fa-check"></i><b>6.1.5</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#optimizing-penalties"><i class="fa fa-check"></i><b>6.2</b> Optimizing Penalties</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#cross-validation"><i class="fa fa-check"></i><b>6.2.1</b> Cross-Validation</a></li>
<li class="chapter" data-level="6.2.2" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#cv-in-regularized-regression"><i class="fa fa-check"></i><b>6.2.2</b> CV in Regularized Regression</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#model-comparisons"><i class="fa fa-check"></i><b>6.3</b> Model Comparisons</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#model-metrics"><i class="fa fa-check"></i><b>6.3.1</b> Model Metrics</a></li>
<li class="chapter" data-level="6.3.2" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#test-dataset-comparison"><i class="fa fa-check"></i><b>6.3.2</b> Test Dataset Comparison</a></li>
<li class="chapter" data-level="6.3.3" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#python-code-32"><i class="fa fa-check"></i><b>6.3.3</b> Python Code</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html"><i class="fa fa-check"></i><b>7</b> Categorical Data Analysis</a>
<ul>
<li class="chapter" data-level="7.1" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#describing-categorical-data"><i class="fa fa-check"></i><b>7.1</b> Describing Categorical Data</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#python-code-33"><i class="fa fa-check"></i><b>7.1.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#tests-of-association"><i class="fa fa-check"></i><b>7.2</b> Tests of Association</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#python-code-34"><i class="fa fa-check"></i><b>7.2.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#measures-of-association"><i class="fa fa-check"></i><b>7.3</b> Measures of Association</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#python-code-35"><i class="fa fa-check"></i><b>7.3.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#introduction-to-logistic-regression"><i class="fa fa-check"></i><b>7.4</b> Introduction to Logistic Regression</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#linear-probability-model"><i class="fa fa-check"></i><b>7.4.1</b> Linear Probability Model</a></li>
<li class="chapter" data-level="7.4.2" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#binary-logistic-regression"><i class="fa fa-check"></i><b>7.4.2</b> Binary Logistic Regression</a></li>
<li class="chapter" data-level="7.4.3" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#adding-categorical-variables"><i class="fa fa-check"></i><b>7.4.3</b> Adding Categorical Variables</a></li>
<li class="chapter" data-level="7.4.4" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#model-assessment"><i class="fa fa-check"></i><b>7.4.4</b> Model Assessment</a></li>
<li class="chapter" data-level="7.4.5" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#variable-selection-and-regularized-regression"><i class="fa fa-check"></i><b>7.4.5</b> Variable Selection and Regularized Regression</a></li>
<li class="chapter" data-level="7.4.6" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#python-code-36"><i class="fa fa-check"></i><b>7.4.6</b> Python Code</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Foundations</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="categorical-data-analysis" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Categorical Data Analysis<a href="categorical-data-analysis.html#categorical-data-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Everything analysis covered so far has used a continuous variable as a target variable of interest. What if our target variable was categorical instead of continuous? Our analysis must change to adjust.</p>
<p>This Chapter aims to answer the following questions:</p>
<ul>
<li><p>How do you explore categorical variables?</p>
<ul>
<li>Nominal vs. Ordinal</li>
<li>Tests of Association</li>
<li>Measures of Association</li>
</ul></li>
<li><p>How do you model a categorical target variable?</p>
<ul>
<li>Logistic Regression</li>
<li>Interpreting Logistic Regression</li>
<li>Assessing Logistic Regression</li>
</ul></li>
</ul>
<div id="describing-categorical-data" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Describing Categorical Data<a href="categorical-data-analysis.html#describing-categorical-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We need to first explore our data before building any models to try and explain/predict our categorical target variable. With categorical variables, we can look at the distribution of the categories as well as see if this distribution has any association with other variables. For this analysis we are going to still use our Ames housing data. Imagine you worked for a real estate agency and got a bonus check if you sold a house above $175,000 in value. Let’s create this variable in our data:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="categorical-data-analysis.html#cb1-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="categorical-data-analysis.html#cb1-2" tabindex="-1"></a>train <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="categorical-data-analysis.html#cb1-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Bonus =</span> <span class="fu">ifelse</span>(Sale_Price <span class="sc">&gt;</span> <span class="dv">175000</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span></code></pre></div>
<p>You are interested in what variables might be associated with obtaining a higher chance of getting a bonus (selling a house above $175,000). An association exists between two categorical variables if the distribution of one variable changes when the value of the other categorical changes. If there is no association, the distribution of the first variable is the same regardless of the value of the other variable. For example, if we wanted to know if obtaining a bonus on selling a house in Ames, Iowa was associated with whether the house had central air we could look at the distribution of bonus eligible houses. If we observe that 42% of homes with central air are bonus eligible and 42% of homes without central air are bonus eligible, then it appears that central air has no bearing on whether the home is bonus eligible. However, if instead we observe that only 3% of homes without central air are bonus eligible, but 44% of home with central air are bonus eligible, then it appears that having central air might be related to a home being bonus eligible.</p>
<p>To understand the distribution of categorical variables we need to look at frequency tables. A frequency table shows the number of observations that occur in certain categories or intervals. A one way frequency table examines all the categories of one variable. These are easily visualized with bar charts.</p>
<p>Let’s look at the distribution of both bonus eligibility and central air using the <code>table</code> function. The <code>ggplot</code> function with the <code>geom_bar</code> function allows us to view our data in a bar chart.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="categorical-data-analysis.html#cb2-1" tabindex="-1"></a><span class="fu">table</span>(train<span class="sc">$</span>Bonus)</span></code></pre></div>
<pre><code>## 
##    0    1 
## 1189  862</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="categorical-data-analysis.html#cb4-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> train) <span class="sc">+</span></span>
<span id="cb4-2"><a href="categorical-data-analysis.html#cb4-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Bonus))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="categorical-data-analysis.html#cb5-1" tabindex="-1"></a><span class="fu">table</span>(train<span class="sc">$</span>Central_Air)</span></code></pre></div>
<pre><code>## 
##    N    Y 
##  130 1921</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="categorical-data-analysis.html#cb7-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> train) <span class="sc">+</span></span>
<span id="cb7-2"><a href="categorical-data-analysis.html#cb7-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Central_Air))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Frequency tables show single variables, but if we want to explore two variables together we look at <strong>cross-tabulation</strong> tables. A cross-tabulation table shows the number of observations for each combination of the row and column variables.</p>
<p>Let’s again examine bonus eligibility, but this time across levels of central air. Again, we can use the <code>table</code> function. The <code>prop.table</code> function allows us to compare two variables in terms of proportions instead of frequencies.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="categorical-data-analysis.html#cb8-1" tabindex="-1"></a><span class="fu">table</span>(train<span class="sc">$</span>Central_Air, train<span class="sc">$</span>Bonus)</span></code></pre></div>
<pre><code>##    
##        0    1
##   N  126    4
##   Y 1063  858</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="categorical-data-analysis.html#cb10-1" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(train<span class="sc">$</span>Central_Air, train<span class="sc">$</span>Bonus))</span></code></pre></div>
<pre><code>##    
##               0           1
##   N 0.061433447 0.001950268
##   Y 0.518283764 0.418332521</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="categorical-data-analysis.html#cb12-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> train) <span class="sc">+</span></span>
<span id="cb12-2"><a href="categorical-data-analysis.html#cb12-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Bonus, <span class="at">fill =</span> Central_Air))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>From the above output we can see that 147 homes have no central air with only 5 of them being bonus eligible. However, there are 1904 homes that have central air with 835 of them being bonus eligible. For an even more detailed breakdown we can use the <code>CrossTable</code> function.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="categorical-data-analysis.html#cb13-1" tabindex="-1"></a><span class="fu">library</span>(gmodels)</span>
<span id="cb13-2"><a href="categorical-data-analysis.html#cb13-2" tabindex="-1"></a></span>
<span id="cb13-3"><a href="categorical-data-analysis.html#cb13-3" tabindex="-1"></a><span class="fu">CrossTable</span>(train<span class="sc">$</span>Central_Air, train<span class="sc">$</span>Bonus)</span></code></pre></div>
<pre><code>## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## | Chi-square contribution |
## |           N / Row Total |
## |           N / Col Total |
## |         N / Table Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  2051 
## 
##  
##                   | train$Bonus 
## train$Central_Air |         0 |         1 | Row Total | 
## ------------------|-----------|-----------|-----------|
##                 N |       126 |         4 |       130 | 
##                   |    34.023 |    46.930 |           | 
##                   |     0.969 |     0.031 |     0.063 | 
##                   |     0.106 |     0.005 |           | 
##                   |     0.061 |     0.002 |           | 
## ------------------|-----------|-----------|-----------|
##                 Y |      1063 |       858 |      1921 | 
##                   |     2.302 |     3.176 |           | 
##                   |     0.553 |     0.447 |     0.937 | 
##                   |     0.894 |     0.995 |           | 
##                   |     0.518 |     0.418 |           | 
## ------------------|-----------|-----------|-----------|
##      Column Total |      1189 |       862 |      2051 | 
##                   |     0.580 |     0.420 |           | 
## ------------------|-----------|-----------|-----------|
## 
## </code></pre>
<p>The advantage of the <code>CrossTable</code> function is that we can easily get not only the frequencies, but the cell, row, and column proportions. For example, the third number in each cell gives us the row proportion. For homes without central air, 96.6% of them are not bonus eligible, while 3.4% of them are. For homes with central air, 56.1% of the homes are not bonus eligible, while 43.9% of them are. This would appear that the distribution of bonus eligible homes changes across levels of central air - a relationship between the two variables. This expected relationship needs to be tested statistically for verification.</p>
<div id="python-code-33" class="section level3 hasAnchor" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> Python Code<a href="categorical-data-analysis.html#python-code-33" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb15"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb15-1"><a href="categorical-data-analysis.html#cb15-1" tabindex="-1"></a>train[<span class="st">&#39;Bonus&#39;</span>] <span class="op">=</span> np.where(train[<span class="st">&#39;Sale_Price&#39;</span>] <span class="op">&gt;</span> <span class="dv">175000</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span></code></pre></div>
<div class="sourceCode" id="cb16"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb16-1"><a href="categorical-data-analysis.html#cb16-1" tabindex="-1"></a>train[<span class="st">&#39;Bonus&#39;</span>].value_counts()</span></code></pre></div>
<pre><code>## Bonus
## 0    1162
## 1     889
## Name: count, dtype: int64</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb18-1"><a href="categorical-data-analysis.html#cb18-1" tabindex="-1"></a>plot <span class="op">=</span> (</span>
<span id="cb18-2"><a href="categorical-data-analysis.html#cb18-2" tabindex="-1"></a>    ggplot(train)</span>
<span id="cb18-3"><a href="categorical-data-analysis.html#cb18-3" tabindex="-1"></a>    <span class="op">+</span> geom_bar(aes(x<span class="op">=</span><span class="st">&#39;Bonus&#39;</span>))</span>
<span id="cb18-4"><a href="categorical-data-analysis.html#cb18-4" tabindex="-1"></a>    <span class="op">+</span> labs(x<span class="op">=</span><span class="st">&#39;Bonus&#39;</span>, y<span class="op">=</span><span class="st">&#39;Count&#39;</span>)</span>
<span id="cb18-5"><a href="categorical-data-analysis.html#cb18-5" tabindex="-1"></a>    <span class="op">+</span> theme_minimal()</span>
<span id="cb18-6"><a href="categorical-data-analysis.html#cb18-6" tabindex="-1"></a>)</span>
<span id="cb18-7"><a href="categorical-data-analysis.html#cb18-7" tabindex="-1"></a></span>
<span id="cb18-8"><a href="categorical-data-analysis.html#cb18-8" tabindex="-1"></a>plot.show()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-9-1.png" width="614" /></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb19-1"><a href="categorical-data-analysis.html#cb19-1" tabindex="-1"></a>train[<span class="st">&#39;Central_Air&#39;</span>].value_counts()</span></code></pre></div>
<pre><code>## Central_Air
## Y    1913
## N     138
## Name: count, dtype: int64</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb21-1"><a href="categorical-data-analysis.html#cb21-1" tabindex="-1"></a>plot <span class="op">=</span> (</span>
<span id="cb21-2"><a href="categorical-data-analysis.html#cb21-2" tabindex="-1"></a>    ggplot(train)</span>
<span id="cb21-3"><a href="categorical-data-analysis.html#cb21-3" tabindex="-1"></a>    <span class="op">+</span> geom_bar(aes(x<span class="op">=</span><span class="st">&#39;Central_Air&#39;</span>))</span>
<span id="cb21-4"><a href="categorical-data-analysis.html#cb21-4" tabindex="-1"></a>    <span class="op">+</span> labs(x<span class="op">=</span><span class="st">&#39;Central_Air&#39;</span>, y<span class="op">=</span><span class="st">&#39;Count&#39;</span>)</span>
<span id="cb21-5"><a href="categorical-data-analysis.html#cb21-5" tabindex="-1"></a>    <span class="op">+</span> theme_minimal()</span>
<span id="cb21-6"><a href="categorical-data-analysis.html#cb21-6" tabindex="-1"></a>)</span>
<span id="cb21-7"><a href="categorical-data-analysis.html#cb21-7" tabindex="-1"></a></span>
<span id="cb21-8"><a href="categorical-data-analysis.html#cb21-8" tabindex="-1"></a>plot.show()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-10-3.png" width="614" /></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb22-1"><a href="categorical-data-analysis.html#cb22-1" tabindex="-1"></a>plot <span class="op">=</span> (</span>
<span id="cb22-2"><a href="categorical-data-analysis.html#cb22-2" tabindex="-1"></a>    ggplot(train)</span>
<span id="cb22-3"><a href="categorical-data-analysis.html#cb22-3" tabindex="-1"></a>    <span class="op">+</span> geom_bar(aes(x<span class="op">=</span><span class="st">&#39;Bonus&#39;</span>, fill<span class="op">=</span><span class="st">&#39;Central_Air&#39;</span>), position<span class="op">=</span><span class="st">&#39;stack&#39;</span>)</span>
<span id="cb22-4"><a href="categorical-data-analysis.html#cb22-4" tabindex="-1"></a>    <span class="op">+</span> labs(x<span class="op">=</span><span class="st">&#39;Bonus&#39;</span>, y<span class="op">=</span><span class="st">&#39;Count&#39;</span>, fill<span class="op">=</span><span class="st">&#39;Central_Air&#39;</span>)</span>
<span id="cb22-5"><a href="categorical-data-analysis.html#cb22-5" tabindex="-1"></a>    <span class="op">+</span> theme_minimal()</span>
<span id="cb22-6"><a href="categorical-data-analysis.html#cb22-6" tabindex="-1"></a>)</span>
<span id="cb22-7"><a href="categorical-data-analysis.html#cb22-7" tabindex="-1"></a></span>
<span id="cb22-8"><a href="categorical-data-analysis.html#cb22-8" tabindex="-1"></a>plot.show()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-11-5.png" width="614" /></p>
<div class="sourceCode" id="cb23"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb23-1"><a href="categorical-data-analysis.html#cb23-1" tabindex="-1"></a>pd.crosstab(index <span class="op">=</span> train[<span class="st">&#39;Central_Air&#39;</span>], columns <span class="op">=</span> train[<span class="st">&#39;Bonus&#39;</span>])</span></code></pre></div>
<pre><code>## Bonus           0    1
## Central_Air           
## N             132    6
## Y            1030  883</code></pre>
</div>
</div>
<div id="tests-of-association" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Tests of Association<a href="categorical-data-analysis.html#tests-of-association" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Much like in Chapter <a href="slr.html#slr">2</a> we have statistical tests to evaluate relationships between two categorical variables. The null hypothesis for these statistical tests is that the two variables have no association - the distribution of one variable does not change across levels of another variable. The alternative hypothesis is an association between the two variables - the distribution of one variable changes across levels of another variable.</p>
<p>These statistical tests follow a <span class="math inline">\(\chi^2\)</span>-distribution. The <span class="math inline">\(\chi^2\)</span>-distribution is a distribution that has the following characteristics:</p>
<ul>
<li>Bounded below by 0</li>
<li>Right-skewed</li>
<li>One set of degrees of freedom</li>
</ul>
<p>A plot of a variety of <span class="math inline">\(\chi^2\)</span>-distributions is shown here:</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-13-7.png" width="672" /></p>
<p>Two common <span class="math inline">\(\chi^2\)</span> tests are the Pearson and Likelihood Ratio <span class="math inline">\(\chi^2\)</span> tests. They compare the observed count of observations in each cell of a cross-tabulation table between two variables to their expected count <strong>if</strong> there was no relationship. The expected cell count applies the overall distribution of one variable across all the levels of the other variable. For example, overall 59% of all homes are not bonus eligible. <strong>If</strong> that were to apply to every level of central air, then the 140 homes without central air would be expected to have 86.73 ( $ = 147 $ ) of them would be bonus eligible while 60.27 ( $ = 147 $ ) of them would not be bonus eligible. We actually observe 142 and 5 homes for each of these categories respectively. The further the observed data is from the expected data, the more evidence we have that there is a relationship between the two variables.</p>
<p>The test statistic for the Pearson <span class="math inline">\(\chi^2\)</span> test is the following:</p>
<p><span class="math display">\[
\chi^2_P = \sum_{i=1}^R \sum_{j=1}^C \frac{(Obs_{i,j} - Exp_{i,j})^2}{Exp_{i,j}}
\]</span>
From the equation above, the closer that the observed count of each cross-tabulation table cell to the expected count, the smaller the test statistic. As with all previous hypothesis tests, the smaller the test statistic, the larger the p-value, implying less evidence for the alternative hypothesis.</p>
<p>Let’s examine the relationship between central air and bonus eligibility using the <code>chisq.test</code> function.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="categorical-data-analysis.html#cb25-1" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(train<span class="sc">$</span>Central_Air, train<span class="sc">$</span>Bonus))</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  table(train$Central_Air, train$Bonus)
## X-squared = 84.732, df = 1, p-value &lt; 2.2e-16</code></pre>
<p>The above results shows an extremely small p-value that is below any reasonable significance level. This implies that we have statistical evidence for a relationship between having central air and bonus eligibility of homes. The p-value comes from a <span class="math inline">\(\chi^2\)</span>-distribution with degrees of freedom that equal the product of the number of rows minus one and the number of columns minus one.</p>
<p>Another common test is the Likelihood Ratio test. The test statistic for this is the following:</p>
<p><span class="math display">\[
\chi^2_L = 2 \times \sum_{i=1}^R \sum_{j=1}^C Obs_{i,j} \times \log(\frac{Obs_{i,j}}{Exp_{i,j}})
\]</span></p>
<p>The p-value comes from a <span class="math inline">\(\chi^2\)</span>-distribution with degrees of freedom that equal the product of the number of rows minus one and the number of columns minus one. Both of the above tests have a sample size requirement. The sample size requirement is 80% or more of the cells in the cross-tabulation table need <strong>expected</strong> count larger
than 5.</p>
<p>For smaller sample sizes, this might be hard to meet. In those situations, we can use a more computationally expensive test called Fisher’s exact test. This test calculates every possible permutation of the data being evaluated to calculate the p-value without any distributional assumptions. To perform this test we can use the <code>fisher.test</code> function.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="categorical-data-analysis.html#cb27-1" tabindex="-1"></a><span class="fu">fisher.test</span>(<span class="fu">table</span>(train<span class="sc">$</span>Central_Air, train<span class="sc">$</span>Bonus))</span></code></pre></div>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  table(train$Central_Air, train$Bonus)
## p-value &lt; 2.2e-16
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##   9.621024 95.281143
## sample estimates:
## odds ratio 
##   25.40401</code></pre>
<p>We see the same results as with the Pearson test because the assumptions were met for sample size.</p>
<p>Both the Pearson and Likelihood Ratio <span class="math inline">\(\chi^2\)</span> tests can handle any type of categorical variable either ordinal, nominal, or both. However, ordinal variables provide us extra information since the order of the categories actually matters compared to nominal. We can test for even more with ordinal variables against other ordinal variables whether two ordinal variables have a <strong>linear relationship</strong> as compared to just a general one. An ordinal test for association is the Mantel-Haenszel <span class="math inline">\(\chi^2\)</span> test. The test statistic for the Mantel-Haenszel <span class="math inline">\(\chi^2\)</span> test is the following:</p>
<p><span class="math display">\[
\chi^2_{MH} = (n-1)r^2
\]</span>
where <span class="math inline">\(r^2\)</span> is the Spearman’s correlation between the column and row variables. This test follows a <span class="math inline">\(\chi^2\)</span>-distribution with only one degree of freedom.</p>
<p>Since both the central air and bonus eligibility variables are binary, they are ordinal. Since they are both ordinal, we should use the Mantel-Haenszel <span class="math inline">\(\chi^2\)</span> test with the <code>CMHtest</code> function. In the main output table, the first row is the Mantel-Haenszel <span class="math inline">\(\chi^2\)</span> test.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="categorical-data-analysis.html#cb29-1" tabindex="-1"></a><span class="fu">library</span>(vcdExtra)</span>
<span id="cb29-2"><a href="categorical-data-analysis.html#cb29-2" tabindex="-1"></a></span>
<span id="cb29-3"><a href="categorical-data-analysis.html#cb29-3" tabindex="-1"></a><span class="fu">CMHtest</span>(<span class="fu">table</span>(train<span class="sc">$</span>Central_Air, train<span class="sc">$</span>Bonus))<span class="sc">$</span>table[<span class="dv">1</span>,]</span></code></pre></div>
<pre><code>##        Chisq           Df         Prob 
## 8.638875e+01 1.000000e+00 1.478232e-20</code></pre>
<p>From here we can see another extremely small p-value as we saw in earlier, more general <span class="math inline">\(\chi^2\)</span> tests.</p>
<div id="python-code-34" class="section level3 hasAnchor" number="7.2.1">
<h3><span class="header-section-number">7.2.1</span> Python Code<a href="categorical-data-analysis.html#python-code-34" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb31"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb31-1"><a href="categorical-data-analysis.html#cb31-1" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> chi2_contingency</span>
<span id="cb31-2"><a href="categorical-data-analysis.html#cb31-2" tabindex="-1"></a></span>
<span id="cb31-3"><a href="categorical-data-analysis.html#cb31-3" tabindex="-1"></a>chi2_contingency(pd.crosstab(index <span class="op">=</span> train[<span class="st">&#39;Central_Air&#39;</span>], columns <span class="op">=</span> train[<span class="st">&#39;Bonus&#39;</span>]), correction <span class="op">=</span> <span class="va">True</span>)</span></code></pre></div>
<pre><code>## Chi2ContingencyResult(statistic=89.93013829077994, pvalue=2.4671990961829127e-21, dof=1, expected_freq=array([[  78.18430034,   59.81569966],
##        [1083.81569966,  829.18430034]]))</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb33-1"><a href="categorical-data-analysis.html#cb33-1" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> fisher_exact</span>
<span id="cb33-2"><a href="categorical-data-analysis.html#cb33-2" tabindex="-1"></a></span>
<span id="cb33-3"><a href="categorical-data-analysis.html#cb33-3" tabindex="-1"></a>fisher_exact(pd.crosstab(index <span class="op">=</span> train[<span class="st">&#39;Central_Air&#39;</span>], columns <span class="op">=</span> train[<span class="st">&#39;Bonus&#39;</span>]))</span></code></pre></div>
<pre><code>## SignificanceResult(statistic=18.860194174757282, pvalue=1.1286497199252816e-26)</code></pre>
<p>No real Mantel-Haenszel options in Python that work for anything more than a 2x2 table so I wouldn’t trust them.</p>
</div>
</div>
<div id="measures-of-association" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Measures of Association<a href="categorical-data-analysis.html#measures-of-association" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Tests of association are best designed for just that, testing the existence of an association between two categorical variables. However, just like we saw in Chapter <a href="intro-stat.html#eda">1.1</a>, hypothesis tests are impacted by sample size. When we have the same sample size, tests of association can rank significance of variables with p-values. However, when sample sizes are not the same between two tests, the tests of association are not best for comparing the strength of an association. In those scenarios, we have measures of strength of association that can be compared across any sample size.</p>
<p>Measures of association were not designed to test if an association exists, as that is what statistical testing is for. They are designed to measure the strength of association. There are dozens of these measures. Three of the most common are the following:</p>
<ul>
<li>Odds Ratios (only for comparing two binary variables)</li>
<li>Cramer’s V (able to compare nominal variables with any number of categories)</li>
<li>Spearman’s Correlation (able to compare ordinal variables with any number of categories)</li>
</ul>
<p>An <strong>odds ratio</strong> indicates how much more likely, with respect to <strong>odds</strong>, a certain event occurs in one group relative to its occurrence in another group. The odds of an event occurring is <em>not</em> the same as the probability that an event occurs. The odds of an event occurring is the probability the event occurs divided by the probability that event does not occur.</p>
<p><span class="math display">\[
Odds = \frac{p}{1-p}
\]</span></p>
<p>Let’s again examine the cross-tabulation table between central air and bonus eligibility.</p>
<pre><code>## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## | Chi-square contribution |
## |           N / Row Total |
## |           N / Col Total |
## |         N / Table Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  2051 
## 
##  
##                   | train$Bonus 
## train$Central_Air |         0 |         1 | Row Total | 
## ------------------|-----------|-----------|-----------|
##                 N |       126 |         4 |       130 | 
##                   |    34.023 |    46.930 |           | 
##                   |     0.969 |     0.031 |     0.063 | 
##                   |     0.106 |     0.005 |           | 
##                   |     0.061 |     0.002 |           | 
## ------------------|-----------|-----------|-----------|
##                 Y |      1063 |       858 |      1921 | 
##                   |     2.302 |     3.176 |           | 
##                   |     0.553 |     0.447 |     0.937 | 
##                   |     0.894 |     0.995 |           | 
##                   |     0.518 |     0.418 |           | 
## ------------------|-----------|-----------|-----------|
##      Column Total |      1189 |       862 |      2051 | 
##                   |     0.580 |     0.420 |           | 
## ------------------|-----------|-----------|-----------|
## 
## </code></pre>
<p>Let’s look at the row without central air. The probability that a home without central air is not bonus eligible is 96.6%. That implies that the odds of not being bonus eligible in homes without central air is 28.41 (= 0.966/0.034). For homes with central air, the odds of not being bonus eligible are 1.28 (= 0.561/0.439). The odds ratio between these two would be approximately 22.2 (= 28.41/1.28). In other words, homes without central air are 22.2 times more likely (in terms of odds) to not be bonus eligible as compared to homes with central air. This relationship is intuitive based on the numbers we have seen. Without going into details, it can also be shown that homes with central air are 22.2 times as likely (in terms of odds) to be bonus eligible.</p>
<p>We can use the <code>OddsRatio</code> function to get these same results.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="categorical-data-analysis.html#cb36-1" tabindex="-1"></a><span class="fu">library</span>(DescTools)</span>
<span id="cb36-2"><a href="categorical-data-analysis.html#cb36-2" tabindex="-1"></a></span>
<span id="cb36-3"><a href="categorical-data-analysis.html#cb36-3" tabindex="-1"></a><span class="fu">OddsRatio</span>(<span class="fu">table</span>(train<span class="sc">$</span>Central_Air, train<span class="sc">$</span>Bonus))</span></code></pre></div>
<pre><code>## [1] 25.42521</code></pre>
<p><strong>Cramer’s V</strong> is another measure of strength of association. Cramer’s V is calculated as follows:</p>
<p><span class="math display">\[
V = \sqrt{\frac{\chi^2_P/n}{\min(Rows-1, Columns-1)}}
\]</span></p>
<p>Cramer’s V is bounded between 0 and 1 for every comparison other than two binary variables. For two binary variables being compared the bounds are -1 to 1. The idea is still the same for both. The further the value is from 0, the stronger the relationship. Unfortunately, unlike <span class="math inline">\(R^2\)</span>, Cramer’s V has no interpretative value. It can only be used for comparison.</p>
<p>We use the <code>assocstats</code> function to get the Cramer’s V value. This function also provides the Pearson and Likelihood Ratio <span class="math inline">\(\chi^2\)</span> tests as well.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="categorical-data-analysis.html#cb38-1" tabindex="-1"></a><span class="fu">assocstats</span>(<span class="fu">table</span>(train<span class="sc">$</span>Central_Air, train<span class="sc">$</span>Bonus))</span></code></pre></div>
<pre><code>##                      X^2 df P(&gt; X^2)
## Likelihood Ratio 114.053  1        0
## Pearson           86.431  1        0
## 
## Phi-Coefficient   : 0.205 
## Contingency Coeff.: 0.201 
## Cramer&#39;s V        : 0.205</code></pre>
<p>Lastly, we have Spearman’s correlation. Much like the Mantel-Haenszel test of association was specifically designed for comparing two ordinal variables, Spearman correlation measures the strength of association between two ordinal variables. Spearman is not limited to only categorical data analysis as it was also seen back in Chapter <a href="diag.html#diag">5</a> with detecting heteroskedasticity. Remember, Spearman correlation is a correlation on the ranks of the observations as compared to the actual values of the observations.</p>
<p>The <code>cor.test</code> function that gave us Pearson’s correlation also provides Spearman’s correlation.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="categorical-data-analysis.html#cb40-1" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="at">x =</span> <span class="fu">as.numeric</span>(<span class="fu">ordered</span>(train<span class="sc">$</span>Central_Air)), </span>
<span id="cb40-2"><a href="categorical-data-analysis.html#cb40-2" tabindex="-1"></a>         <span class="at">y =</span> <span class="fu">as.numeric</span>(<span class="fu">ordered</span>(train<span class="sc">$</span>Bonus)), </span>
<span id="cb40-3"><a href="categorical-data-analysis.html#cb40-3" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  x and y
## S = 1142769050, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.2052824</code></pre>
<p>As previously mentioned, these are only a few of the dozens of different measures of association that exist. However, they are the most used ones.</p>
<div id="python-code-35" class="section level3 hasAnchor" number="7.3.1">
<h3><span class="header-section-number">7.3.1</span> Python Code<a href="categorical-data-analysis.html#python-code-35" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Odds Ratios are the statistic calculated from the Fisher’s Exact test from the previous code:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb42-1"><a href="categorical-data-analysis.html#cb42-1" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> fisher_exact</span>
<span id="cb42-2"><a href="categorical-data-analysis.html#cb42-2" tabindex="-1"></a></span>
<span id="cb42-3"><a href="categorical-data-analysis.html#cb42-3" tabindex="-1"></a>fisher_exact(pd.crosstab(index <span class="op">=</span> train[<span class="st">&#39;Central_Air&#39;</span>], columns <span class="op">=</span> train[<span class="st">&#39;Bonus&#39;</span>]))</span></code></pre></div>
<pre><code>## SignificanceResult(statistic=18.860194174757282, pvalue=1.1286497199252816e-26)</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb44-1"><a href="categorical-data-analysis.html#cb44-1" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> fisher_exact</span>
<span id="cb44-2"><a href="categorical-data-analysis.html#cb44-2" tabindex="-1"></a></span>
<span id="cb44-3"><a href="categorical-data-analysis.html#cb44-3" tabindex="-1"></a>fisher_exact(pd.crosstab(index <span class="op">=</span> train[<span class="st">&#39;Central_Air&#39;</span>], columns <span class="op">=</span> train[<span class="st">&#39;Bonus&#39;</span>]))</span></code></pre></div>
<pre><code>## SignificanceResult(statistic=18.860194174757282, pvalue=1.1286497199252816e-26)</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb46-1"><a href="categorical-data-analysis.html#cb46-1" tabindex="-1"></a><span class="im">from</span> scipy.stats.contingency <span class="im">import</span> association</span>
<span id="cb46-2"><a href="categorical-data-analysis.html#cb46-2" tabindex="-1"></a></span>
<span id="cb46-3"><a href="categorical-data-analysis.html#cb46-3" tabindex="-1"></a>association(pd.crosstab(index <span class="op">=</span> train[<span class="st">&#39;Central_Air&#39;</span>], columns <span class="op">=</span> train[<span class="st">&#39;Bonus&#39;</span>]), method <span class="op">=</span> <span class="st">&quot;cramer&quot;</span>)</span></code></pre></div>
<pre><code>## 0.2113604274410272</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb48-1"><a href="categorical-data-analysis.html#cb48-1" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> spearmanr</span>
<span id="cb48-2"><a href="categorical-data-analysis.html#cb48-2" tabindex="-1"></a></span>
<span id="cb48-3"><a href="categorical-data-analysis.html#cb48-3" tabindex="-1"></a>spearmanr(train[<span class="st">&#39;Central_Air&#39;</span>], train[<span class="st">&#39;Bonus&#39;</span>])</span></code></pre></div>
<pre><code>## SignificanceResult(statistic=0.21136042744102718, pvalue=3.822493169056582e-22)</code></pre>
</div>
</div>
<div id="introduction-to-logistic-regression" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Introduction to Logistic Regression<a href="categorical-data-analysis.html#introduction-to-logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>After exploring the categorical target variable, we can move on to modeling the categorical target variable. Logistic regression is a fundamental statistical analysis for data science and analytics. It part of a class of modeling techniques known as classification models since they are trying to predict categorical target variables. This target variable can be binary, ordinal, or even nominal in its structure. The primary focus will be binary logistic regression. It is the most common type of logistic regression, and sets up the foundation for both ordinal and nominal logistic regression.</p>
<p>Ordinary least squares regression is not the best approach to modeling categorical target variables. Mathematically, it can be shown that with a binary target variable coded as 0 and 1, an OLS linear regression model will produce the <strong>linear probability model</strong>.</p>
<div id="linear-probability-model" class="section level3 hasAnchor" number="7.4.1">
<h3><span class="header-section-number">7.4.1</span> Linear Probability Model<a href="categorical-data-analysis.html#linear-probability-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The linear probability model is not as widely used since probabilities do not tend to follow the properties of linearity in relation to their predictors. Also, the linear probability model possibly produces predictions outside of the bounds of 0 and 1 (where probabilities should be!). For completeness sake however, here is the linear probability model using the <code>lm</code> function to try and predict bonus eligibility.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="categorical-data-analysis.html#cb50-1" tabindex="-1"></a>lp.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Bonus <span class="sc">~</span> Gr_Liv_Area, <span class="at">data =</span> train)</span>
<span id="cb50-2"><a href="categorical-data-analysis.html#cb50-2" tabindex="-1"></a></span>
<span id="cb50-3"><a href="categorical-data-analysis.html#cb50-3" tabindex="-1"></a><span class="fu">with</span>(train, <span class="fu">plot</span>(<span class="at">x =</span> Gr_Liv_Area, <span class="at">y =</span> Bonus,</span>
<span id="cb50-4"><a href="categorical-data-analysis.html#cb50-4" tabindex="-1"></a>               <span class="at">main =</span> <span class="st">&#39;OLS Regression?&#39;</span>,</span>
<span id="cb50-5"><a href="categorical-data-analysis.html#cb50-5" tabindex="-1"></a>               <span class="at">xlab =</span> <span class="st">&#39;Greater Living Area (Sqft)&#39;</span>,</span>
<span id="cb50-6"><a href="categorical-data-analysis.html#cb50-6" tabindex="-1"></a>               <span class="at">ylab =</span> <span class="st">&#39;Bonus Eligibility&#39;</span>))</span>
<span id="cb50-7"><a href="categorical-data-analysis.html#cb50-7" tabindex="-1"></a><span class="fu">abline</span>(lp.model)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>Even though it doesn’t appear to really look like our data, let’s fit this linear probability model anyway for completeness sake.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="categorical-data-analysis.html#cb51-1" tabindex="-1"></a>lp.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Bonus <span class="sc">~</span> Gr_Liv_Area, <span class="at">data =</span> train)</span>
<span id="cb51-2"><a href="categorical-data-analysis.html#cb51-2" tabindex="-1"></a></span>
<span id="cb51-3"><a href="categorical-data-analysis.html#cb51-3" tabindex="-1"></a><span class="fu">summary</span>(lp.model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Bonus ~ Gr_Liv_Area, data = train)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.48631 -0.29532 -0.09408  0.38524  0.86915 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -4.436e-01  2.782e-02  -15.95   &lt;2e-16 ***
## Gr_Liv_Area  5.751e-04  1.756e-05   32.75   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4001 on 2049 degrees of freedom
## Multiple R-squared:  0.3436, Adjusted R-squared:  0.3433 
## F-statistic:  1072 on 1 and 2049 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="categorical-data-analysis.html#cb53-1" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">rstandard</span>(lp.model),</span>
<span id="cb53-2"><a href="categorical-data-analysis.html#cb53-2" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">&quot;Standardized Residuals&quot;</span>,</span>
<span id="cb53-3"><a href="categorical-data-analysis.html#cb53-3" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">&quot;Normal Scores&quot;</span>,</span>
<span id="cb53-4"><a href="categorical-data-analysis.html#cb53-4" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">&quot;QQ-Plot of Residuals&quot;</span>)</span>
<span id="cb53-5"><a href="categorical-data-analysis.html#cb53-5" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">rstandard</span>(lp.model))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="categorical-data-analysis.html#cb54-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predict</span>(lp.model), <span class="fu">resid</span>(lp.model), </span>
<span id="cb54-2"><a href="categorical-data-analysis.html#cb54-2" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Residuals&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Predicted Values&quot;</span>, </span>
<span id="cb54-3"><a href="categorical-data-analysis.html#cb54-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Residuals of Linear Probability Model&quot;</span>) </span>
<span id="cb54-4"><a href="categorical-data-analysis.html#cb54-4" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>, <span class="dv">0</span>) </span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-28-2.png" width="672" /></p>
<p>As we can see from the charts above, the assumptions of ordinary least squares don’t really hold in this situation. Therefore, we should be careful interpreting the results of the model. Maybe a better model won’t have these problems?</p>
</div>
<div id="binary-logistic-regression" class="section level3 hasAnchor" number="7.4.2">
<h3><span class="header-section-number">7.4.2</span> Binary Logistic Regression<a href="categorical-data-analysis.html#binary-logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Due to the limitations of the linear probability model, people typically just use the binary logistic regression model. The logistic regression model does not have the limitations of the linear probability model. The outcome of the logistic regression model is the probability of getting a 1 in a binary variable. That probability is calculated as follows:</p>
<p><span class="math display">\[
p_i = \frac{1}{1+e^{-(\beta_0 + \beta_1x_{1,i} + \cdots + \beta_k x_{k,i})}}
\]</span></p>
<p>This function has the desired properties for predicting probabilities. The predicted probability from the above equation will always be between 0 and 1. The parameter estimates do not enter the function linearly (this is a non-linear regression model), and the rate of change of the probability varies as the predictor variables vary as seen in Figure <a href="categorical-data-analysis.html#fig:logistic">7.1</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:logistic"></span>
<img src="img/logistic.png" alt="Example of a Logistic Curve" width="50%" />
<p class="caption">
Figure 7.1: Example of a Logistic Curve
</p>
</div>
<p>To create a linear model, a <strong>link function</strong> is applied to the probabilities. The specific link function for logistic regression is called the <strong>logit</strong> function.</p>
<p><span class="math display">\[
logit(p_i) = \log(\frac{p_i}{1-p_i}) = \beta_0 + \beta_1x_{1,i} + \cdots + \beta_k x_{k,i}
\]</span></p>
<p>The relationship between the predictor variables and the logits are linear in nature as the logits themselves are unbounded. This structure looks much more like our linear regression model structure. However, logistic regression does not use OLS to estimate the coefficients in our model. OLS requires residuals which the logistic regression model does not provide. The target variable is binary in nature, but the predictions are probabilities. Therefore, we cannot calculate a traditional residual. Instead, logistic regression uses maximum likelihood estimation. This is not covered here.</p>
<p>There are two main assumptions for logistic regression:</p>
<ol style="list-style-type: decimal">
<li>Independence of observations</li>
<li>Linearity of the logit</li>
</ol>
<p>The first assumption of independence is the same as we had for linear regression. The second assumption implies that the logistic function transformation (the logit) actually makes a linear relationship with our predictor variables. This assumption can be tested, but will not be covered in this brief introduction to logistic regression.</p>
<p>Let’s build a logistic regression model. We will use the <code>glm</code> function to do this. The <code>glm</code> function has a similar structure to the <code>lm</code> function. The main difference is the <code>family = binomial(link = "logit")</code> option to specify that we are uses a logistic regression model. Again, there are many different link functions, but only the logistic link function (the logit) is being used here.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="categorical-data-analysis.html#cb55-1" tabindex="-1"></a>ames_logit <span class="ot">&lt;-</span> <span class="fu">glm</span>(Bonus <span class="sc">~</span> Gr_Liv_Area, </span>
<span id="cb55-2"><a href="categorical-data-analysis.html#cb55-2" tabindex="-1"></a>                   <span class="at">data =</span> train, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;logit&quot;</span>))</span>
<span id="cb55-3"><a href="categorical-data-analysis.html#cb55-3" tabindex="-1"></a><span class="fu">summary</span>(ames_logit)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Bonus ~ Gr_Liv_Area, family = binomial(link = &quot;logit&quot;), 
##     data = train)
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -6.4980679  0.2908138  -22.34   &lt;2e-16 ***
## Gr_Liv_Area  0.0041028  0.0001899   21.61   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 2790.9  on 2050  degrees of freedom
## Residual deviance: 1881.5  on 2049  degrees of freedom
## AIC: 1885.5
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Let’s examine the above output. Scanning down the output, you can see the actual logistic regression equation for the variable <code>Gr_Liv_Area</code>. Here we can see that it appears to be a significant variable at predicting bonus eligibility. However, the coefficient reported does not have the same usable interpretation as in linear regression. An increase of one unit of greater living area square footage is linearly related to the logit <strong>not</strong> the probability of bonus eligibility. We can transform this coefficient to make it more interpretable. A single unit increase in greater living area square footage <strong>does</strong> have a <span class="math inline">\(100 \times (e^\hat{\beta}-1)\%\)</span> increase in the average <strong>odds</strong> of bonus eligibility. We can use a combination of the <code>exp</code> and <code>coef</code> functions to obtain this number.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="categorical-data-analysis.html#cb57-1" tabindex="-1"></a><span class="dv">100</span><span class="sc">*</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="fu">coef</span>(ames_logit), <span class="fu">confint</span>(ames_logit)))<span class="sc">-</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                               2.5 %      97.5 %
## (Intercept) -99.8493653 -99.9160362 -99.7373217
## Gr_Liv_Area   0.4111248   0.3746797   0.4494483</code></pre>
<p>In other words, every additional square foot in greater living area in the home leads to an average increase in odds of 0.385% to be bonus eligible.</p>
</div>
<div id="adding-categorical-variables" class="section level3 hasAnchor" number="7.4.3">
<h3><span class="header-section-number">7.4.3</span> Adding Categorical Variables<a href="categorical-data-analysis.html#adding-categorical-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Similar to linear regression as we learned in Chapter <a href="mlr.html#mlr">3</a>, logistic regression can have both continuous and categorical predictors for our categorical target variable. Let’s add both central air as well as number of fireplaces to our logistic regression model.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="categorical-data-analysis.html#cb60-1" tabindex="-1"></a>ames_logit2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Bonus <span class="sc">~</span> Gr_Liv_Area <span class="sc">+</span> Central_Air <span class="sc">+</span> <span class="fu">factor</span>(Fireplaces), </span>
<span id="cb60-2"><a href="categorical-data-analysis.html#cb60-2" tabindex="-1"></a>                  <span class="at">data =</span> train, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;logit&quot;</span>))</span>
<span id="cb60-3"><a href="categorical-data-analysis.html#cb60-3" tabindex="-1"></a><span class="fu">summary</span>(ames_logit2)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Bonus ~ Gr_Liv_Area + Central_Air + factor(Fireplaces), 
##     family = binomial(link = &quot;logit&quot;), data = train)
## 
## Coefficients:
##                       Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)         -1.158e+01  7.855e-01 -14.742  &lt; 2e-16 ***
## Gr_Liv_Area          4.166e-03  2.183e-04  19.087  &lt; 2e-16 ***
## Central_AirY         4.583e+00  6.410e-01   7.150 8.69e-13 ***
## factor(Fireplaces)1  1.013e+00  1.281e-01   7.906 2.66e-15 ***
## factor(Fireplaces)2  3.649e-01  2.447e-01   1.491    0.136    
## factor(Fireplaces)3  4.537e-01  1.041e+00   0.436    0.663    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 2790.9  on 2050  degrees of freedom
## Residual deviance: 1679.1  on 2045  degrees of freedom
## AIC: 1691.1
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>Just like with linear regression, categorical predictor variables are a comparison between two categories. Again, the coefficients from the logistic regression model need to be transformed to be interpreted.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="categorical-data-analysis.html#cb62-1" tabindex="-1"></a><span class="dv">100</span><span class="sc">*</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="fu">coef</span>(ames_logit2), <span class="fu">confint</span>(ames_logit2)))<span class="sc">-</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>##                                         2.5 %        97.5 %
## (Intercept)          -99.9990646  -99.9998206   -99.9960225
## Gr_Liv_Area            0.4174825    0.3755847     0.4615482
## Central_AirY        9677.6456694 2981.4405074 39222.7811352
## factor(Fireplaces)1  175.3373539  114.3240763   254.2182994
## factor(Fireplaces)2   44.0359300  -11.0028029   132.5770593
## factor(Fireplaces)3   57.4104171  -77.5875200  1394.7564635</code></pre>
<p>Let’s use the first fireplace variable as an example. A home with one fireplace has, on average, 167.04% higher odds of being bonus eligible as compared to a home with zero fireplaces.</p>
</div>
<div id="model-assessment" class="section level3 hasAnchor" number="7.4.4">
<h3><span class="header-section-number">7.4.4</span> Model Assessment<a href="categorical-data-analysis.html#model-assessment" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are dozens of different ways to evaluate a logistic regression model. We will cover one popular way here - concordance. Counting the number of <strong>concordant</strong>, <strong>discordant</strong>, and <strong>tied</strong> pairs is a way to to assess how well the model fits the data.</p>
<p>To find concordant, discordant, and tied pairs, we must compare all of the 0’s in the target variable to all of the 1’s. For our example, we will compare every pair of homes where one home is bonus eligible and one is not (every 0 and 1 pair). A <strong>concordant</strong> pair is a 0 and 1 pair where the bonus eligible home (the 1 in our model) has a higher predicted probability than the non-bonus eligible home (the 0 in our model) - our model successfully ordered these two observations by probability. It does not matter what the actual predicted probability values are as long as the bonus eligible home has a higher predicted probability than the non-bonus eligible home. A <strong>discordant</strong> pair is a 0 and 1 pair where the bonus eligible home (the 1 in our model) has a lower predicted probability than the non-bonus eligible home (the 0 in our model) - our model unsuccessfully ordered the homes. It does not matter what the actual predicted probability values are as long as the bonus eligible home has a lower predicted probability than the non-bonus eligible home. A <strong>tied</strong> pair is a 0 and 1 pair where the bonus eligible home has the same predicted probability as the non-bonus eligible home - the model is confused and sees these two different things as the same. In general, you want a high percentage of concordant pairs and low percentages of discordant and tied pairs.</p>
<p>We can use the <code>concordance</code> function from the <code>survival</code> package to obtain these values on our predictions from the <code>predict</code> function.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="categorical-data-analysis.html#cb64-1" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb64-2"><a href="categorical-data-analysis.html#cb64-2" tabindex="-1"></a></span>
<span id="cb64-3"><a href="categorical-data-analysis.html#cb64-3" tabindex="-1"></a>survival<span class="sc">::</span><span class="fu">concordance</span>(ames_logit)</span></code></pre></div>
<pre><code>## Call:
## concordance.lm(object = ames_logit)
## 
## n= 2051 
## Concordance= 0.8675 se= 0.007596
## concordant discordant     tied.x     tied.y    tied.xy 
##     888831     135490        597    1075272       2085</code></pre>
<p>From the above output we have a concordance of 86.3% for our model. There is no good or bad value as this can only be compared with another model to see which is better. Let’s compare this to our model with the categorical variables.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="categorical-data-analysis.html#cb66-1" tabindex="-1"></a>survival<span class="sc">::</span><span class="fu">concordance</span>(ames_logit2)</span></code></pre></div>
<pre><code>## Call:
## concordance.lm(object = ames_logit2)
## 
## n= 2051 
## Concordance= 0.8924 se= 0.006783
## concordant discordant     tied.x     tied.y    tied.xy 
##     914478     110174        266    1076141       1216</code></pre>
<p>We can see that the model with categorical predictors added to it has a higher concordance at 88.4%. That implies that our model is correctly able to rank our observations 88.4% of the time. This is <strong>NOT</strong> the same thing as saying our model is 88.4% accurate. Accuracy (which is not covered here) deals with a prediction being correct or incorrect. Concordance is only measuring how often we are able to predict 1’s with higher probability than 0’s - again, correctly ranking the observations.</p>
</div>
<div id="variable-selection-and-regularized-regression" class="section level3 hasAnchor" number="7.4.5">
<h3><span class="header-section-number">7.4.5</span> Variable Selection and Regularized Regression<a href="categorical-data-analysis.html#variable-selection-and-regularized-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As with linear regression in Chapters <a href="#reg"><strong>??</strong></a> and <a href="#sel"><strong>??</strong></a>, logistic regression uses the same approaches to doing variable selection. In fact, the same function are used as well. Let’s use the <code>step</code> function to apply a forward and backward selection to the logistic regression model.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="categorical-data-analysis.html#cb68-1" tabindex="-1"></a>train_sel_log <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span> </span>
<span id="cb68-2"><a href="categorical-data-analysis.html#cb68-2" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Bonus, </span>
<span id="cb68-3"><a href="categorical-data-analysis.html#cb68-3" tabindex="-1"></a>         Lot_Area,</span>
<span id="cb68-4"><a href="categorical-data-analysis.html#cb68-4" tabindex="-1"></a>         Street,</span>
<span id="cb68-5"><a href="categorical-data-analysis.html#cb68-5" tabindex="-1"></a>         Bldg_Type,</span>
<span id="cb68-6"><a href="categorical-data-analysis.html#cb68-6" tabindex="-1"></a>         House_Style,</span>
<span id="cb68-7"><a href="categorical-data-analysis.html#cb68-7" tabindex="-1"></a>         Overall_Qual,</span>
<span id="cb68-8"><a href="categorical-data-analysis.html#cb68-8" tabindex="-1"></a>         Roof_Style,</span>
<span id="cb68-9"><a href="categorical-data-analysis.html#cb68-9" tabindex="-1"></a>         Central_Air,</span>
<span id="cb68-10"><a href="categorical-data-analysis.html#cb68-10" tabindex="-1"></a>         First_Flr_SF,</span>
<span id="cb68-11"><a href="categorical-data-analysis.html#cb68-11" tabindex="-1"></a>         Second_Flr_SF,</span>
<span id="cb68-12"><a href="categorical-data-analysis.html#cb68-12" tabindex="-1"></a>         Full_Bath,</span>
<span id="cb68-13"><a href="categorical-data-analysis.html#cb68-13" tabindex="-1"></a>         Half_Bath,</span>
<span id="cb68-14"><a href="categorical-data-analysis.html#cb68-14" tabindex="-1"></a>         Fireplaces,</span>
<span id="cb68-15"><a href="categorical-data-analysis.html#cb68-15" tabindex="-1"></a>         Garage_Area,</span>
<span id="cb68-16"><a href="categorical-data-analysis.html#cb68-16" tabindex="-1"></a>         Gr_Liv_Area, </span>
<span id="cb68-17"><a href="categorical-data-analysis.html#cb68-17" tabindex="-1"></a>         TotRms_AbvGrd) <span class="sc">%&gt;%</span></span>
<span id="cb68-18"><a href="categorical-data-analysis.html#cb68-18" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.numeric, <span class="sc">~</span><span class="fu">replace_na</span>(.,<span class="fu">mean</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb68-19"><a href="categorical-data-analysis.html#cb68-19" tabindex="-1"></a></span>
<span id="cb68-20"><a href="categorical-data-analysis.html#cb68-20" tabindex="-1"></a>full.model <span class="ot">&lt;-</span> <span class="fu">glm</span>(Bonus <span class="sc">~</span> . , <span class="at">data =</span> train_sel_log)</span>
<span id="cb68-21"><a href="categorical-data-analysis.html#cb68-21" tabindex="-1"></a></span>
<span id="cb68-22"><a href="categorical-data-analysis.html#cb68-22" tabindex="-1"></a>empty.model <span class="ot">&lt;-</span> <span class="fu">glm</span>(Bonus <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> train_sel_log)</span></code></pre></div>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="categorical-data-analysis.html#cb69-1" tabindex="-1"></a>for.model <span class="ot">&lt;-</span> <span class="fu">step</span>(empty.model,</span>
<span id="cb69-2"><a href="categorical-data-analysis.html#cb69-2" tabindex="-1"></a>                  <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> <span class="fu">formula</span>(empty.model),</span>
<span id="cb69-3"><a href="categorical-data-analysis.html#cb69-3" tabindex="-1"></a>                               <span class="at">upper =</span> <span class="fu">formula</span>(full.model)),</span>
<span id="cb69-4"><a href="categorical-data-analysis.html#cb69-4" tabindex="-1"></a>                  <span class="at">direction =</span> <span class="st">&quot;forward&quot;</span>, <span class="at">k =</span> <span class="fu">log</span>(<span class="fu">dim</span>(train_sel_log)[<span class="dv">1</span>]))</span></code></pre></div>
<pre><code>## Start:  AIC=2934.01
## Bonus ~ 1
## 
##                 Df Deviance    AIC
## + Overall_Qual   9   236.49 1468.2
## + Full_Bath      1   320.70 2032.0
## + Gr_Liv_Area    1   328.02 2078.3
## + Garage_Area    1   357.99 2257.6
## + First_Flr_SF   1   389.04 2428.2
## + TotRms_AbvGrd  1   418.76 2579.2
## + Fireplaces     1   420.14 2585.9
## + House_Style    7   443.36 2742.0
## + Second_Flr_SF  1   464.15 2790.2
## + Half_Bath      1   465.56 2796.4
## + Lot_Area       1   474.57 2835.8
## + Central_Air    1   478.66 2853.3
## + Bldg_Type      4   481.65 2889.0
## &lt;none&gt;               499.72 2934.0
## + Street         1   499.23 2939.6
## + Roof_Style     5   492.33 2941.6
## 
## Step:  AIC=1468.19
## Bonus ~ Overall_Qual
## 
##                 Df Deviance    AIC
## + Gr_Liv_Area    1   208.62 1218.7
## + Full_Bath      1   208.66 1219.0
## + First_Flr_SF   1   216.99 1299.4
## + Lot_Area       1   221.01 1337.0
## + TotRms_AbvGrd  1   223.58 1360.7
## + Garage_Area    1   223.59 1360.8
## + Fireplaces     1   226.17 1384.3
## + Bldg_Type      4   229.34 1435.8
## + Second_Flr_SF  1   233.32 1448.2
## + Half_Bath      1   233.65 1451.1
## + House_Style    7   229.14 1456.8
## + Central_Air    1   234.84 1461.5
## &lt;none&gt;               236.49 1468.2
## + Street         1   236.36 1474.8
## + Roof_Style     5   235.77 1500.1
## 
## Step:  AIC=1218.69
## Bonus ~ Overall_Qual + Gr_Liv_Area
## 
##                 Df Deviance    AIC
## + Full_Bath      1   199.12 1130.7
## + House_Style    7   194.95 1133.1
## + First_Flr_SF   1   201.73 1157.4
## + Second_Flr_SF  1   202.48 1165.0
## + Garage_Area    1   202.58 1166.0
## + Lot_Area       1   202.94 1169.7
## + Fireplaces     1   206.04 1200.8
## + Central_Air    1   206.28 1203.2
## + Bldg_Type      4   205.04 1213.6
## + TotRms_AbvGrd  1   207.75 1217.7
## &lt;none&gt;               208.62 1218.7
## + Street         1   208.37 1223.9
## + Half_Bath      1   208.52 1225.3
## + Roof_Style     5   207.62 1246.9
## 
## Step:  AIC=1130.68
## Bonus ~ Overall_Qual + Gr_Liv_Area + Full_Bath
## 
##                 Df Deviance    AIC
## + House_Style    7   187.42 1059.9
## + First_Flr_SF   1   192.79 1072.1
## + Lot_Area       1   193.12 1075.5
## + Second_Flr_SF  1   193.47 1079.3
## + Garage_Area    1   194.00 1084.9
## + Fireplaces     1   195.10 1096.5
## + Bldg_Type      4   193.28 1100.1
## + Central_Air    1   196.72 1113.5
## + TotRms_AbvGrd  1   197.68 1123.4
## &lt;none&gt;               199.12 1130.7
## + Street         1   198.82 1135.2
## + Half_Bath      1   198.88 1135.8
## + Roof_Style     5   198.63 1163.7
## 
## Step:  AIC=1059.91
## Bonus ~ Overall_Qual + Gr_Liv_Area + Full_Bath + House_Style
## 
##                 Df Deviance    AIC
## + Lot_Area       1   183.49 1024.0
## + Bldg_Type      4   182.21 1032.6
## + Fireplaces     1   184.58 1036.2
## + Garage_Area    1   185.09 1041.8
## + Half_Bath      1   185.51 1046.5
## + Central_Air    1   186.12 1053.3
## + TotRms_AbvGrd  1   186.68 1059.4
## &lt;none&gt;               187.42 1059.9
## + First_Flr_SF   1   186.90 1061.9
## + Street         1   187.09 1064.0
## + Second_Flr_SF  1   187.17 1064.8
## + Roof_Style     5   186.32 1086.0
## 
## Step:  AIC=1024.03
## Bonus ~ Overall_Qual + Gr_Liv_Area + Full_Bath + House_Style + 
##     Lot_Area
## 
##                 Df Deviance    AIC
## + Fireplaces     1   181.35 1007.6
## + Bldg_Type      4   179.35 1007.8
## + Half_Bath      1   181.64 1010.9
## + Garage_Area    1   181.78 1012.5
## + Central_Air    1   182.34 1018.8
## + TotRms_AbvGrd  1   182.68 1022.5
## &lt;none&gt;               183.49 1024.0
## + First_Flr_SF   1   183.27 1029.2
## + Second_Flr_SF  1   183.41 1030.8
## + Street         1   183.48 1031.6
## + Roof_Style     5   182.40 1050.0
## 
## Step:  AIC=1007.63
## Bonus ~ Overall_Qual + Gr_Liv_Area + Full_Bath + House_Style + 
##     Lot_Area + Fireplaces
## 
##                 Df Deviance     AIC
## + Garage_Area    1   179.60  995.32
## + Half_Bath      1   179.69  996.33
## + Bldg_Type      4   177.71  996.50
## + Central_Air    1   180.43 1004.85
## + TotRms_AbvGrd  1   180.65 1007.28
## &lt;none&gt;               181.35 1007.63
## + First_Flr_SF   1   181.20 1013.56
## + Second_Flr_SF  1   181.31 1014.74
## + Street         1   181.34 1015.13
## + Roof_Style     5   180.17 1032.37
## 
## Step:  AIC=995.32
## Bonus ~ Overall_Qual + Gr_Liv_Area + Full_Bath + House_Style + 
##     Lot_Area + Fireplaces + Garage_Area
## 
##                 Df Deviance     AIC
## + Half_Bath      1   178.20  986.92
## + Bldg_Type      4   176.41  989.06
## &lt;none&gt;               179.60  995.32
## + TotRms_AbvGrd  1   178.99  995.95
## + Central_Air    1   179.05  996.71
## + First_Flr_SF   1   179.51 1001.92
## + Second_Flr_SF  1   179.58 1002.72
## + Street         1   179.59 1002.90
## + Roof_Style     5   178.37 1019.38
## 
## Step:  AIC=986.92
## Bonus ~ Overall_Qual + Gr_Liv_Area + Full_Bath + House_Style + 
##     Lot_Area + Fireplaces + Garage_Area + Half_Bath
## 
##                 Df Deviance     AIC
## + Bldg_Type      4   174.89  978.99
## &lt;none&gt;               178.20  986.92
## + TotRms_AbvGrd  1   177.65  988.17
## + Central_Air    1   177.85  990.54
## + First_Flr_SF   1   178.02  992.44
## + Second_Flr_SF  1   178.12  993.63
## + Street         1   178.20  994.51
## + Roof_Style     5   177.03 1011.59
## 
## Step:  AIC=978.99
## Bonus ~ Overall_Qual + Gr_Liv_Area + Full_Bath + House_Style + 
##     Lot_Area + Fireplaces + Garage_Area + Half_Bath + Bldg_Type
## 
##                 Df Deviance     AIC
## &lt;none&gt;               174.89  978.99
## + TotRms_AbvGrd  1   174.47  981.62
## + First_Flr_SF   1   174.52  982.27
## + Second_Flr_SF  1   174.69  984.30
## + Central_Air    1   174.81  985.62
## + Street         1   174.84  986.05
## + Roof_Style     5   173.70 1003.12</code></pre>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="categorical-data-analysis.html#cb71-1" tabindex="-1"></a>back.model <span class="ot">&lt;-</span> <span class="fu">step</span>(full.model,</span>
<span id="cb71-2"><a href="categorical-data-analysis.html#cb71-2" tabindex="-1"></a>                   <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> <span class="fu">formula</span>(empty.model),</span>
<span id="cb71-3"><a href="categorical-data-analysis.html#cb71-3" tabindex="-1"></a>                                <span class="at">upper =</span> <span class="fu">formula</span>(full.model)),</span>
<span id="cb71-4"><a href="categorical-data-analysis.html#cb71-4" tabindex="-1"></a>                   <span class="at">direction =</span> <span class="st">&quot;backward&quot;</span>, <span class="at">k =</span> <span class="fu">log</span>(<span class="fu">dim</span>(train_sel_log)[<span class="dv">1</span>]))</span></code></pre></div>
<pre><code>## Start:  AIC=1028.98
## Bonus ~ Lot_Area + Street + Bldg_Type + House_Style + Overall_Qual + 
##     Roof_Style + Central_Air + First_Flr_SF + Second_Flr_SF + 
##     Full_Bath + Half_Bath + Fireplaces + Garage_Area + Gr_Liv_Area + 
##     TotRms_AbvGrd
## 
##                 Df Deviance    AIC
## - Roof_Style     5   173.78 1004.0
## - Gr_Liv_Area    1   172.68 1021.5
## - Central_Air    1   172.71 1021.9
## - Street         1   172.73 1022.1
## - Second_Flr_SF  1   172.82 1023.2
## - First_Flr_SF   1   173.01 1025.5
## - TotRms_AbvGrd  1   173.03 1025.7
## &lt;none&gt;               172.66 1029.0
## - House_Style    7   177.41 1031.2
## - Garage_Area    1   173.50 1031.2
## - Lot_Area       1   173.90 1036.0
## - Bldg_Type      4   175.97 1037.4
## - Half_Bath      1   174.09 1038.2
## - Fireplaces     1   174.10 1038.4
## - Full_Bath      1   183.82 1149.8
## - Overall_Qual   9   215.71 1416.8
## 
## Step:  AIC=1003.99
## Bonus ~ Lot_Area + Street + Bldg_Type + House_Style + Overall_Qual + 
##     Central_Air + First_Flr_SF + Second_Flr_SF + Full_Bath + 
##     Half_Bath + Fireplaces + Garage_Area + Gr_Liv_Area + TotRms_AbvGrd
## 
##                 Df Deviance     AIC
## - Gr_Liv_Area    1   173.79  996.58
## - Street         1   173.83  996.99
## - Central_Air    1   173.86  997.38
## - Second_Flr_SF  1   173.93  998.24
## - First_Flr_SF   1   174.12 1000.40
## - TotRms_AbvGrd  1   174.21 1001.50
## - House_Style    7   178.28 1003.11
## &lt;none&gt;               173.78 1003.99
## - Garage_Area    1   174.53 1005.27
## - Bldg_Type      4   177.00 1011.23
## - Lot_Area       1   175.08 1011.70
## - Fireplaces     1   175.15 1012.51
## - Half_Bath      1   175.23 1013.51
## - Full_Bath      1   185.72 1132.74
## - Overall_Qual   9   217.19 1392.75
## 
## Step:  AIC=996.58
## Bonus ~ Lot_Area + Street + Bldg_Type + House_Style + Overall_Qual + 
##     Central_Air + First_Flr_SF + Second_Flr_SF + Full_Bath + 
##     Half_Bath + Fireplaces + Garage_Area + TotRms_AbvGrd
## 
##                 Df Deviance     AIC
## - Street         1   173.85  989.59
## - Central_Air    1   173.88  989.97
## - TotRms_AbvGrd  1   174.26  994.42
## &lt;none&gt;               173.79  996.58
## - House_Style    7   178.40  996.80
## - Garage_Area    1   174.55  997.86
## - Second_Flr_SF  1   174.55  997.89
## - Bldg_Type      4   177.01 1003.66
## - Lot_Area       1   175.10 1004.27
## - Fireplaces     1   175.16 1005.08
## - Half_Bath      1   175.25 1006.08
## - First_Flr_SF   1   177.59 1033.29
## - Full_Bath      1   185.73 1125.21
## - Overall_Qual   9   217.28 1385.94
## 
## Step:  AIC=989.59
## Bonus ~ Lot_Area + Bldg_Type + House_Style + Overall_Qual + Central_Air + 
##     First_Flr_SF + Second_Flr_SF + Full_Bath + Half_Bath + Fireplaces + 
##     Garage_Area + TotRms_AbvGrd
## 
##                 Df Deviance     AIC
## - Central_Air    1   173.93  982.89
## - TotRms_AbvGrd  1   174.32  987.55
## &lt;none&gt;               173.85  989.59
## - House_Style    7   178.45  989.78
## - Second_Flr_SF  1   174.59  990.77
## - Garage_Area    1   174.63  991.15
## - Bldg_Type      4   177.01  996.11
## - Fireplaces     1   175.22  998.09
## - Half_Bath      1   175.31  999.09
## - Lot_Area       1   175.38  999.93
## - First_Flr_SF   1   177.60 1025.76
## - Full_Bath      1   185.75 1117.81
## - Overall_Qual   9   217.39 1379.42
## 
## Step:  AIC=982.89
## Bonus ~ Lot_Area + Bldg_Type + House_Style + Overall_Qual + First_Flr_SF + 
##     Second_Flr_SF + Full_Bath + Half_Bath + Fireplaces + Garage_Area + 
##     TotRms_AbvGrd
## 
##                 Df Deviance     AIC
## - TotRms_AbvGrd  1   174.41  980.93
## &lt;none&gt;               173.93  982.89
## - House_Style    7   178.57  983.56
## - Second_Flr_SF  1   174.66  983.96
## - Garage_Area    1   174.80  985.55
## - Fireplaces     1   175.33  991.77
## - Bldg_Type      4   177.30  991.85
## - Lot_Area       1   175.48  993.54
## - Half_Bath      1   175.49  993.60
## - First_Flr_SF   1   177.66 1018.82
## - Full_Bath      1   185.99 1112.84
## - Overall_Qual   9   217.41 1371.92
## 
## Step:  AIC=980.93
## Bonus ~ Lot_Area + Bldg_Type + House_Style + Overall_Qual + First_Flr_SF + 
##     Second_Flr_SF + Full_Bath + Half_Bath + Fireplaces + Garage_Area
## 
##                 Df Deviance     AIC
## - Second_Flr_SF  1   174.84  978.44
## &lt;none&gt;               174.41  980.93
## - House_Style    7   179.11  982.16
## - Garage_Area    1   175.35  984.33
## - Fireplaces     1   175.81  989.79
## - Bldg_Type      4   177.90  991.08
## - Half_Bath      1   176.01  992.06
## - Lot_Area       1   176.04  992.41
## - First_Flr_SF   1   177.80 1012.82
## - Full_Bath      1   186.17 1107.15
## - Overall_Qual   9   218.40 1373.68
## 
## Step:  AIC=978.44
## Bonus ~ Lot_Area + Bldg_Type + House_Style + Overall_Qual + First_Flr_SF + 
##     Full_Bath + Half_Bath + Fireplaces + Garage_Area
## 
##                Df Deviance     AIC
## - House_Style   7   179.16  975.13
## &lt;none&gt;              174.84  978.44
## - Garage_Area   1   175.84  982.42
## - Fireplaces    1   176.50  990.21
## - Lot_Area      1   176.51  990.26
## - Bldg_Type     4   178.55  990.93
## - Half_Bath     1   176.88  994.52
## - First_Flr_SF  1   177.98 1007.28
## - Full_Bath     1   189.54 1136.37
## - Overall_Qual  9   218.94 1371.07
## 
## Step:  AIC=975.13
## Bonus ~ Lot_Area + Bldg_Type + Overall_Qual + First_Flr_SF + 
##     Full_Bath + Half_Bath + Fireplaces + Garage_Area
## 
##                Df Deviance     AIC
## &lt;none&gt;              179.16  975.13
## - Garage_Area   1   180.54  983.22
## - Fireplaces    1   180.54  983.25
## - Bldg_Type     4   182.71  984.80
## - Lot_Area      1   180.78  985.91
## - Half_Bath     1   183.35 1014.88
## - First_Flr_SF  1   183.82 1020.09
## - Full_Bath     1   198.19 1174.50
## - Overall_Qual  9   225.96 1382.45</code></pre>
<p>In the above two approaches we used the BIC selection criteria. Here both forward and backward selection actually picked the same model. Let’s check the concordance of this model.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="categorical-data-analysis.html#cb73-1" tabindex="-1"></a>survival<span class="sc">::</span><span class="fu">concordance</span>(back.model)</span></code></pre></div>
<pre><code>## Call:
## concordance.lm(object = back.model)
## 
## n= 2051 
## Concordance= 0.9608 se= 0.003626
## concordant discordant     tied.x     tied.y    tied.xy 
##     984770      40147          1    1077327         30</code></pre>
<p>Not surprisingly, this model outperforms the previous model that we had with a concordance of 96.1%.</p>
<p>Although not covered in detail here, regularized regression can also be applied to logistic regression to get a different view. This might be helpful with the multicollinearity present in these predictor variables. Again, we can use the <code>glmnet</code> function with the addition of a <code>family = "binomial"</code> option.</p>
</div>
<div id="python-code-36" class="section level3 hasAnchor" number="7.4.6">
<h3><span class="header-section-number">7.4.6</span> Python Code<a href="categorical-data-analysis.html#python-code-36" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><em>Linear Probability Model</em></p>
<div class="sourceCode" id="cb75"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb75-1"><a href="categorical-data-analysis.html#cb75-1" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb75-2"><a href="categorical-data-analysis.html#cb75-2" tabindex="-1"></a></span>
<span id="cb75-3"><a href="categorical-data-analysis.html#cb75-3" tabindex="-1"></a>lp_model <span class="op">=</span> smf.ols(<span class="st">&quot;Bonus ~ Gr_Liv_Area&quot;</span>, data <span class="op">=</span> train).fit()</span>
<span id="cb75-4"><a href="categorical-data-analysis.html#cb75-4" tabindex="-1"></a>lp_model.summary()</span></code></pre></div>
<table class="simpletable">
<caption>OLS Regression Results</caption>
<tr>
  <th>Dep. Variable:</th>          <td>Bonus</td>      <th>  R-squared:         </th> <td>   0.328</td> 
</tr>
<tr>
  <th>Model:</th>                   <td>OLS</td>       <th>  Adj. R-squared:    </th> <td>   0.327</td> 
</tr>
<tr>
  <th>Method:</th>             <td>Least Squares</td>  <th>  F-statistic:       </th> <td>   998.6</td> 
</tr>
<tr>
  <th>Date:</th>             <td>Tue, 22 Jul 2025</td> <th>  Prob (F-statistic):</th> <td>7.04e-179</td>
</tr>
<tr>
  <th>Time:</th>                 <td>08:47:49</td>     <th>  Log-Likelihood:    </th> <td> -1063.1</td> 
</tr>
<tr>
  <th>No. Observations:</th>      <td>  2051</td>      <th>  AIC:               </th> <td>   2130.</td> 
</tr>
<tr>
  <th>Df Residuals:</th>          <td>  2049</td>      <th>  BIC:               </th> <td>   2142.</td> 
</tr>
<tr>
  <th>Df Model:</th>              <td>     1</td>      <th>                     </th>     <td> </td>    
</tr>
<tr>
  <th>Covariance Type:</th>      <td>nonrobust</td>    <th>                     </th>     <td> </td>    
</tr>
</table>
<table class="simpletable">
<tr>
       <td></td>          <th>coef</th>     <th>std err</th>      <th>t</th>      <th>P>|t|</th>  <th>[0.025</th>    <th>0.975]</th>  
</tr>
<tr>
  <th>Intercept</th>   <td>   -0.4056</td> <td>    0.028</td> <td>  -14.471</td> <td> 0.000</td> <td>   -0.461</td> <td>   -0.351</td>
</tr>
<tr>
  <th>Gr_Liv_Area</th> <td>    0.0006</td> <td> 1.76e-05</td> <td>   31.601</td> <td> 0.000</td> <td>    0.001</td> <td>    0.001</td>
</tr>
</table>
<table class="simpletable">
<tr>
  <th>Omnibus:</th>       <td> 0.074</td> <th>  Durbin-Watson:     </th> <td>   2.088</td>
</tr>
<tr>
  <th>Prob(Omnibus):</th> <td> 0.964</td> <th>  Jarque-Bera (JB):  </th> <td>   0.093</td>
</tr>
<tr>
  <th>Skew:</th>          <td> 0.014</td> <th>  Prob(JB):          </th> <td>   0.955</td>
</tr>
<tr>
  <th>Kurtosis:</th>      <td> 2.983</td> <th>  Cond. No.          </th> <td>4.96e+03</td>
</tr>
</table><br/><br/>Notes:<br/>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.<br/>[2] The condition number is large, 4.96e+03. This might indicate that there are<br/>strong multicollinearity or other numerical problems.
<div class="sourceCode" id="cb76"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb76-1"><a href="categorical-data-analysis.html#cb76-1" tabindex="-1"></a>sm.api.qqplot(lp_model.resid)</span>
<span id="cb76-2"><a href="categorical-data-analysis.html#cb76-2" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<div class="sourceCode" id="cb77"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb77-1"><a href="categorical-data-analysis.html#cb77-1" tabindex="-1"></a>train[<span class="st">&#39;pred_lp&#39;</span>] <span class="op">=</span> lp_model.predict()</span>
<span id="cb77-2"><a href="categorical-data-analysis.html#cb77-2" tabindex="-1"></a>train[<span class="st">&#39;resid_lp&#39;</span>] <span class="op">=</span> lp_model.resid</span>
<span id="cb77-3"><a href="categorical-data-analysis.html#cb77-3" tabindex="-1"></a></span>
<span id="cb77-4"><a href="categorical-data-analysis.html#cb77-4" tabindex="-1"></a>train[[<span class="st">&#39;Bonus&#39;</span>, <span class="st">&#39;pred_lp&#39;</span>, <span class="st">&#39;resid_lp&#39;</span>]].head(n <span class="op">=</span> <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##       Bonus   pred_lp  resid_lp
## 2278      0  0.727900 -0.727900
## 1379      0  0.098187 -0.098187
## 2182      0  0.191808 -0.191808
## 1436      1  0.515023  0.484977
## 1599      0  0.202954 -0.202954
## 452       1  0.322209  0.677791
## 585       1  1.065604 -0.065604
## 1078      0  0.500534 -0.500534
## 2452      1  1.002075 -0.002075
## 1658      0  0.565735 -0.565735</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb79-1"><a href="categorical-data-analysis.html#cb79-1" tabindex="-1"></a>plt.cla()</span>
<span id="cb79-2"><a href="categorical-data-analysis.html#cb79-2" tabindex="-1"></a>ax <span class="op">=</span> sns.relplot(data <span class="op">=</span> train, y <span class="op">=</span> <span class="st">&quot;resid_lp&quot;</span>, x <span class="op">=</span> <span class="st">&quot;pred_lp&quot;</span>)</span>
<span id="cb79-3"><a href="categorical-data-analysis.html#cb79-3" tabindex="-1"></a>ax.<span class="bu">set</span>(ylabel <span class="op">=</span> <span class="st">&#39;Residuals&#39;</span>,</span>
<span id="cb79-4"><a href="categorical-data-analysis.html#cb79-4" tabindex="-1"></a>       xlabel <span class="op">=</span> <span class="st">&#39;Predicted Probability of Bonus&#39;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-42-3.png" width="245" /></p>
<div class="sourceCode" id="cb80"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb80-1"><a href="categorical-data-analysis.html#cb80-1" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-42-4.png" width="480" /><img src="bookdownproj_files/figure-html/unnamed-chunk-42-5.png" width="672" /></p>
<p><em>Binary Logistic Regression</em></p>
<div class="sourceCode" id="cb81"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb81-1"><a href="categorical-data-analysis.html#cb81-1" tabindex="-1"></a>log_model <span class="op">=</span> smf.logit(<span class="st">&quot;Bonus ~ Gr_Liv_Area&quot;</span>, data <span class="op">=</span> train).fit()</span></code></pre></div>
<pre><code>## Optimization terminated successfully.
##          Current function value: 0.466728
##          Iterations 7</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb83-1"><a href="categorical-data-analysis.html#cb83-1" tabindex="-1"></a>log_model.summary()</span></code></pre></div>
<table class="simpletable">
<caption>Logit Regression Results</caption>
<tr>
  <th>Dep. Variable:</th>         <td>Bonus</td>      <th>  No. Observations:  </th>   <td>  2051</td>  
</tr>
<tr>
  <th>Model:</th>                 <td>Logit</td>      <th>  Df Residuals:      </th>   <td>  2049</td>  
</tr>
<tr>
  <th>Method:</th>                 <td>MLE</td>       <th>  Df Model:          </th>   <td>     1</td>  
</tr>
<tr>
  <th>Date:</th>            <td>Tue, 22 Jul 2025</td> <th>  Pseudo R-squ.:     </th>   <td>0.3179</td>  
</tr>
<tr>
  <th>Time:</th>                <td>08:47:51</td>     <th>  Log-Likelihood:    </th>  <td> -957.26</td> 
</tr>
<tr>
  <th>converged:</th>             <td>True</td>       <th>  LL-Null:           </th>  <td> -1403.4</td> 
</tr>
<tr>
  <th>Covariance Type:</th>     <td>nonrobust</td>    <th>  LLR p-value:       </th> <td>4.571e-196</td>
</tr>
</table>
<table class="simpletable">
<tr>
       <td></td>          <th>coef</th>     <th>std err</th>      <th>z</th>      <th>P>|z|</th>  <th>[0.025</th>    <th>0.975]</th>  
</tr>
<tr>
  <th>Intercept</th>   <td>   -6.3503</td> <td>    0.286</td> <td>  -22.231</td> <td> 0.000</td> <td>   -6.910</td> <td>   -5.790</td>
</tr>
<tr>
  <th>Gr_Liv_Area</th> <td>    0.0041</td> <td>    0.000</td> <td>   21.645</td> <td> 0.000</td> <td>    0.004</td> <td>    0.004</td>
</tr>
</table>
<div class="sourceCode" id="cb84"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb84-1"><a href="categorical-data-analysis.html#cb84-1" tabindex="-1"></a>odds_ratio <span class="op">=</span> <span class="dv">100</span><span class="op">*</span>(np.exp(log_model.params) <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb84-2"><a href="categorical-data-analysis.html#cb84-2" tabindex="-1"></a></span>
<span id="cb84-3"><a href="categorical-data-analysis.html#cb84-3" tabindex="-1"></a><span class="bu">print</span>(odds_ratio)</span></code></pre></div>
<pre><code>## Intercept     -99.825386
## Gr_Liv_Area     0.405848
## dtype: float64</code></pre>
<p><em>Adding Categorical Variables</em></p>
<div class="sourceCode" id="cb86"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb86-1"><a href="categorical-data-analysis.html#cb86-1" tabindex="-1"></a>log_model2 <span class="op">=</span> smf.logit(<span class="st">&quot;Bonus ~ Gr_Liv_Area + C(Central_Air) + C(Fireplaces)&quot;</span>, data <span class="op">=</span> train).fit()</span></code></pre></div>
<pre><code>## Warning: Maximum number of iterations has been exceeded.
##          Current function value: 0.421157
##          Iterations: 35
## C:\PROGRA~3\ANACON~1\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb88-1"><a href="categorical-data-analysis.html#cb88-1" tabindex="-1"></a>log_model2.summary()</span></code></pre></div>
<table class="simpletable">
<caption>Logit Regression Results</caption>
<tr>
  <th>Dep. Variable:</th>         <td>Bonus</td>      <th>  No. Observations:  </th>   <td>  2051</td>  
</tr>
<tr>
  <th>Model:</th>                 <td>Logit</td>      <th>  Df Residuals:      </th>   <td>  2044</td>  
</tr>
<tr>
  <th>Method:</th>                 <td>MLE</td>       <th>  Df Model:          </th>   <td>     6</td>  
</tr>
<tr>
  <th>Date:</th>            <td>Tue, 22 Jul 2025</td> <th>  Pseudo R-squ.:     </th>   <td>0.3845</td>  
</tr>
<tr>
  <th>Time:</th>                <td>08:47:51</td>     <th>  Log-Likelihood:    </th>  <td> -863.79</td> 
</tr>
<tr>
  <th>converged:</th>             <td>False</td>      <th>  LL-Null:           </th>  <td> -1403.4</td> 
</tr>
<tr>
  <th>Covariance Type:</th>     <td>nonrobust</td>    <th>  LLR p-value:       </th> <td>6.407e-230</td>
</tr>
</table>
<table class="simpletable">
<tr>
           <td></td>              <th>coef</th>     <th>std err</th>      <th>z</th>      <th>P>|z|</th>  <th>[0.025</th>    <th>0.975]</th>  
</tr>
<tr>
  <th>Intercept</th>           <td>  -10.1177</td> <td>    0.667</td> <td>  -15.176</td> <td> 0.000</td> <td>  -11.424</td> <td>   -8.811</td>
</tr>
<tr>
  <th>C(Central_Air)[T.Y]</th> <td>    3.4809</td> <td>    0.536</td> <td>    6.495</td> <td> 0.000</td> <td>    2.430</td> <td>    4.531</td>
</tr>
<tr>
  <th>C(Fireplaces)[T.1]</th>  <td>    1.1059</td> <td>    0.126</td> <td>    8.766</td> <td> 0.000</td> <td>    0.859</td> <td>    1.353</td>
</tr>
<tr>
  <th>C(Fireplaces)[T.2]</th>  <td>    0.6891</td> <td>    0.235</td> <td>    2.930</td> <td> 0.003</td> <td>    0.228</td> <td>    1.150</td>
</tr>
<tr>
  <th>C(Fireplaces)[T.3]</th>  <td>   -0.4379</td> <td>    0.964</td> <td>   -0.454</td> <td> 0.650</td> <td>   -2.328</td> <td>    1.452</td>
</tr>
<tr>
  <th>C(Fireplaces)[T.4]</th>  <td>   17.4289</td> <td> 3.95e+04</td> <td>    0.000</td> <td> 1.000</td> <td>-7.73e+04</td> <td> 7.73e+04</td>
</tr>
<tr>
  <th>Gr_Liv_Area</th>         <td>    0.0039</td> <td>    0.000</td> <td>   18.786</td> <td> 0.000</td> <td>    0.004</td> <td>    0.004</td>
</tr>
</table>
<div class="sourceCode" id="cb89"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb89-1"><a href="categorical-data-analysis.html#cb89-1" tabindex="-1"></a>odds_ratio <span class="op">=</span> <span class="dv">100</span><span class="op">*</span>(np.exp(log_model2.params) <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb89-2"><a href="categorical-data-analysis.html#cb89-2" tabindex="-1"></a></span>
<span id="cb89-3"><a href="categorical-data-analysis.html#cb89-3" tabindex="-1"></a><span class="bu">print</span>(odds_ratio)</span></code></pre></div>
<pre><code>## Intercept             -9.999596e+01
## C(Central_Air)[T.Y]    3.149026e+03
## C(Fireplaces)[T.1]     2.021892e+02
## C(Fireplaces)[T.2]     9.919188e+01
## C(Fireplaces)[T.3]    -3.545996e+01
## C(Fireplaces)[T.4]     3.709002e+09
## Gr_Liv_Area            3.928177e-01
## dtype: float64</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb91-1"><a href="categorical-data-analysis.html#cb91-1" tabindex="-1"></a>odds_ratio <span class="op">=</span> (np.exp(log_model2.params))</span>
<span id="cb91-2"><a href="categorical-data-analysis.html#cb91-2" tabindex="-1"></a></span>
<span id="cb91-3"><a href="categorical-data-analysis.html#cb91-3" tabindex="-1"></a><span class="bu">print</span>(odds_ratio)</span></code></pre></div>
<pre><code>## Intercept              4.035898e-05
## C(Central_Air)[T.Y]    3.249026e+01
## C(Fireplaces)[T.1]     3.021892e+00
## C(Fireplaces)[T.2]     1.991919e+00
## C(Fireplaces)[T.3]     6.454004e-01
## C(Fireplaces)[T.4]     3.709002e+07
## Gr_Liv_Area            1.003928e+00
## dtype: float64</code></pre>
<p><em>Model Assessment</em></p>
<p>Python doesn’t have concordant / discordant pair calculations. We will learn in Fall semester other metrics to evaluate a logistic regression model that Python does have.</p>
<p><em>Variable Selection and Regularized Regression</em></p>
<p>Python does NOT have nice capabilities to do variable selection automatically in statsmodels, scikitlearn, or scipy. All resources I can find involve downloading and installing a package (mlxtend) that is not included by default in anaconda or writing your own function. Scikit learn has something similar but uses the model’s coefficients (!!!) to select, not p-values. Scikit learn can do this by evaluating a metric on cross-validation, but that is not covered until machine learning in Fall 3.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="model-building-and-scoring-for-prediction.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/IAA-Faculty/statistical_foundations.git/edit/master/07-categorical.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": "https://github.com/IAA-Faculty/statistical_foundations.git/blob/master/07-categorical.Rmd",
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "toc": null
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
