<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 Introduction to Statistics | Statistical Foundations</title>
  <meta name="description" content="Chapter 1 Introduction to Statistics | Statistical Foundations" />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 Introduction to Statistics | Statistical Foundations" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="IAA-Faculty/statistical_foundations" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 Introduction to Statistics | Statistical Foundations" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="slr.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a style="font-weight:bold, text-align:center" href="https://github.com/IAA-Faculty/statistical_foundations/">Statistical Foundations</a>
<img src="./img/iaaicon.png" alt="IAA"  class="center"</li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#authors"><i class="fa fa-check"></i>Authors</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#structure-of-the-book"><i class="fa fa-check"></i>Structure of the book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro-stat.html"><a href="intro-stat.html"><i class="fa fa-check"></i><b>1</b> Introduction to Statistics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro-stat.html"><a href="intro-stat.html#eda"><i class="fa fa-check"></i><b>1.1</b> Exploratory Data Analysis (EDA)</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="intro-stat.html"><a href="intro-stat.html#vartypes"><i class="fa fa-check"></i><b>1.1.1</b> Types of Variables</a></li>
<li class="chapter" data-level="1.1.2" data-path="intro-stat.html"><a href="intro-stat.html#distributions"><i class="fa fa-check"></i><b>1.1.2</b> Distributions</a></li>
<li class="chapter" data-level="1.1.3" data-path="intro-stat.html"><a href="intro-stat.html#normal"><i class="fa fa-check"></i><b>1.1.3</b> The Normal Distribution</a></li>
<li class="chapter" data-level="1.1.4" data-path="intro-stat.html"><a href="intro-stat.html#skew"><i class="fa fa-check"></i><b>1.1.4</b> Skewness</a></li>
<li class="chapter" data-level="1.1.5" data-path="intro-stat.html"><a href="intro-stat.html#kurt"><i class="fa fa-check"></i><b>1.1.5</b> Kurtosis</a></li>
<li class="chapter" data-level="1.1.6" data-path="intro-stat.html"><a href="intro-stat.html#graphdist"><i class="fa fa-check"></i><b>1.1.6</b> Graphical Displays of Distributions</a></li>
<li class="chapter" data-level="1.1.7" data-path="intro-stat.html"><a href="intro-stat.html#python-code"><i class="fa fa-check"></i><b>1.1.7</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="intro-stat.html"><a href="intro-stat.html#pointest"><i class="fa fa-check"></i><b>1.2</b> Point Estimates</a></li>
<li class="chapter" data-level="1.3" data-path="intro-stat.html"><a href="intro-stat.html#ci"><i class="fa fa-check"></i><b>1.3</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="intro-stat.html"><a href="intro-stat.html#python-code-1"><i class="fa fa-check"></i><b>1.3.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="intro-stat.html"><a href="intro-stat.html#hypotest"><i class="fa fa-check"></i><b>1.4</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="intro-stat.html"><a href="intro-stat.html#onesample"><i class="fa fa-check"></i><b>1.4.1</b> One-Sample T-Test</a></li>
<li class="chapter" data-level="1.4.2" data-path="intro-stat.html"><a href="intro-stat.html#python-code-2"><i class="fa fa-check"></i><b>1.4.2</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="intro-stat.html"><a href="intro-stat.html#two-sample-t-tests"><i class="fa fa-check"></i><b>1.5</b> Two-Sample t-tests</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="intro-stat.html"><a href="intro-stat.html#testnorm"><i class="fa fa-check"></i><b>1.5.1</b> Testing Normality of Groups</a></li>
<li class="chapter" data-level="1.5.2" data-path="intro-stat.html"><a href="intro-stat.html#ftest"><i class="fa fa-check"></i><b>1.5.2</b> Testing Equality of Variances</a></li>
<li class="chapter" data-level="1.5.3" data-path="intro-stat.html"><a href="intro-stat.html#tsttest"><i class="fa fa-check"></i><b>1.5.3</b> Testing Equality of Means</a></li>
<li class="chapter" data-level="1.5.4" data-path="intro-stat.html"><a href="intro-stat.html#python-code-3"><i class="fa fa-check"></i><b>1.5.4</b> Python Code</a></li>
<li class="chapter" data-level="1.5.5" data-path="intro-stat.html"><a href="intro-stat.html#wilcoxon"><i class="fa fa-check"></i><b>1.5.5</b> Mann-Whitney-Wilcoxon Test</a></li>
<li class="chapter" data-level="1.5.6" data-path="intro-stat.html"><a href="intro-stat.html#python-code-4"><i class="fa fa-check"></i><b>1.5.6</b> Python Code</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="slr.html"><a href="slr.html"><i class="fa fa-check"></i><b>2</b> Introduction to ANOVA and Linear Regression</a>
<ul>
<li class="chapter" data-level="2.1" data-path="slr.html"><a href="slr.html#evp"><i class="fa fa-check"></i><b>2.1</b> Predictive vs. Explanatory</a></li>
<li class="chapter" data-level="2.2" data-path="slr.html"><a href="slr.html#trainvalidtest"><i class="fa fa-check"></i><b>2.2</b> Honest Assessment</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="slr.html"><a href="slr.html#python-code-5"><i class="fa fa-check"></i><b>2.2.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="slr.html"><a href="slr.html#bivariate-eda"><i class="fa fa-check"></i><b>2.3</b> Bivariate EDA</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="slr.html"><a href="slr.html#continuous-continuous-associations"><i class="fa fa-check"></i><b>2.3.1</b> Continuous-Continuous Associations</a></li>
<li class="chapter" data-level="2.3.2" data-path="slr.html"><a href="slr.html#continuous-categorical-associations"><i class="fa fa-check"></i><b>2.3.2</b> Continuous-Categorical Associations</a></li>
<li class="chapter" data-level="2.3.3" data-path="slr.html"><a href="slr.html#python-code-6"><i class="fa fa-check"></i><b>2.3.3</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="slr.html"><a href="slr.html#oneway"><i class="fa fa-check"></i><b>2.4</b> One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="slr.html"><a href="slr.html#python-code-7"><i class="fa fa-check"></i><b>2.4.1</b> Python Code</a></li>
<li class="chapter" data-level="2.4.2" data-path="slr.html"><a href="slr.html#testing-assumptions"><i class="fa fa-check"></i><b>2.4.2</b> Testing Assumptions</a></li>
<li class="chapter" data-level="2.4.3" data-path="slr.html"><a href="slr.html#python-code-8"><i class="fa fa-check"></i><b>2.4.3</b> Python Code</a></li>
<li class="chapter" data-level="2.4.4" data-path="slr.html"><a href="slr.html#kruskal"><i class="fa fa-check"></i><b>2.4.4</b> Kruskal-Wallis</a></li>
<li class="chapter" data-level="2.4.5" data-path="slr.html"><a href="slr.html#python-code-9"><i class="fa fa-check"></i><b>2.4.5</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="slr.html"><a href="slr.html#posthoc"><i class="fa fa-check"></i><b>2.5</b> ANOVA Post-hoc Testing</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="slr.html"><a href="slr.html#tukey"><i class="fa fa-check"></i><b>2.5.1</b> Tukey-Kramer</a></li>
<li class="chapter" data-level="2.5.2" data-path="slr.html"><a href="slr.html#dunnett"><i class="fa fa-check"></i><b>2.5.2</b> Dunnett’s Test</a></li>
<li class="chapter" data-level="2.5.3" data-path="slr.html"><a href="slr.html#python-code-10"><i class="fa fa-check"></i><b>2.5.3</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="slr.html"><a href="slr.html#cor"><i class="fa fa-check"></i><b>2.6</b> Pearson Correlation</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="slr.html"><a href="slr.html#testcor"><i class="fa fa-check"></i><b>2.6.1</b> Statistical Test</a></li>
<li class="chapter" data-level="2.6.2" data-path="slr.html"><a href="slr.html#effect-of-anomalous-observations"><i class="fa fa-check"></i><b>2.6.2</b> Effect of Anomalous Observations</a></li>
<li class="chapter" data-level="2.6.3" data-path="slr.html"><a href="slr.html#the-correlation-matrix"><i class="fa fa-check"></i><b>2.6.3</b> The Correlation Matrix</a></li>
<li class="chapter" data-level="2.6.4" data-path="slr.html"><a href="slr.html#python-code-11"><i class="fa fa-check"></i><b>2.6.4</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="slr.html"><a href="slr.html#simple-linear-regression"><i class="fa fa-check"></i><b>2.7</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="slr.html"><a href="slr.html#slrassumptions"><i class="fa fa-check"></i><b>2.7.1</b> Assumptions of Linear Regression</a></li>
<li class="chapter" data-level="2.7.2" data-path="slr.html"><a href="slr.html#testing-for-association"><i class="fa fa-check"></i><b>2.7.2</b> Testing for Association</a></li>
<li class="chapter" data-level="2.7.3" data-path="slr.html"><a href="slr.html#python-code-12"><i class="fa fa-check"></i><b>2.7.3</b> Python Code</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mlr.html"><a href="mlr.html"><i class="fa fa-check"></i><b>3</b> Complex ANOVA and Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="mlr.html"><a href="mlr.html#two-way-anova"><i class="fa fa-check"></i><b>3.1</b> Two-Way ANOVA</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="mlr.html"><a href="mlr.html#exploration"><i class="fa fa-check"></i><b>3.1.1</b> Exploration</a></li>
<li class="chapter" data-level="3.1.2" data-path="mlr.html"><a href="mlr.html#model"><i class="fa fa-check"></i><b>3.1.2</b> Model</a></li>
<li class="chapter" data-level="3.1.3" data-path="mlr.html"><a href="mlr.html#post-hoc-testing"><i class="fa fa-check"></i><b>3.1.3</b> Post-Hoc Testing</a></li>
<li class="chapter" data-level="3.1.4" data-path="mlr.html"><a href="mlr.html#python-code-13"><i class="fa fa-check"></i><b>3.1.4</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="mlr.html"><a href="mlr.html#two-way-anova-with-interactions"><i class="fa fa-check"></i><b>3.2</b> Two-Way ANOVA with Interactions</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="mlr.html"><a href="mlr.html#post-hoc-testing-1"><i class="fa fa-check"></i><b>3.2.1</b> Post-Hoc Testing</a></li>
<li class="chapter" data-level="3.2.2" data-path="mlr.html"><a href="mlr.html#assumptions"><i class="fa fa-check"></i><b>3.2.2</b> Assumptions</a></li>
<li class="chapter" data-level="3.2.3" data-path="mlr.html"><a href="mlr.html#python-code-14"><i class="fa fa-check"></i><b>3.2.3</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="mlr.html"><a href="mlr.html#randomized-block-design"><i class="fa fa-check"></i><b>3.3</b> Randomized Block Design</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="mlr.html"><a href="mlr.html#garlic-bulb-weight-example"><i class="fa fa-check"></i><b>3.3.1</b> Garlic Bulb Weight Example</a></li>
<li class="chapter" data-level="3.3.2" data-path="mlr.html"><a href="mlr.html#assumptions-1"><i class="fa fa-check"></i><b>3.3.2</b> Assumptions</a></li>
<li class="chapter" data-level="3.3.3" data-path="mlr.html"><a href="mlr.html#python-code-15"><i class="fa fa-check"></i><b>3.3.3</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="mlr.html"><a href="mlr.html#multiple-linear-regression"><i class="fa fa-check"></i><b>3.4</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="mlr.html"><a href="mlr.html#model-structure"><i class="fa fa-check"></i><b>3.4.1</b> Model Structure</a></li>
<li class="chapter" data-level="3.4.2" data-path="mlr.html"><a href="mlr.html#global-local-inference"><i class="fa fa-check"></i><b>3.4.2</b> Global &amp; Local Inference</a></li>
<li class="chapter" data-level="3.4.3" data-path="mlr.html"><a href="mlr.html#assumptions-2"><i class="fa fa-check"></i><b>3.4.3</b> Assumptions</a></li>
<li class="chapter" data-level="3.4.4" data-path="mlr.html"><a href="mlr.html#multiple-coefficients-of-determination"><i class="fa fa-check"></i><b>3.4.4</b> Multiple Coefficients of Determination</a></li>
<li class="chapter" data-level="3.4.5" data-path="mlr.html"><a href="mlr.html#categorical-predictor-variables"><i class="fa fa-check"></i><b>3.4.5</b> Categorical Predictor Variables</a></li>
<li class="chapter" data-level="3.4.6" data-path="mlr.html"><a href="mlr.html#python-code-16"><i class="fa fa-check"></i><b>3.4.6</b> Python Code</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="model-selection.html"><a href="model-selection.html"><i class="fa fa-check"></i><b>4</b> Model Selection</a>
<ul>
<li class="chapter" data-level="4.1" data-path="model-selection.html"><a href="model-selection.html#selection-criteria"><i class="fa fa-check"></i><b>4.1</b> Selection Criteria</a></li>
<li class="chapter" data-level="4.2" data-path="model-selection.html"><a href="model-selection.html#stepwise-selection"><i class="fa fa-check"></i><b>4.2</b> Stepwise Selection</a>
<ul>
<li class="chapter" data-level="" data-path="model-selection.html"><a href="model-selection.html#forward"><i class="fa fa-check"></i>Forward</a></li>
<li class="chapter" data-level="" data-path="model-selection.html"><a href="model-selection.html#backward"><i class="fa fa-check"></i>Backward</a></li>
<li class="chapter" data-level="" data-path="model-selection.html"><a href="model-selection.html#stepwise"><i class="fa fa-check"></i>Stepwise</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="model-selection.html"><a href="model-selection.html#significance-levels"><i class="fa fa-check"></i><b>4.3</b> Significance Levels</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="model-selection.html"><a href="model-selection.html#python-code-17"><i class="fa fa-check"></i><b>4.3.1</b> Python Code</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="diag.html"><a href="diag.html"><i class="fa fa-check"></i><b>5</b> Diagnostics</a>
<ul>
<li class="chapter" data-level="5.0.1" data-path="diag.html"><a href="diag.html#python-code-18"><i class="fa fa-check"></i><b>5.0.1</b> Python Code</a></li>
<li class="chapter" data-level="5.1" data-path="diag.html"><a href="diag.html#examining-residuals"><i class="fa fa-check"></i><b>5.1</b> Examining Residuals</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="diag.html"><a href="diag.html#python-code-19"><i class="fa fa-check"></i><b>5.1.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="diag.html"><a href="diag.html#misspecified-model"><i class="fa fa-check"></i><b>5.2</b> Misspecified Model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="diag.html"><a href="diag.html#python-code-20"><i class="fa fa-check"></i><b>5.2.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="diag.html"><a href="diag.html#constant-variance"><i class="fa fa-check"></i><b>5.3</b> Constant Variance</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="diag.html"><a href="diag.html#python-code-21"><i class="fa fa-check"></i><b>5.3.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="diag.html"><a href="diag.html#normality"><i class="fa fa-check"></i><b>5.4</b> Normality</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="diag.html"><a href="diag.html#python-code-22"><i class="fa fa-check"></i><b>5.4.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="diag.html"><a href="diag.html#correlated-errors"><i class="fa fa-check"></i><b>5.5</b> Correlated Errors</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="diag.html"><a href="diag.html#python-code-23"><i class="fa fa-check"></i><b>5.5.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="diag.html"><a href="diag.html#influential-observations-and-outliers"><i class="fa fa-check"></i><b>5.6</b> Influential Observations and Outliers</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="diag.html"><a href="diag.html#python-code-24"><i class="fa fa-check"></i><b>5.6.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="diag.html"><a href="diag.html#multicollinearity"><i class="fa fa-check"></i><b>5.7</b> Multicollinearity</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="diag.html"><a href="diag.html#python-code-25"><i class="fa fa-check"></i><b>5.7.1</b> Python Code</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html"><i class="fa fa-check"></i><b>6</b> Model Building and Scoring for Prediction</a>
<ul>
<li class="chapter" data-level="6.1" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#regularized-regression"><i class="fa fa-check"></i><b>6.1</b> Regularized Regression</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#penalties-in-models"><i class="fa fa-check"></i><b>6.1.1</b> Penalties in Models</a></li>
<li class="chapter" data-level="6.1.2" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#ridge-regression"><i class="fa fa-check"></i><b>6.1.2</b> Ridge Regression</a></li>
<li class="chapter" data-level="6.1.3" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#lasso"><i class="fa fa-check"></i><b>6.1.3</b> LASSO</a></li>
<li class="chapter" data-level="6.1.4" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#elastic-net"><i class="fa fa-check"></i><b>6.1.4</b> Elastic Net</a></li>
<li class="chapter" data-level="6.1.5" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#python-code-26"><i class="fa fa-check"></i><b>6.1.5</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#optimizing-penalties"><i class="fa fa-check"></i><b>6.2</b> Optimizing Penalties</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#cross-validation"><i class="fa fa-check"></i><b>6.2.1</b> Cross-Validation</a></li>
<li class="chapter" data-level="6.2.2" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#cv-in-regularized-regression"><i class="fa fa-check"></i><b>6.2.2</b> CV in Regularized Regression</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#model-comparisons"><i class="fa fa-check"></i><b>6.3</b> Model Comparisons</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#model-metrics"><i class="fa fa-check"></i><b>6.3.1</b> Model Metrics</a></li>
<li class="chapter" data-level="6.3.2" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#test-dataset-comparison"><i class="fa fa-check"></i><b>6.3.2</b> Test Dataset Comparison</a></li>
<li class="chapter" data-level="6.3.3" data-path="model-building-and-scoring-for-prediction.html"><a href="model-building-and-scoring-for-prediction.html#python-code-27"><i class="fa fa-check"></i><b>6.3.3</b> Python Code</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html"><i class="fa fa-check"></i><b>7</b> Categorical Data Analysis</a>
<ul>
<li class="chapter" data-level="7.1" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#describing-categorical-data"><i class="fa fa-check"></i><b>7.1</b> Describing Categorical Data</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#python-code-28"><i class="fa fa-check"></i><b>7.1.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#tests-of-association"><i class="fa fa-check"></i><b>7.2</b> Tests of Association</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#python-code-29"><i class="fa fa-check"></i><b>7.2.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#measures-of-association"><i class="fa fa-check"></i><b>7.3</b> Measures of Association</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#python-code-30"><i class="fa fa-check"></i><b>7.3.1</b> Python Code</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#introduction-to-logistic-regression"><i class="fa fa-check"></i><b>7.4</b> Introduction to Logistic Regression</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#linear-probability-model"><i class="fa fa-check"></i><b>7.4.1</b> Linear Probability Model</a></li>
<li class="chapter" data-level="7.4.2" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#binary-logistic-regression"><i class="fa fa-check"></i><b>7.4.2</b> Binary Logistic Regression</a></li>
<li class="chapter" data-level="7.4.3" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#adding-categorical-variables"><i class="fa fa-check"></i><b>7.4.3</b> Adding Categorical Variables</a></li>
<li class="chapter" data-level="7.4.4" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#model-assessment"><i class="fa fa-check"></i><b>7.4.4</b> Model Assessment</a></li>
<li class="chapter" data-level="7.4.5" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#variable-selection-and-regularized-regression"><i class="fa fa-check"></i><b>7.4.5</b> Variable Selection and Regularized Regression</a></li>
<li class="chapter" data-level="7.4.6" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#python-code-31"><i class="fa fa-check"></i><b>7.4.6</b> Python Code</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Foundations</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="intro-stat" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Chapter 1</span> Introduction to Statistics<a href="intro-stat.html#intro-stat" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Welcome to your introduction to statistics. You will be learning the basics of statistics, along with applications of statistics within the R language. This book will provide fundamentals of the concepts and the code to apply these concepts in R. At the end of each section, you will also find the Python code that will perform a comparable analysis (however, in class, we will be discussing and focusing on the R code). </p>
<p>This Chapter aims to answer the following questions:</p>
<ul>
<li>What type of data is being analyzed?
<ul>
<li>Nominal</li>
<li>Ordinal</li>
<li>Continuous/Discrete</li>
</ul></li>
<li>How do we describe distributions of these variables?
<ul>
<li>Center</li>
<li>Spread</li>
<li>Shape</li>
<li>Graphical Display</li>
</ul></li>
<li>How do we create confidence intervals for parameters?</li>
<li>How do we perform hypothesis testing?
<ul>
<li>One sample t-test</li>
<li>Two sample t-test</li>
<li>Testing Normality</li>
<li>Testing Equality of Variances</li>
<li>Testing Equality of Means</li>
<li>Mann-Whitney-Wilcoxon Test</li>
</ul></li>
</ul>
<p>The following packages will be used in this textbook (there are some sections that add more later in the textbook, so keep your eyes open for those). In order to use a library in the R session, you will first need to install it on your local drive (this only needs to be done once….however, you should periodically check for updates to packages). You should also periodically check to see if R or RStudio needs to be updated as well.</p>
<p>Installing packages:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="intro-stat.html#cb1-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;AmesHousing&#39;</span>)</span>
<span id="cb1-2"><a href="intro-stat.html#cb1-2" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;tidyverse&#39;</span>)</span>
<span id="cb1-3"><a href="intro-stat.html#cb1-3" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;car&#39;</span>)</span>
<span id="cb1-4"><a href="intro-stat.html#cb1-4" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;DescTools&#39;</span>)</span>
<span id="cb1-5"><a href="intro-stat.html#cb1-5" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;corrplot&#39;</span>)</span>
<span id="cb1-6"><a href="intro-stat.html#cb1-6" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;mosaic&#39;</span>)</span>
<span id="cb1-7"><a href="intro-stat.html#cb1-7" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;modelr&#39;</span>)</span>
<span id="cb1-8"><a href="intro-stat.html#cb1-8" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;plotly&#39;</span>)</span>
<span id="cb1-9"><a href="intro-stat.html#cb1-9" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;ggplot2&#39;</span>)</span>
<span id="cb1-10"><a href="intro-stat.html#cb1-10" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;Hmisc&#39;</span>)</span>
<span id="cb1-11"><a href="intro-stat.html#cb1-11" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;onehot&#39;</span>)</span>
<span id="cb1-12"><a href="intro-stat.html#cb1-12" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;jmuOutlier&#39;</span>)</span>
<span id="cb1-13"><a href="intro-stat.html#cb1-13" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;leaps&#39;</span>)</span>
<span id="cb1-14"><a href="intro-stat.html#cb1-14" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;glmnet&#39;</span>)</span>
<span id="cb1-15"><a href="intro-stat.html#cb1-15" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;nortest&#39;</span>)</span>
<span id="cb1-16"><a href="intro-stat.html#cb1-16" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;lmtest&#39;</span>)</span>
<span id="cb1-17"><a href="intro-stat.html#cb1-17" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;gmodels&#39;</span>)</span>
<span id="cb1-18"><a href="intro-stat.html#cb1-18" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;vcdExtra&#39;</span>)</span>
<span id="cb1-19"><a href="intro-stat.html#cb1-19" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;TSA&#39;</span>)</span>
<span id="cb1-20"><a href="intro-stat.html#cb1-20" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;carData&#39;</span>)</span>
<span id="cb1-21"><a href="intro-stat.html#cb1-21" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;epiDisplay&#39;</span>)</span></code></pre></div>
<p>You will need to bring the packages into your currently opened R session (this will need to be done whenever you open a new session):</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="intro-stat.html#cb2-1" tabindex="-1"></a><span class="fu">library</span>(AmesHousing)</span></code></pre></div>
<pre><code>## Warning: package &#39;AmesHousing&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="intro-stat.html#cb4-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## Warning: package &#39;tidyverse&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="intro-stat.html#cb6-1" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div>
<pre><code>## Warning: package &#39;car&#39; was built under R version 4.3.3</code></pre>
<pre><code>## Warning: package &#39;carData&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="intro-stat.html#cb9-1" tabindex="-1"></a><span class="fu">library</span>(DescTools)</span></code></pre></div>
<pre><code>## Warning: package &#39;DescTools&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="intro-stat.html#cb11-1" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code></pre></div>
<pre><code>## Warning: package &#39;corrplot&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="intro-stat.html#cb13-1" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span></code></pre></div>
<pre><code>## Warning: package &#39;mosaic&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="intro-stat.html#cb15-1" tabindex="-1"></a><span class="fu">library</span>(modelr)</span></code></pre></div>
<pre><code>## Warning: package &#39;modelr&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="intro-stat.html#cb17-1" tabindex="-1"></a><span class="fu">library</span>(plotly)</span></code></pre></div>
<pre><code>## Warning: package &#39;plotly&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="intro-stat.html#cb19-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb19-2"><a href="intro-stat.html#cb19-2" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span>
<span id="cb19-3"><a href="intro-stat.html#cb19-3" tabindex="-1"></a><span class="fu">library</span>(onehot)</span>
<span id="cb19-4"><a href="intro-stat.html#cb19-4" tabindex="-1"></a><span class="fu">library</span>(jmuOutlier)</span></code></pre></div>
<pre><code>## Warning: package &#39;jmuOutlier&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="intro-stat.html#cb21-1" tabindex="-1"></a><span class="fu">library</span>(leaps)</span></code></pre></div>
<pre><code>## Warning: package &#39;leaps&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="intro-stat.html#cb23-1" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span></code></pre></div>
<pre><code>## Warning: package &#39;glmnet&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="intro-stat.html#cb25-1" tabindex="-1"></a><span class="fu">library</span>(nortest)</span>
<span id="cb25-2"><a href="intro-stat.html#cb25-2" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code></pre></div>
<pre><code>## Warning: package &#39;lmtest&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="intro-stat.html#cb27-1" tabindex="-1"></a><span class="fu">library</span>(gmodels)</span></code></pre></div>
<pre><code>## Warning: package &#39;gmodels&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="intro-stat.html#cb29-1" tabindex="-1"></a><span class="fu">library</span>(vcdExtra)</span></code></pre></div>
<pre><code>## Warning: package &#39;vcdExtra&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="intro-stat.html#cb31-1" tabindex="-1"></a><span class="fu">library</span>(TSA)</span></code></pre></div>
<pre><code>## Warning: package &#39;TSA&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="intro-stat.html#cb33-1" tabindex="-1"></a><span class="fu">library</span>(carData)</span>
<span id="cb33-2"><a href="intro-stat.html#cb33-2" tabindex="-1"></a><span class="fu">library</span>(epiDisplay)</span></code></pre></div>
<pre><code>## Warning: package &#39;epiDisplay&#39; was built under R version 4.3.3</code></pre>
<div id="eda" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Exploratory Data Analysis (EDA)<a href="intro-stat.html#eda" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The crucial first step to any data science problem is exploratory data analysis (EDA). Before you attempt to run any models, or jump towards any formal statistical analysis, you must <strong><em>explore your data</em></strong>. Many unexpected frustrations arise when exploratory analysis is overlooked; knowing your data is critical to your ability to make necessary assumptions about it and analyzing it appropriately. This preliminary analysis will help inform our decisions for data manipulation, give us a base-level understanding of our variables and the relationships between them, and help determine which statistical analyses might be appropriate for the questions we are trying to answer. Some of the questions we aim to answer through exploratory analysis are:</p>
<ul>
<li>What kind of variables do you have?
<ul>
<li>Continuous</li>
<li>Nominal</li>
<li>Ordinal</li>
</ul></li>
<li>How are the attributes stored?
<ul>
<li>Strings</li>
<li>Integers</li>
<li>Floats/Numeric</li>
<li>Dates</li>
</ul></li>
<li>What do their distributions look like?
<ul>
<li>Center/Location</li>
<li>Spread</li>
<li>Shape</li>
</ul></li>
<li>Are there any anomolies?
<ul>
<li>Outliers</li>
<li>Leverage points</li>
<li>Missing values</li>
<li>Low-frequency categories</li>
</ul></li>
</ul>
<p>Throughout the textbook, we will continue to use a real-estate data set that contains the <code>sale_price</code> and numerous physical attributes of nearly 3,000 homes in Ames, Iowa in the early 2000s. You should have already loaded the <code>AmesHousing</code> package which has the data set, so now we will create a nicely formatted data set with the <code>make_ordinal_ames()</code> function. The function <code>str()</code> is a good way to see what variables are in the data set and how they are currently formatted. Take a look at some of the variables within the AmesHousing data set.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="intro-stat.html#cb35-1" tabindex="-1"></a>ames <span class="ot">&lt;-</span> <span class="fu">make_ordinal_ames</span>() </span>
<span id="cb35-2"><a href="intro-stat.html#cb35-2" tabindex="-1"></a><span class="fu">str</span>(ames)</span></code></pre></div>
<div id="vartypes" class="section level3 hasAnchor" number="1.1.1">
<h3><span class="header-section-number">1.1.1</span> Types of Variables<a href="intro-stat.html#vartypes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The columns of a data set are referred to by the following <strong>equivalent terms</strong>:</p>
<ul>
<li>Variables</li>
<li>Features</li>
<li>Attributes</li>
<li>Predictors/Targets</li>
<li>Factors</li>
<li>Inputs/Outputs</li>
</ul>
<p>This book may use any of these words interchangeably to refer to a quality or quantity of interest in our data.</p>
<div id="nominal-variables" class="section level4 hasAnchor" number="1.1.1.1">
<h4><span class="header-section-number">1.1.1.1</span> Nominal Variables<a href="intro-stat.html#nominal-variables" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A <strong>nominal</strong> or <strong>categorical variable</strong> is a <em>quality of interest</em> whose values have no logical ordering. Color (“blue”, “red”, “green”…), ethnicity (“African-American”, “Asian”, “Caucasian”,…), and style of house (“ranch”, “two-story”, “duplex”, …) are all examples of nominal attributes. The categories or values that these variables can take on - those words listed in quotes and parenthesis - are called the <strong>levels</strong> of the variable.</p>
<p>In modeling, nominal attributes are commonly transformed into <strong>dummy variables</strong>. Dummy variables are binary columns that indicate the presence or absence of a quality. There is more than one way to create dummy variables, and the treatment/estimates will be different depending on what type of model you are using. Linear regression models will use either <strong>reference-level</strong> or <strong>effects coding</strong>, whereas other machine learning models are more likely to use one-hot encoding or a variation thereof.</p>
<p><strong>One-hot encoding</strong></p>
<p>For machine learning applications, it is common to create a binary dummy column for each level of your categorical variable. This is the most intuitive representation of categorical information, answering indicative questions for each level of the variable: <em>“is it blue?”</em>, <em>“is it red?”</em> etc. The table below gives an example of some data, the original nominal variable (color) and the one-hot encoded color information.</p>
<table>
<tr>
<td>
Observation
<td>
Color
<td>
Blue
<td>
Red
<td>
Yellow
<td>
Other
<tr>
<td>
1
<td>
Blue
<td>
1
<td>
0
<td>
0
<td>
0
<tr>
<td>
2
<td>
Yellow
<td>
0
<td>
0
<td>
1
<td>
0
<tr>
<td>
3
<td>
Blue
<td>
1
<td>
0
<td>
0
<td>
0
<tr>
<td>
4
<td>
Red
<td>
0
<td>
1
<td>
0
<td>
0
<tr>
<td>
5
<td>
Red
<td>
0
<td>
1
<td>
0
<td>
0
<tr>
<td>
6
<td>
Blue
<td>
1
<td>
0
<td>
0
<td>
0
<tr>
<td>
7
<td>
Yellow
<td>
0
<td>
0
<td>
1
<td>
0
<tr>
<td>
8
<td>
Other
<td>
0
<td>
0
<td>
0
<td>
1
</table>
<caption>
<span id="tab:onehot">Table 1.1: </span>One-hot dummy variable coding for the categorical attribute <em>color</em>
</caption>
<p>We will demonstrate the creation of this data using some simple random categorical data:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="intro-stat.html#cb36-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">41</span>)</span>
<span id="cb36-2"><a href="intro-stat.html#cb36-2" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">y =</span> <span class="fu">c</span>(<span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">2</span>), <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">1</span>),<span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">0</span>)),</span>
<span id="cb36-3"><a href="intro-stat.html#cb36-3" tabindex="-1"></a>                <span class="at">x1 =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;C&quot;</span>), <span class="at">each =</span> <span class="dv">10</span>)),</span>
<span id="cb36-4"><a href="intro-stat.html#cb36-4" tabindex="-1"></a>                <span class="at">x2 =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;Z&quot;</span>, <span class="st">&quot;X&quot;</span>, <span class="st">&quot;Y&quot;</span>,<span class="st">&quot;W&quot;</span>,<span class="st">&quot;V&quot;</span>,<span class="st">&quot;U&quot;</span>), <span class="at">each =</span> <span class="dv">5</span>)))</span>
<span id="cb36-5"><a href="intro-stat.html#cb36-5" tabindex="-1"></a><span class="fu">print</span>(dat)</span></code></pre></div>
<pre><code>##             y x1 x2
## 1   1.2056317  A  Z
## 2   2.1972575  A  Z
## 3   3.0017043  A  Z
## 4   3.2888254  A  Z
## 5   2.9057534  A  Z
## 6   2.4936675  A  X
## 7   2.5992858  A  X
## 8   0.4203930  A  X
## 9   3.0006207  A  X
## 10  4.1880077  A  X
## 11 -0.2093244  B  Y
## 12  0.4126881  B  Y
## 13  2.0561206  B  Y
## 14  0.6834151  B  Y
## 15  0.9454590  B  Y
## 16  1.3297513  B  W
## 17  1.6630951  B  W
## 18  1.8783282  B  W
## 19  1.2028743  B  W
## 20  3.2744025  B  W
## 21 -0.8992970  C  V
## 22  2.1394903  C  V
## 23 -1.1659510  C  V
## 24 -0.0471304  C  V
## 25  0.4158763  C  V
## 26  1.7200805  C  U
## 27 -0.7843607  C  U
## 28 -1.3039296  C  U
## 29 -0.4520359  C  U
## 30 -1.7739919  C  U</code></pre>
<p>Unlike reference and effects coding, which are used in linear regression models, one-hot encoding is most quickly achieved through use of the <code>onehot</code> package in R, which first creates an “encoder” to do the job quickly.</p>
<p>The speed of this function has been tested against both the base R <code>model.matrix()</code> function and the <code>dummyVars()</code> function in the <code>caret</code> package and is <em>substantially</em> faster than either.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="intro-stat.html#cb38-1" tabindex="-1"></a><span class="fu">library</span>(onehot)</span>
<span id="cb38-2"><a href="intro-stat.html#cb38-2" tabindex="-1"></a></span>
<span id="cb38-3"><a href="intro-stat.html#cb38-3" tabindex="-1"></a>encoder  <span class="ot">=</span> <span class="fu">onehot</span>(dat)</span>
<span id="cb38-4"><a href="intro-stat.html#cb38-4" tabindex="-1"></a>dummies <span class="ot">=</span> <span class="fu">predict</span>(encoder,dat)</span>
<span id="cb38-5"><a href="intro-stat.html#cb38-5" tabindex="-1"></a><span class="fu">head</span>(dummies)</span></code></pre></div>
<pre><code>##             y x1=A x1=B x1=C x2=U x2=V x2=W x2=X x2=Y x2=Z
## [1,] 1.205632    1    0    0    0    0    0    0    0    1
## [2,] 2.197258    1    0    0    0    0    0    0    0    1
## [3,] 3.001704    1    0    0    0    0    0    0    0    1
## [4,] 3.288825    1    0    0    0    0    0    0    0    1
## [5,] 2.905753    1    0    0    0    0    0    0    0    1
## [6,] 2.493667    1    0    0    0    0    0    1    0    0</code></pre>
<p><strong>Reference-level coding </strong></p>
<p>Reference-level coding is similar to one-hot encoding except one of the levels of the attribute, called the <strong>reference level</strong>, is omitted. Notice that the 4 dummy columns from Table <a href="intro-stat.html#tab:onehot">1.1</a> collectively form a linearly dependent set; that is, if you know the values of 3 of the 4 dummy variables you can determine the <span class="math inline">\(4^{th}\)</span> with complete certainty. This would be a problem for linear regression, where we assume our input attributes are not linearly dependent as we will discuss when we get to Simple Linear Regression.</p>
<p>A reference level of the attribute is often specified by the user to be a particular level worthy of comparison (a baseline), as the estimates in the regression output will be interpreted in a way that compares each non-reference level to the reference level. If a reference level is not specified by the user, one will be picked by the software by default either using the order in which the levels were encountered in the data, or their alphabetical ordering. Users should check the documentation of the associated function to understand what to expect.</p>
<p>Table <a href="intro-stat.html#tab:refcoding">1.2</a> transforms the one-hot encoding from Table <a href="intro-stat.html#tab:onehot">1.1</a> into reference-level coding with the color “blue” as the reference level. Notice the absence of the column indicating “blue” and how each blue observation exists as a row of zeros.</p>
<table>
<tr>
<td>
Observation
<td>
Color
<td>
Red
<td>
Yellow
<td>
Other
</tr>
<tr>
<td>
1
<td>
Blue
<td>
0
<td>
0
<td>
0
</tr>
<tr>
<td>
2
<td>
Yellow
<td>
0
<td>
1
<td>
0
</tr>
<tr>
<td>
3
<td>
Blue
<td>
0
<td>
0
<td>
0
</tr>
<tr>
<td>
4
<td>
Red
<td>
1
<td>
0
<td>
0
</tr>
<tr>
<td>
5
<td>
Red
<td>
1
<td>
0
<td>
0
</tr>
<tr>
<td>
6
<td>
Blue
<td>
0
<td>
0
<td>
0
</tr>
<tr>
<td>
7
<td>
Yellow
<td>
0
<td>
1
<td>
0
</tr>
<tr>
<td>
8
<td>
Other
<td>
0
<td>
0
<td>
1
</tr>
</table>
<caption>
<span id="tab:refcoding">Table 1.2: </span> Reference-level dummy variable coding for the categorical attribute <em>color</em> and the reference level of “blue”
</caption>
<p><strong>Effects coding</strong></p>
<p>Effects coding is useful for obtaining a more general comparative interpretation when you have approximately equal sample sizes across each level of your categorical attribute. Effects coding is designed to allow the user to compare each level to <em>all</em> of the other levels. More specifically the mean of each level is compared to the <strong>overall mean</strong> of your data. However, the comparison is actually to the so-called <em>grand mean</em>, which is the mean of the means of each group. When sample sizes are equal, the grand mean and the overall sample mean are equivalent. When sample sizes are <em>not</em> equal, the parameter estimates for effects coding should not be used for interpretation or explanation.</p>
<p>Effects coding still requires a <em>reference level</em>, however the purpose of the reference level is not the same as it was in reference-level coding. Here, the reference level is left out in the sense that no comparison is made between it and the overall mean. Table <a href="intro-stat.html#tab:effcoding">1.3</a> shows our same example with effects coding. Again we notice the absence of the column indicating “blue” but now the reference level receives values of <code>-1</code> rather than <code>0</code> for all 3 dummy columns. We will revisit the interpretation of linear regression coefficients under this coding scheme in the Simple Linear Regression Section.</p>
<table>
<tr>
<td>
Observation
<td>
Color
<td>
Red
<td>
Yellow
<td>
Other
<tr>
<td>
1
<td>
Blue
<td>
-1
<td>
-1
<td>
-1
<tr>
<td>
2
<td>
Yellow
<td>
0
<td>
1
<td>
0
<tr>
<td>
3
<td>
Blue
<td>
-1
<td>
-1
<td>
-1
<tr>
<td>
4
<td>
Red
<td>
1
<td>
0
<td>
0
<tr>
<td>
5
<td>
Red
<td>
1
<td>
0
<td>
0
<tr>
<td>
6
<td>
Blue
<td>
-1
<td>
-1
<td>
-1
<tr>
<td>
7
<td>
Yellow
<td>
0
<td>
1
<td>
0
<tr>
<td>
8
<td>
Other
<td>
0
<td>
0
<td>
1
</table>
<caption>
<span id="tab:effcoding">Table 1.3: </span> Effects coding for the categorical attribute <em>color</em> and the reference level of “blue”
</caption>
</div>
<div id="interval-variables" class="section level4 hasAnchor" number="1.1.1.2">
<h4><span class="header-section-number">1.1.1.2</span> Interval Variables<a href="intro-stat.html#interval-variables" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>An interval variable is a <em>quantity of interest</em> on which the mathematical operations of addition, subtraction, multiplication and division can be performed. Time, temperature and age are all examples of interval attributes. To illustrate the definition, note that “15 minutes” divided by “5 minutes” is 3, which indicates that 15 minutes is 3 times as long as 5 minutes. The sensible interpretation of this simple arithmetic sentence demonstrates the nature of interval attributes. One should note that such arithmetic would not make sense in the treatment of nominal variables.</p>
</div>
<div id="ordinal-variables" class="section level4 hasAnchor" number="1.1.1.3">
<h4><span class="header-section-number">1.1.1.3</span> Ordinal Variables<a href="intro-stat.html#ordinal-variables" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><strong>Ordinal variables</strong> are attributes that are qualitative in nature but have some natural ordering. <em>Level of education</em> is a common example, with a level of ‘PhD’ indicating <em>more</em> education than ‘Bachelors’ but lacking a numerical framework to quantify <em>how much more</em>. The treatment of ordinal variables will depend on the application. Survey responses on a Likert scale are also ordinal - a response of 4=“somewhat agree” on a 1-to-5 scale of agreement cannot reliably be said to be twice as enthusiastic as a response of 2=“somewhat disagree”. These are not interval measurements, though they are often treated as such in a trade-off for computational efficiency.</p>
<p><strong>Ordinal variables will either be given some numeric value and treated as interval variables or they will be treated as categorical variables and dummy variables will be created. The choice of solution is up to the analyst.</strong> When numeric values are assigned to ordinal variables, the possibilities are many. For example, consider <em>level of education</em>. The simplest ordinal treatment for such an attribute might be something like Table <a href="intro-stat.html#tab:educationint">1.4</a>.</p>
<table>
<tr>
<td>
Level of Education
<td>
Numeric Value
<tr>
<td>
No H.S. Diploma
<td>
1
<tr>
<td>
H.S. Diploma or GED
<td>
2
<tr>
<td>
Associates or Certificate
<td>
3
<tr>
<td>
Bachelors
<td>
4
<tr>
<td>
Masters
<td>
5
<tr>
<td>
PhD
<td>
6
</table>
<caption>
<span id="tab:educationint">Table 1.4: </span> One potential approach to scaling the ordinal attribute level of education
</caption>
<p>While numeric values have been assigned and this data and <em>could</em> be used like an interval attribute, it’s important to realize that the notion of a “one-unit increase” is qualitative in nature rather than quantitative. However, if we’re interested in learning whether there is a <em>linear</em> type of relationship between education and another attribute (meaning as education level increases, the value of another attribute increases or decreases), this would be the path to get us there. However we’re making an assumption in this model that the difference between a H.S. Diploma and an Associates degree (a difference of “1 unit”) is the same as the difference between a Master’s degree and a PhD (also a difference of “1 unit”). These types of assumptions can be flawed, and it is often desirable to develop an alternative system of measurement based either on domain expertise or the target variable of interest. This is the notion behind <strong>optimal scaling</strong> and <strong>target-level encoding</strong>.</p>
<p><strong>Optimal Scaling</strong></p>
<p>The primary idea behind optimal scaling is to transform an ordinal attribute into an interval one in a way that doesn’t restrict the numeric values to simply the integers <span class="math inline">\(1,2,3, \dots\)</span>. It’s reasonable for a data scientist to use domain expertise to develop an alternative scheme.</p>
<p>For example, if analyzing movie theater concessions with ordinal drink sizes {small, medium, large}, one is not restricted to the numeric valuation of 1=small, 2=medium, and 3=large just because it’s an ordinal variable with 3 levels. Perhaps it would make more sense to use the drink size in fluid ounces to represent the ordinality. If the small drink is 12 ounces, the medium is 20 ounces, and the large is 48 ounces, then using those values as the numerical representation would be every bit as (if not more) reasonable than using the standard integers 1, 2, and 3.</p>
<p>If we re-consider the ordinal attribute level of education, we might decide to represent the approximate years of post-secondary schooling required to obtain a given level. This might lead us to something like the attribute values in Table <a href="#tab:educationscaled"><strong>??</strong></a>.</p>
<table>
<tr>
<td>
Level of Education
<td>
Numeric Value
<tr>
<td>
No H.S. Diploma
<td>
8
<tr>
<td>
H.S. Diploma or GED
<td>
13
<tr>
<td>
Associates or Certificate
<td>
15
<tr>
<td>
Bachelors
<td>
17
<tr>
<td>
Masters
<td>
19
<tr>
<td>
PhD
<td>
22
</table>
<caption>
<span id="tab:educationint">Table 1.4: </span> One potential approach to scaling the ordinal attribute level of education
</caption>
<p>If we were modeling the effect of education on something like salary, it seems reasonable to assume that the jumps between levels should not have equal distance like they did in <a href="intro-stat.html#tab:educationint">1.4</a>. It seems reasonable to assume that one would experience a larger salary lift from Associate’s to Bachelor’s degree than they would from No H.S. Diploma to H.S Diploma. The most common way to determine the numeric values for categories is to use information from the response variable. This is commonly referred to as <strong>target level encoding</strong>.</p>
<p><strong>Target Level Encoding</strong></p>
<p>The values in Table <a href="#tab:educationscaled"><strong>??</strong></a> might have struck the reader as logical but arbitrary. To be more scientific about the determination of those numeric values, one might wish to use information from the response variable to obtain a more precise expected change in salary for each level increase in education. At first hearing this, one might question the validity of the technique; isn’t the goal to <em>predict</em> salary? This line of thought is natural, which is why having a holdout sample is extremely important in this situation. To implement Target level encoding, we can simply create a look-up table that matches each level of education to the average or median salary obtained for that level. These values can be used just as readily as the arbitrary levels created in Table <a href="#tab:educationscaled"><strong>??</strong></a> to encode the ordinal attribute!</p>
</div>
</div>
<div id="distributions" class="section level3 hasAnchor" number="1.1.2">
<h3><span class="header-section-number">1.1.2</span> Distributions<a href="intro-stat.html#distributions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>After reviewing the types and formats of the data inputs, we move on to some basic <strong>univariate</strong> (one variable at a time) analysis. We start by describing the distribution of values that each variable takes on. For nominal variables, this amounts to frequency tables and bar charts of how often each level of the variable appears in the data set.</p>
<p>We’ll begin by exploring one of our nominal features, <code>Heating_QC</code> which categorizes the quality and condition of a home’s heating system. To create plots in R, we will use the popular <code>ggplot2</code> library. At the same time, we will load the <code>tidyverse</code> library which we will use in the next chunk of code.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="intro-stat.html#cb40-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb40-2"><a href="intro-stat.html#cb40-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb40-3"><a href="intro-stat.html#cb40-3" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> ames) <span class="sc">+</span></span>
<span id="cb40-4"><a href="intro-stat.html#cb40-4" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Heating_QC),<span class="at">fill=</span><span class="st">&quot;orange&quot;</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Heating System Quality&quot;</span>,<span class="at">y=</span><span class="st">&quot;Frequency&quot;</span>,<span class="at">title=</span><span class="st">&quot;Bar Graph of Heating System&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:barchart"></span>
<img src="bookdownproj_files/figure-html/barchart-1.png" alt="Distribution of Nominal Variable Heating_QC" width="672" />
<p class="caption">
Figure 1.1: Distribution of Nominal Variable Heating_QC
</p>
</div>
<p>To summon the same information in tabular form, we can use the <code>count()</code> function to create a table:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="intro-stat.html#cb41-1" tabindex="-1"></a>ames <span class="sc">%&gt;%</span> </span>
<span id="cb41-2"><a href="intro-stat.html#cb41-2" tabindex="-1"></a>  <span class="fu">count</span>(Heating_QC)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 2
##   Heating_QC     n
##   &lt;ord&gt;      &lt;int&gt;
## 1 Poor           3
## 2 Fair          92
## 3 Typical      864
## 4 Good         476
## 5 Excellent   1495</code></pre>
<p>You’ll notice that very few houses (3) have heating systems in <code>Poor</code> condition, and the majority of houses have systems rated <code>Excellent</code>. <strong>It will likely make sense to combine the categories of <code>Fair</code> and <code>Poor</code> in our eventual analysis, a decision we will later revisit.</strong></p>
<p>Next we create a <strong>histogram</strong> for an interval attribute like <code>Sale_Price</code>:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="intro-stat.html#cb43-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> ames) <span class="sc">+</span></span>
<span id="cb43-2"><a href="intro-stat.html#cb43-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Sale_Price<span class="sc">/</span><span class="dv">1000</span>),<span class="at">fill=</span><span class="st">&quot;blue&quot;</span>) <span class="sc">+</span> </span>
<span id="cb43-3"><a href="intro-stat.html#cb43-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Sales Price (Thousands $)&quot;</span>,<span class="at">y=</span><span class="st">&quot;Frequency&quot;</span>,<span class="at">title=</span><span class="st">&quot;Histogram of Sales Price in Thousands of Dollars&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:histogram"></span>
<img src="bookdownproj_files/figure-html/histogram-1.png" alt="Distribution of Interval Variable Sale_Price" width="672" />
<p class="caption">
Figure 1.2: Distribution of Interval Variable Sale_Price
</p>
</div>
<p>From this initial inspection, we can conclude that most of the houses sell for less than $200,000 and there are a number of expensive anomalies. To more concretely describe and quantify a statistical distribution, we use statistics that describe the <em>location, spread, and shape</em> of the data.</p>
<div id="location" class="section level4 hasAnchor" number="1.1.2.1">
<h4><span class="header-section-number">1.1.2.1</span> Location<a href="intro-stat.html#location" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The <em>location</em> is a measure of central tendency for a distribution. Most common measures of central tendency are <strong>mean</strong>, <strong>median</strong>, and <strong>mode</strong>.</p>
<p>We define each of these terms below for a variable <span class="math inline">\(\mathbf{x}\)</span> having n observations with values <span class="math inline">\(\{x_i\}_{i=1}^n\)</span>, sorted in order of magnitude such that <span class="math inline">\(x_1 \leq x_2 \leq \dots \leq x_n\)</span>:</p>
<ul>
<li>Mean: The <strong>average</strong> of the observations, <span class="math inline">\(\bar{\mathbf{x}}= \frac{1}{n}\sum_{i=1}^n x_i\)</span></li>
<li>Median: The “middle value” of the data. Formally, when <span class="math inline">\(n\)</span> is odd, the median is the observation value, <span class="math inline">\(x_m = x_{\frac{(n+1)}{2}}\)</span> for which <span class="math inline">\(x_i &lt; x_m\)</span> for 50% of the observations (excluding <span class="math inline">\(x_m\)</span>). When <span class="math inline">\(n\)</span> is even, <span class="math inline">\(x_m\)</span> is the average of <span class="math inline">\(x_\frac{n}{2}\)</span> and <span class="math inline">\(x_{(\frac{n}{2}+1)}\)</span>. The median is also known as the <span class="math inline">\(2^{nd}\)</span> <strong>quartile</strong> (see next section).</li>
<li>Mode: The most commonly occurring value in the data. Most commonly used to describe nominal attributes.</li>
</ul>
<p><strong>Example</strong></p>
<p>The following table contains the heights of 10 students randomly sampled from NC State’s campus. Compute the mean, median, mode and quartiles of this variable.</p>
<table style="width:auto; margin-left: auto; margin-right: auto;" >
<tr>
<td style="text-align:center">
height
<td style="text-align:center">
60
<td style="text-align:center">
62
<td style="text-align:center">
63
<td style="text-align:center">
65
<td style="text-align:center">
67
<td style="text-align:center">
67
<td style="text-align:center">
67
<td style="text-align:center">
68
<td style="text-align:center">
68
<td style="text-align:center">
69
</table>
<p><strong>Solution:</strong></p>
<ul>
<li>The mean is <code>(60+62+63+65+67+67+67+68+68+69)/10</code> = 65.6.</li>
<li>The median (second quartile) is <code>(67+67)/2</code> = 67.</li>
<li>The mode is 67.</li>
</ul>
</div>
<div id="spread" class="section level4 hasAnchor" number="1.1.2.2">
<h4><span class="header-section-number">1.1.2.2</span> Spread<a href="intro-stat.html#spread" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Once we have an understanding of the central tendency of a data set, we move on to describing the spread (the dispersion or variation) of the data. <strong>Range</strong>, <strong>interquartile range</strong>, <strong>variance</strong>, and <strong>standard deviation</strong> are all statistics that describe spread.</p>
<ul>
<li>Range: The difference between the maximum and minimum data values.</li>
<li>Sample variance: The sum of squared differences between each data point and the mean, divided by (n-1). <span class="math inline">\(\frac{1}{n-1}\sum_{i=1}^n (x_i-\bar{x})^2\)</span></li>
<li>Standard deviation: The square root of the sample variance.<br />
</li>
</ul>
<p>In order to define <strong>interquartile range</strong>, we must first define <strong>percentiles</strong> and <strong>quartiles</strong>.</p>
<ul>
<li>Percentiles: The 99 intermediate values of the data which divide the observations into 100 equally-sized groups. The <span class="math inline">\(r^{th}\)</span> percentile of the data, <span class="math inline">\(P_{r}\)</span> is the number for which <span class="math inline">\(r\)</span>% of the data is less than <span class="math inline">\(P_{r}\)</span>. Percentiles are also called Quantiles.</li>
<li>Quartiles: The quartiles of the data are the <span class="math inline">\(25^{th}\)</span>, <span class="math inline">\(50^{th}\)</span> and <span class="math inline">\(75^{th}\)</span> percentiles. They are denoted as <span class="math inline">\(Q_{1}\)</span> (<span class="math inline">\(1^{st}\)</span> quartile), <span class="math inline">\(Q_{2}\)</span> (<span class="math inline">\(2^{nd}\)</span> quartile = median) and <span class="math inline">\(Q_{3}\)</span> (<span class="math inline">\(3^{rd}\)</span> quartile), respectively.</li>
<li>Interquartile range (IQR): The difference between the <span class="math inline">\(25^{th}\)</span> and <span class="math inline">\(75^{th}\)</span> percentiles.</li>
</ul>
<p>One should note that standard deviation is more frequently reported than variance because it shares the same units as the original data, and because of the guidance provided by the empirical rule. If we’re exploring something like <code>Sale_Price</code>, which has the unit “dollars”, then the variance would be measured in “square-dollars”, which hampers the intuition. Standard deviation, on the other hand, would share the unit “dollars”, aiding our fundamental understanding.</p>
<p><strong>Example </strong>
Let’s again use the table of heights from the previous example, this time computing the range, IQR, sample variance and standard deviation.</p>
<table style="width:auto; margin-left: auto; margin-right: auto;" >
<tr>
<td style="text-align:center">
height
<td style="text-align:center">
60
<td style="text-align:center">
62
<td style="text-align:center">
63
<td style="text-align:center">
65
<td style="text-align:center">
67
<td style="text-align:center">
67
<td style="text-align:center">
67
<td style="text-align:center">
68
<td style="text-align:center">
68
<td style="text-align:center">
69
</table>
<p><strong>Solution:</strong></p>
<ul>
<li>The range <code>69-60</code> = 9.</li>
<li>The variance is <code>((60-65.6)^2+(62-65.6)^2+(63-65.6)^2+(65-65.6)^2+(67-65.6)^2+(67-65.6)^2+(67-65.6)^2+(68-65.6)^2+(68-65.6)^2+(69-65.6)^2)/9</code> = 8.933</li>
<li>The standard deviation is <code>sqrt(8.933)</code> = 2.989</li>
<li>The first quartile is 63.5</li>
<li>The third quartile is 67.75</li>
<li>The IQR is <code>68 - 62.5</code> = 4.25.</li>
</ul>
<p>Note: In R, to find the quartiles, you should ask for the 0.25, 0.5 and 0.75 quantiles.</p>
</div>
<div id="shape" class="section level4 hasAnchor" number="1.1.2.3">
<h4><span class="header-section-number">1.1.2.3</span> Shape<a href="intro-stat.html#shape" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The final description we will want to give to distributions regards their shape. Is the histogram <em>symmetric</em>? Is it <em>unimodal</em> (having a single large “heap” of data) or <em>multimodal</em> (having multiple heaps”)? Does it have a longer tail on one side than the other (<em>skew</em>)? Is there a lot more or less data in the tails than you might expect?</p>
<p>We’ll formalize these ideas with some illustrations. A distribution is right (left) skewed if it has a longer tail on its right (left) side, as shown in Figure <a href="intro-stat.html#fig:skewdiagram">1.3</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:skewdiagram"></span>
<img src="img/skewdiagrams.png" alt="Examples of Left-Skewed (Negative Skew) and Right-skewed (Positive Skew) distributions respectively" width="100%" />
<p class="caption">
Figure 1.3: Examples of Left-Skewed (Negative Skew) and Right-skewed (Positive Skew) distributions respectively
</p>
</div>
<p>A distribution is called <em>bimodal</em> if it has two “heaps”, as shown in Figure <a href="intro-stat.html#fig:bimodal">1.4</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:bimodal"></span>
<img src="img/bimodal.png" alt="Example of a Bimodal Distribution" width="50%" />
<p class="caption">
Figure 1.4: Example of a Bimodal Distribution
</p>
</div>
</div>
<div id="summary-functions-in-r" class="section level4 hasAnchor" number="1.1.2.4">
<h4><span class="header-section-number">1.1.2.4</span> Summary Functions in R<a href="intro-stat.html#summary-functions-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>There are many ways to obtain all of the statistics described in the preceding sections, below we highlight 3:</p>
<ul>
<li>The <code>describe</code> function from the <code>Hmisc</code> package which can work on the entire dataset or a subset of columns.</li>
</ul>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="intro-stat.html#cb44-1" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span>
<span id="cb44-2"><a href="intro-stat.html#cb44-2" tabindex="-1"></a></span>
<span id="cb44-3"><a href="intro-stat.html#cb44-3" tabindex="-1"></a>Hmisc<span class="sc">::</span><span class="fu">describe</span>(ames<span class="sc">$</span>Sale_Price)</span></code></pre></div>
<pre><code>## ames$Sale_Price 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##     2930        0     1032        1   180796    81960    87500   105450 
##      .25      .50      .75      .90      .95 
##   129500   160000   213500   281242   335000 
## 
## lowest :  12789  13100  34900  35000  35311, highest: 611657 615000 625000 745000 755000</code></pre>
<ul>
<li>The tidyverse <code>summarise</code> function, in this case obtaining statistics for each <code>Exter_Qual</code> separately.</li>
</ul>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="intro-stat.html#cb46-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb46-2"><a href="intro-stat.html#cb46-2" tabindex="-1"></a>ames <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Exter_Qual) <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">average =</span> <span class="fu">mean</span>(Sale_Price), <span class="at">st.dev =</span> <span class="fu">sd</span>(Sale_Price), <span class="at">maximum =</span> <span class="fu">max</span>(Sale_Price), <span class="at">minimum =</span> <span class="fu">min</span>(Sale_Price))</span></code></pre></div>
<pre><code>## # A tibble: 4 × 5
##   Exter_Qual average  st.dev maximum minimum
##   &lt;ord&gt;        &lt;dbl&gt;   &lt;dbl&gt;   &lt;int&gt;   &lt;int&gt;
## 1 Fair        89924.  38014.  200000   13100
## 2 Typical    143374.  41504.  415000   12789
## 3 Good       230756.  70411.  745000   52000
## 4 Excellent  377919. 106988.  755000  160000</code></pre>
<ul>
<li>The base R <code>summary</code> function, which can work on the entire dataset or an individual variable</li>
</ul>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="intro-stat.html#cb48-1" tabindex="-1"></a><span class="fu">summary</span>(ames<span class="sc">$</span>Sale_Price)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   12789  129500  160000  180796  213500  755000</code></pre>
</div>
</div>
<div id="normal" class="section level3 hasAnchor" number="1.1.3">
<h3><span class="header-section-number">1.1.3</span> The Normal Distribution<a href="intro-stat.html#normal" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The normal distribution, also known as the Gaussian distribution, is one of the most fundamental concepts in statistics. It is one that arises naturally out of many applications and settings. The Normal distribution has the following characteristics:</p>
<ul>
<li>Symmetric</li>
<li>Fully defined by mean and standard deviation (equivalently, variance)</li>
<li>Bell-shaped/Unimodal</li>
<li>Mean = Median = Mode</li>
<li>Assymptotic to the x-axis (theoretical bounds are <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(\infty\)</span>)</li>
</ul>
<p>Much of the normal distributions utility can be summarized in the <strong>empirical rule</strong>, which states that:</p>
<ul>
<li><span class="math inline">\(\approx\)</span> 68% of data in normal distribution lies within 1 standard deviation of the mean.</li>
<li><span class="math inline">\(\approx\)</span> 95% of data in normal distribution lies within 2 standard deviations of the mean.</li>
<li><span class="math inline">\(\approx\)</span> 99.7% of data in normal distribution lies within 3 standard deviations of the mean.</li>
</ul>
<p>We can thus conclude that observations found outside of 3 standard deviations from the mean are quite rare, expected less than 1% of the time.</p>
</div>
<div id="skew" class="section level3 hasAnchor" number="1.1.4">
<h3><span class="header-section-number">1.1.4</span> Skewness<a href="intro-stat.html#skew" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Skewness is a statistic that describes the symmetry (or lack thereof) of a distribution. A normal distribution is perfectly symmetric and has a skewness of 0. Distributions that are more right skewed will have positive values of skewness whereas distributions that are more left skewed will have negative values of skewness.</p>
</div>
<div id="kurt" class="section level3 hasAnchor" number="1.1.5">
<h3><span class="header-section-number">1.1.5</span> Kurtosis<a href="intro-stat.html#kurt" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Kurtosis is a statistic that describes the <em>tailedness</em> of a distribution. The normal distribution has a kurtosis of 3. Distributions that are more tailed (leptokurtic or heavy-tailed) will have kurtosis values greater than 3 whereas distributions that are more less tailed (platykurtic or thin-tailed) will have values of kurtosis less than 3. For this reason, kurtosis is often reported in the form of <em>excess kurtosis</em> which is the raw kurtosis value minus 3. This is meant as a comparison to the normal distribution so that positive values indicate thicker tails and negative values indicate thinner tails than the normal.</p>
<p>In Figure <a href="intro-stat.html#fig:kurtosis">1.5</a> below, we compare classical examples of leptokurtic and platykurtic distributions to a normal distribution with the same mean and variance.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:kurtosis"></span>
<img src="bookdownproj_files/figure-html/kurtosis-1.png" alt="The Laplace distribution (top left) is leptokurtic because it has more data in its tails than the normal distribution with the same mean and variance. The uniform distribution (top right) is platykurtic because it has less data in its tails than the normal distribution with the same mean and variance (it effectively has no tails)." width="672" />
<p class="caption">
Figure 1.5: The Laplace distribution (top left) is leptokurtic because it has more data in its tails than the normal distribution with the same mean and variance. The uniform distribution (top right) is platykurtic because it has less data in its tails than the normal distribution with the same mean and variance (it effectively has no tails).
</p>
</div>
</div>
<div id="graphdist" class="section level3 hasAnchor" number="1.1.6">
<h3><span class="header-section-number">1.1.6</span> Graphical Displays of Distributions<a href="intro-stat.html#graphdist" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Three common plots for examining the distribution of your data values:</p>
<ol style="list-style-type: decimal">
<li>Histograms</li>
<li>Normal Probability Plots (QQ-plots)</li>
<li>Box Plots</li>
</ol>
<div id="histograms" class="section level4 hasAnchor" number="1.1.6.1">
<h4><span class="header-section-number">1.1.6.1</span> Histograms<a href="intro-stat.html#histograms" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A histogram shows the shape of a univariate distribution. Each bar in the histogram represents a group of values (a <em>bin</em>). The height of the bar represents the either the frequency of or the percent of values in the bin. The width and number of bins is determined automatically, but the user can adjust them to see more or less detail in the histogram. Figure <a href="intro-stat.html#fig:histogram">1.2</a> demonstrated a histogram of sale price. Sometimes it’s nice to overlay a continuous approximation to the underlying distribution using a <em>kernal density estimator</em> with the <code>geom_density</code> plot, demonstrated in Figure <a href="intro-stat.html#fig:histwithkernal">1.6</a>.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="intro-stat.html#cb50-1" tabindex="-1"></a><span class="fu">ggplot</span>(ames,<span class="fu">aes</span>(<span class="at">x=</span>Sale_Price<span class="sc">/</span><span class="dv">1000</span>)) <span class="sc">+</span> </span>
<span id="cb50-2"><a href="intro-stat.html#cb50-2" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span> <span class="fu">geom_density</span>( <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb50-3"><a href="intro-stat.html#cb50-3" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Sales Price (Thousands $)&quot;</span>)  </span></code></pre></div>
<pre><code>## Warning: The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.
## ℹ Please use `after_stat(density)` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:histwithkernal"></span>
<img src="bookdownproj_files/figure-html/histwithkernal-1.png" alt="Histogram of Sale_Price with kernal density estimator" width="672" />
<p class="caption">
Figure 1.6: Histogram of Sale_Price with kernal density estimator
</p>
</div>
<p>In our next example, Figure <a href="intro-stat.html#fig:overhistogramAC">1.7</a>, we’ll complicate the previous example by showing <em>two</em> distributions of sale price, one for each level of the binary variable <code>Central_Air</code>, overlaid on the same axes.</p>
<p>We can immediately see that there are many more houses that have central air than do not in this data. It appears as though the two distributions have different locations, with the purple distribution centered at a larger sale price. To normalize that quantity and compare the raw probability densitites, we can change our axes to density as in Figure <a href="intro-stat.html#fig:overhistogramdensityAC">1.8</a>.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="intro-stat.html#cb52-1" tabindex="-1"></a><span class="fu">ggplot</span>(ames,<span class="fu">aes</span>(<span class="at">x=</span>Sale_Price<span class="sc">/</span><span class="dv">1000</span>)) <span class="sc">+</span> </span>
<span id="cb52-2"><a href="intro-stat.html#cb52-2" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">data=</span><span class="fu">subset</span>(ames,Central_Air <span class="sc">==</span> <span class="st">&#39;Y&#39;</span>),<span class="fu">aes</span>(<span class="at">fill=</span>Central_Air), <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb52-3"><a href="intro-stat.html#cb52-3" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">data=</span><span class="fu">subset</span>(ames,Central_Air <span class="sc">==</span> <span class="st">&#39;N&#39;</span>),<span class="fu">aes</span>(<span class="at">fill=</span>Central_Air), <span class="at">alpha  =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb52-4"><a href="intro-stat.html#cb52-4" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Sales Price (Thousands $)&quot;</span>)  <span class="sc">+</span> <span class="fu">scale_fill_manual</span>(<span class="at">name=</span><span class="st">&quot;Central_Air&quot;</span>,<span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;No&quot;</span>,<span class="st">&quot;Yes&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:overhistogramAC"></span>
<img src="bookdownproj_files/figure-html/overhistogramAC-1.png" alt="Histogram: Frequency of Sale_Price for Each value of Central_Air" width="672" />
<p class="caption">
Figure 1.7: Histogram: Frequency of Sale_Price for Each value of Central_Air
</p>
</div>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="intro-stat.html#cb53-1" tabindex="-1"></a><span class="fu">ggplot</span>(ames,<span class="fu">aes</span>(<span class="at">x=</span>Sale_Price<span class="sc">/</span><span class="dv">1000</span>)) <span class="sc">+</span> </span>
<span id="cb53-2"><a href="intro-stat.html#cb53-2" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">data=</span><span class="fu">subset</span>(ames,Central_Air <span class="sc">==</span> <span class="st">&#39;Y&#39;</span>),<span class="fu">aes</span>(<span class="at">y=</span>..density..,<span class="at">fill=</span>Central_Air), <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb53-3"><a href="intro-stat.html#cb53-3" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">data=</span><span class="fu">subset</span>(ames,Central_Air <span class="sc">==</span> <span class="st">&#39;N&#39;</span>),<span class="fu">aes</span>(<span class="at">y=</span>..density..,<span class="at">fill=</span>Central_Air), <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb53-4"><a href="intro-stat.html#cb53-4" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Sales Price (Thousands $)&quot;</span>) </span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:overhistogramdensityAC"></span>
<img src="bookdownproj_files/figure-html/overhistogramdensityAC-1.png" alt="Histogram: Density of Sale_Price for varying qualities of  Central_Air" width="672" />
<p class="caption">
Figure 1.8: Histogram: Density of Sale_Price for varying qualities of Central_Air
</p>
</div>
<p>To ease our differentiation of the histograms even further, we again employ a kernel density estimator as shown in Figure <a href="intro-stat.html#fig:overhistogramdensitykernelAC">1.9</a>. This is an appealing alternative to the histogram for continuous data that is assumed to originate from some smooth underlying distribution.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="intro-stat.html#cb55-1" tabindex="-1"></a><span class="fu">ggplot</span>(ames,<span class="fu">aes</span>(<span class="at">x=</span>Sale_Price<span class="sc">/</span><span class="dv">1000</span>)) <span class="sc">+</span> </span>
<span id="cb55-2"><a href="intro-stat.html#cb55-2" tabindex="-1"></a>    <span class="fu">geom_density</span>(<span class="at">data=</span><span class="fu">subset</span>(ames,Central_Air <span class="sc">==</span> <span class="st">&#39;Y&#39;</span>),<span class="fu">aes</span>(<span class="at">fill=</span>Central_Air), <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb55-3"><a href="intro-stat.html#cb55-3" tabindex="-1"></a>    <span class="fu">geom_density</span>(<span class="at">data=</span><span class="fu">subset</span>(ames,Central_Air <span class="sc">==</span> <span class="st">&#39;N&#39;</span>),<span class="fu">aes</span>(<span class="at">fill=</span>Central_Air), <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb55-4"><a href="intro-stat.html#cb55-4" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Sales Price (Thousands $)&quot;</span>)  </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:overhistogramdensitykernelAC"></span>
<img src="bookdownproj_files/figure-html/overhistogramdensitykernelAC-1.png" alt="Histogram: Density of Sale_Price for varying qualities of Central_Air" width="672" />
<p class="caption">
Figure 1.9: Histogram: Density of Sale_Price for varying qualities of Central_Air
</p>
</div>
</div>
<div id="normal-probability-plots-qq-plots" class="section level4 hasAnchor" number="1.1.6.2">
<h4><span class="header-section-number">1.1.6.2</span> Normal probability plots (QQ Plots)<a href="intro-stat.html#normal-probability-plots-qq-plots" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A <strong>normal probability plot</strong> (or QQ plot) graphs the sorted data values against the values that one would expect if the same number of observations came from a theoretical Normal distribution. The resulting image would look close to a straight line if the data was generated by a Normal distribution. Strong deviations from a straight line indicate that the data distribution is not Normal.</p>
<p>Figure <a href="intro-stat.html#fig:qqplot">1.10</a> shows a QQ plot for <code>Sale_Price</code>, and we can conclude that the variable is not Normally distributed (in fact it is right skewed).</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="intro-stat.html#cb56-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> ames, <span class="fu">aes</span>(<span class="at">sample =</span> Sale_Price<span class="sc">/</span><span class="dv">1000</span>)) <span class="sc">+</span></span>
<span id="cb56-2"><a href="intro-stat.html#cb56-2" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb56-3"><a href="intro-stat.html#cb56-3" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:qqplot"></span>
<img src="bookdownproj_files/figure-html/qqplot-1.png" alt="QQ-Plot: Quantiles of Sale_Price vs. quantiles of a theoretical normal distribution with same mean and standard deviation. Conclusion: Sale_Price is _not_ normally distributed due to a problem with skew." width="672" />
<p class="caption">
Figure 1.10: QQ-Plot: Quantiles of Sale_Price vs. quantiles of a theoretical normal distribution with same mean and standard deviation. Conclusion: Sale_Price is <em>not</em> normally distributed due to a problem with skew.
</p>
</div>
<p>There are two main patterns that we expect to find when examining QQ-plots:</p>
<ol style="list-style-type: decimal">
<li>A quadratic shape, as seen in Figure <a href="intro-stat.html#fig:qqplot">1.10</a>. This pattern indicates a deviation from normality due to skewness to the data.</li>
<li>An S-shape (or cubic shape), as seen in Figure <a href="intro-stat.html#fig:qqplotKurt">1.11</a>. This pattern indicates deviation from normality due to kurtosis.</li>
</ol>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="intro-stat.html#cb57-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">j1 =</span> <span class="fu">rlaplace</span>(<span class="dv">10000</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb57-2"><a href="intro-stat.html#cb57-2" tabindex="-1"></a></span>
<span id="cb57-3"><a href="intro-stat.html#cb57-3" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, <span class="fu">aes</span>(<span class="at">sample=</span>j1)) <span class="sc">+</span></span>
<span id="cb57-4"><a href="intro-stat.html#cb57-4" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb57-5"><a href="intro-stat.html#cb57-5" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:qqplotKurt"></span>
<img src="bookdownproj_files/figure-html/qqplotKurt-1.png" alt="QQ-Plot: Quantiles of the Laplace distribution vs. quantiles of a theoretical normal distribution with same mean and standard deviation. Conclusion: Data is _not_ normally distributed (in fact it is leptokurtic), due to a problem with kurtosis." width="672" />
<p class="caption">
Figure 1.11: QQ-Plot: Quantiles of the Laplace distribution vs. quantiles of a theoretical normal distribution with same mean and standard deviation. Conclusion: Data is <em>not</em> normally distributed (in fact it is leptokurtic), due to a problem with kurtosis.
</p>
</div>
</div>
<div id="box-plots" class="section level4 hasAnchor" number="1.1.6.3">
<h4><span class="header-section-number">1.1.6.3</span> Box Plots<a href="intro-stat.html#box-plots" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Box plots (sometimes called box-and-whisker plots) will not necessarily tell you about the <em>shape</em> of your distribution (for instance a bimodal distribution could have a similar box plot to a unimodal one), but it will give you a sense of the distribution’s location and spread and potential skewness.</p>
<p>Many of us have become familiar with the <em>idea</em> of a box plot, but when pressed for the specific steps to create one, we realize our familiarity fades. The diagram in Figure <a href="intro-stat.html#fig:boxplot">1.12</a> will remind the reader the precise information conveyed by a box plot.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:boxplot"></span>
<img src="img/boxplot.png" alt="Anatomy of a Box Plot." width="936" />
<p class="caption">
Figure 1.12: Anatomy of a Box Plot.
</p>
</div>
<p>Figure <a href="intro-stat.html#fig:rboxplot">1.13</a> shows the boxplot of <code>Sale_Price</code>.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="intro-stat.html#cb58-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> ames, <span class="fu">aes</span>(<span class="at">y =</span> Sale_Price<span class="sc">/</span><span class="dv">1000</span>)) <span class="sc">+</span> </span>
<span id="cb58-2"><a href="intro-stat.html#cb58-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb58-3"><a href="intro-stat.html#cb58-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Sales Price (Thousands $)&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:rboxplot"></span>
<img src="bookdownproj_files/figure-html/rboxplot-1.png" alt="Box Plot of Sales Price" width="672" />
<p class="caption">
Figure 1.13: Box Plot of Sales Price
</p>
</div>
<p>Furthermore, we might want to compare the boxplots of <code>Sale_Price</code> for different levels of a categorical variable, like <code>Central_Air</code> as we did with histograms and densities in Figures <a href="intro-stat.html#fig:overhistogramAC">1.7</a> and <a href="intro-stat.html#fig:overhistogramdensityAC">1.8</a>.</p>
<p>The following code achieves this goal in Figure <a href="intro-stat.html#fig:multiboxplotAC">1.14</a>.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="intro-stat.html#cb59-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> ames, <span class="fu">aes</span>(<span class="at">y =</span> Sale_Price<span class="sc">/</span><span class="dv">1000</span>, <span class="at">x =</span> Central_Air, <span class="at">fill =</span> Central_Air)) <span class="sc">+</span> </span>
<span id="cb59-2"><a href="intro-stat.html#cb59-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb59-3"><a href="intro-stat.html#cb59-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Sales Price (Thousands $)&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Central Air&quot;</span>) <span class="sc">+</span></span>
<span id="cb59-4"><a href="intro-stat.html#cb59-4" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette=</span><span class="st">&quot;Accent&quot;</span>) <span class="sc">+</span> <span class="fu">theme_classic</span>() <span class="sc">+</span> <span class="fu">coord_flip</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:multiboxplotAC"></span>
<img src="bookdownproj_files/figure-html/multiboxplotAC-1.png" alt="Box Plots of Sale_Price for each level of Exter_Qual" width="672" />
<p class="caption">
Figure 1.14: Box Plots of Sale_Price for each level of Exter_Qual
</p>
</div>
</div>
</div>
<div id="python-code" class="section level3 hasAnchor" number="1.1.7">
<h3><span class="header-section-number">1.1.7</span> Python Code<a href="intro-stat.html#python-code" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For all of the Python code throughout the book, you will need to use the following libraries:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb60-1"><a href="intro-stat.html#cb60-1" tabindex="-1"></a></span>
<span id="cb60-2"><a href="intro-stat.html#cb60-2" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span></code></pre></div>
<pre><code>## C:\Users\sjsimmo2\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py:117: UserWarning: Pandas requires version &#39;2.8.4&#39; or newer of &#39;numexpr&#39; (version &#39;2.8.3&#39; currently installed).
##   return _find_and_load(name, import_)
## C:\Users\sjsimmo2\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py:117: UserWarning: Pandas requires version &#39;1.3.6&#39; or newer of &#39;bottleneck&#39; (version &#39;1.3.5&#39; currently installed).
##   return _find_and_load(name, import_)</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb62-1"><a href="intro-stat.html#cb62-1" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb62-2"><a href="intro-stat.html#cb62-2" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> OneHotEncoder</span>
<span id="cb62-3"><a href="intro-stat.html#cb62-3" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb62-4"><a href="intro-stat.html#cb62-4" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb62-5"><a href="intro-stat.html#cb62-5" tabindex="-1"></a><span class="im">from</span> numpy <span class="im">import</span> random</span>
<span id="cb62-6"><a href="intro-stat.html#cb62-6" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sma</span>
<span id="cb62-7"><a href="intro-stat.html#cb62-7" tabindex="-1"></a><span class="im">import</span> statsmodels <span class="im">as</span> sm</span>
<span id="cb62-8"><a href="intro-stat.html#cb62-8" tabindex="-1"></a><span class="im">import</span> pylab <span class="im">as</span> py</span>
<span id="cb62-9"><a href="intro-stat.html#cb62-9" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb62-10"><a href="intro-stat.html#cb62-10" tabindex="-1"></a><span class="im">import</span> scipy <span class="im">as</span> sp</span>
<span id="cb62-11"><a href="intro-stat.html#cb62-11" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb62-12"><a href="intro-stat.html#cb62-12" tabindex="-1"></a><span class="im">import</span> sklearn</span>
<span id="cb62-13"><a href="intro-stat.html#cb62-13" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> Ridge</span>
<span id="cb62-14"><a href="intro-stat.html#cb62-14" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> Lasso</span>
<span id="cb62-15"><a href="intro-stat.html#cb62-15" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> ElasticNet</span>
<span id="cb62-16"><a href="intro-stat.html#cb62-16" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_squared_error</span></code></pre></div>
<p>For one-hot encoding in Python:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb63-1"><a href="intro-stat.html#cb63-1" tabindex="-1"></a></span>
<span id="cb63-2"><a href="intro-stat.html#cb63-2" tabindex="-1"></a>x1<span class="op">=</span>np.repeat([<span class="st">&quot;A&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;C&quot;</span>],<span class="dv">10</span>)</span>
<span id="cb63-3"><a href="intro-stat.html#cb63-3" tabindex="-1"></a>x2<span class="op">=</span>np.repeat([<span class="st">&quot;Z&quot;</span>, <span class="st">&quot;X&quot;</span>, <span class="st">&quot;Y&quot;</span>,<span class="st">&quot;W&quot;</span>,<span class="st">&quot;V&quot;</span>,<span class="st">&quot;U&quot;</span>],<span class="dv">5</span>)</span>
<span id="cb63-4"><a href="intro-stat.html#cb63-4" tabindex="-1"></a>random.seed(<span class="dv">41</span>)</span>
<span id="cb63-5"><a href="intro-stat.html#cb63-5" tabindex="-1"></a>y<span class="op">=</span>np.concatenate([np.random.normal(loc<span class="op">=</span><span class="fl">2.0</span>, scale<span class="op">=</span><span class="fl">1.0</span>, size<span class="op">=</span><span class="dv">10</span>),np.random.normal(loc<span class="op">=</span><span class="fl">1.0</span>, scale<span class="op">=</span><span class="fl">1.0</span>, size<span class="op">=</span><span class="dv">10</span>),np.random.normal(loc<span class="op">=</span><span class="fl">0.0</span>, scale<span class="op">=</span><span class="fl">1.0</span>, size<span class="op">=</span><span class="dv">10</span>)])</span>
<span id="cb63-6"><a href="intro-stat.html#cb63-6" tabindex="-1"></a>array<span class="op">=</span>np.array([x1,x2,y])</span>
<span id="cb63-7"><a href="intro-stat.html#cb63-7" tabindex="-1"></a>array2<span class="op">=</span>np.transpose(array)</span>
<span id="cb63-8"><a href="intro-stat.html#cb63-8" tabindex="-1"></a>column_values<span class="op">=</span>[<span class="st">&quot;x1&quot;</span>,<span class="st">&quot;x2&quot;</span>,<span class="st">&quot;y&quot;</span>]</span>
<span id="cb63-9"><a href="intro-stat.html#cb63-9" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame(data <span class="op">=</span> array2, </span>
<span id="cb63-10"><a href="intro-stat.html#cb63-10" tabindex="-1"></a>                  columns <span class="op">=</span> column_values)</span>
<span id="cb63-11"><a href="intro-stat.html#cb63-11" tabindex="-1"></a><span class="bu">print</span>(df)</span></code></pre></div>
<pre><code>##    x1 x2                      y
## 0   A  Z     1.7292876769326795
## 1   A  Z       2.10484805260974
## 2   A  Z      2.250527815723572
## 3   A  Z     1.0748000347219233
## 4   A  Z      2.567143660285906
## 5   A  X     0.9598197839170619
## 6   A  X     1.8463240485420624
## 7   A  X      2.789851810346819
## 8   A  X     0.7737841535581458
## 9   A  X     1.0519930122865415
## 10  B  Y     0.4303460580699353
## 11  B  Y   0.022849785302227588
## 12  B  Y    0.22936828881644922
## 13  B  Y     0.9662887085465139
## 14  B  Y  -0.032859245166130036
## 15  B  W     2.1424273766831528
## 16  B  W     0.3902219923125273
## 17  B  W       2.46941638687667
## 18  B  W     2.4926788367383335
## 19  B  W     1.7071252278892184
## 20  C  V    -1.8584902566516113
## 21  C  V    -1.3706237711281049
## 22  C  V   -0.33010638792060293
## 23  C  V    -1.5152899458722047
## 24  C  V     1.2000601858215505
## 25  C  U    -1.8226191434208407
## 26  C  U    0.26938454136355156
## 27  C  U   -0.44642437564718757
## 28  C  U     1.1143136000921545
## 29  C  U    -1.3808025981774998</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb65-1"><a href="intro-stat.html#cb65-1" tabindex="-1"></a>one_hot_encoded_data <span class="op">=</span> pd.get_dummies(df, columns <span class="op">=</span> [<span class="st">&#39;x1&#39;</span>, <span class="st">&#39;x2&#39;</span>])</span>
<span id="cb65-2"><a href="intro-stat.html#cb65-2" tabindex="-1"></a><span class="bu">print</span>(one_hot_encoded_data)</span></code></pre></div>
<pre><code>##                         y   x1_A   x1_B   x1_C  ...   x2_W   x2_X   x2_Y   x2_Z
## 0      1.7292876769326795   True  False  False  ...  False  False  False   True
## 1        2.10484805260974   True  False  False  ...  False  False  False   True
## 2       2.250527815723572   True  False  False  ...  False  False  False   True
## 3      1.0748000347219233   True  False  False  ...  False  False  False   True
## 4       2.567143660285906   True  False  False  ...  False  False  False   True
## 5      0.9598197839170619   True  False  False  ...  False   True  False  False
## 6      1.8463240485420624   True  False  False  ...  False   True  False  False
## 7       2.789851810346819   True  False  False  ...  False   True  False  False
## 8      0.7737841535581458   True  False  False  ...  False   True  False  False
## 9      1.0519930122865415   True  False  False  ...  False   True  False  False
## 10     0.4303460580699353  False   True  False  ...  False  False   True  False
## 11   0.022849785302227588  False   True  False  ...  False  False   True  False
## 12    0.22936828881644922  False   True  False  ...  False  False   True  False
## 13     0.9662887085465139  False   True  False  ...  False  False   True  False
## 14  -0.032859245166130036  False   True  False  ...  False  False   True  False
## 15     2.1424273766831528  False   True  False  ...   True  False  False  False
## 16     0.3902219923125273  False   True  False  ...   True  False  False  False
## 17       2.46941638687667  False   True  False  ...   True  False  False  False
## 18     2.4926788367383335  False   True  False  ...   True  False  False  False
## 19     1.7071252278892184  False   True  False  ...   True  False  False  False
## 20    -1.8584902566516113  False  False   True  ...  False  False  False  False
## 21    -1.3706237711281049  False  False   True  ...  False  False  False  False
## 22   -0.33010638792060293  False  False   True  ...  False  False  False  False
## 23    -1.5152899458722047  False  False   True  ...  False  False  False  False
## 24     1.2000601858215505  False  False   True  ...  False  False  False  False
## 25    -1.8226191434208407  False  False   True  ...  False  False  False  False
## 26    0.26938454136355156  False  False   True  ...  False  False  False  False
## 27   -0.44642437564718757  False  False   True  ...  False  False  False  False
## 28     1.1143136000921545  False  False   True  ...  False  False  False  False
## 29    -1.3808025981774998  False  False   True  ...  False  False  False  False
## 
## [30 rows x 10 columns]</code></pre>
<p>Bring the r data set over to Python (if you are writing this in an R Markdown document).</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb67-1"><a href="intro-stat.html#cb67-1" tabindex="-1"></a>ames_py <span class="op">=</span> r.ames</span>
<span id="cb67-2"><a href="intro-stat.html#cb67-2" tabindex="-1"></a>ames_py <span class="op">=</span> pd.DataFrame(ames_py)</span>
<span id="cb67-3"><a href="intro-stat.html#cb67-3" tabindex="-1"></a></span>
<span id="cb67-4"><a href="intro-stat.html#cb67-4" tabindex="-1"></a>ames_py.describe()</span></code></pre></div>
<pre><code>##        Lot_Frontage       Lot_Area  ...    Longitude     Latitude
## count   2930.000000    2930.000000  ...  2930.000000  2930.000000
## mean      57.647782   10147.921843  ...   -93.642897    42.034482
## std       33.499441    7880.017759  ...     0.025700     0.018410
## min        0.000000    1300.000000  ...   -93.693153    41.986498
## 25%       43.000000    7440.250000  ...   -93.660217    42.022088
## 50%       63.000000    9436.500000  ...   -93.641806    42.034662
## 75%       78.000000   11555.250000  ...   -93.622113    42.049853
## max      313.000000  215245.000000  ...   -93.577427    42.063388
## 
## [8 rows x 35 columns]</code></pre>
<p>Creating a frequency bar plot for Heating Quality:</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb69-1"><a href="intro-stat.html#cb69-1" tabindex="-1"></a></span>
<span id="cb69-2"><a href="intro-stat.html#cb69-2" tabindex="-1"></a>ax <span class="op">=</span> sns.countplot(x <span class="op">=</span> <span class="st">&quot;Heating_QC&quot;</span>, data <span class="op">=</span> ames_py, color <span class="op">=</span> <span class="st">&quot;orange&quot;</span>)</span></code></pre></div>
<pre><code>## C:\PROGRA~3\ANACON~1\lib\site-packages\seaborn\categorical.py:253: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
##   grouped_vals = vals.groupby(grouper)</code></pre>
<div class="sourceCode" id="cb71"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb71-1"><a href="intro-stat.html#cb71-1" tabindex="-1"></a>ax.<span class="bu">set</span>(xlabel <span class="op">=</span> <span class="st">&#39;Heating Quality&#39;</span>,</span>
<span id="cb71-2"><a href="intro-stat.html#cb71-2" tabindex="-1"></a>       ylabel <span class="op">=</span> <span class="st">&#39;Frequency&#39;</span>,</span>
<span id="cb71-3"><a href="intro-stat.html#cb71-3" tabindex="-1"></a>       title <span class="op">=</span> <span class="st">&#39;Bar Graph of Heating System&#39;</span>)</span>
<span id="cb71-4"><a href="intro-stat.html#cb71-4" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Creating a table of frequencies for Heating Quality:</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb72-1"><a href="intro-stat.html#cb72-1" tabindex="-1"></a>ames_py[<span class="st">&#39;Heating_QC&#39;</span>].value_counts()</span></code></pre></div>
<pre><code>## Heating_QC
## Excellent    1495
## Typical       864
## Good          476
## Fair           92
## Poor            3
## Name: count, dtype: int64</code></pre>
<p>Creating a frequency histogram of Sales Price:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb74-1"><a href="intro-stat.html#cb74-1" tabindex="-1"></a></span>
<span id="cb74-2"><a href="intro-stat.html#cb74-2" tabindex="-1"></a>sale_prices <span class="op">=</span> ames_py[<span class="st">&#39;Sale_Price&#39;</span>] <span class="op">/</span> <span class="dv">1000</span></span>
<span id="cb74-3"><a href="intro-stat.html#cb74-3" tabindex="-1"></a></span>
<span id="cb74-4"><a href="intro-stat.html#cb74-4" tabindex="-1"></a><span class="co"># Create the histogram</span></span>
<span id="cb74-5"><a href="intro-stat.html#cb74-5" tabindex="-1"></a>plt.hist(sale_prices, bins<span class="op">=</span><span class="dv">30</span>, color<span class="op">=</span><span class="st">&#39;blue&#39;</span>, edgecolor<span class="op">=</span><span class="st">&#39;black&#39;</span>)</span>
<span id="cb74-6"><a href="intro-stat.html#cb74-6" tabindex="-1"></a></span>
<span id="cb74-7"><a href="intro-stat.html#cb74-7" tabindex="-1"></a><span class="co"># Set the labels and title</span></span></code></pre></div>
<pre><code>## (array([  5.,  25., 116., 234., 524., 575., 410., 277., 221., 158., 102.,
##         69.,  66.,  35.,  33.,  23.,  18.,  10.,   9.,   5.,   0.,   6.,
##          0.,   3.,   4.,   0.,   0.,   0.,   0.,   2.]), array([ 12.789     ,  37.52936667,  62.26973333,  87.0101    ,
##        111.75046667, 136.49083333, 161.2312    , 185.97156667,
##        210.71193333, 235.4523    , 260.19266667, 284.93303333,
##        309.6734    , 334.41376667, 359.15413333, 383.8945    ,
##        408.63486667, 433.37523333, 458.1156    , 482.85596667,
##        507.59633333, 532.3367    , 557.07706667, 581.81743333,
##        606.5578    , 631.29816667, 656.03853333, 680.7789    ,
##        705.51926667, 730.25963333, 755.        ]), &lt;BarContainer object of 30 artists&gt;)</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb76-1"><a href="intro-stat.html#cb76-1" tabindex="-1"></a>plt.xlabel(<span class="st">&#39;Sales Price (Thousands $)&#39;</span>)</span>
<span id="cb76-2"><a href="intro-stat.html#cb76-2" tabindex="-1"></a>plt.ylabel(<span class="st">&#39;Frequency&#39;</span>)</span>
<span id="cb76-3"><a href="intro-stat.html#cb76-3" tabindex="-1"></a>plt.title(<span class="st">&#39;Histogram of Sales Price in Thousands of Dollars&#39;</span>)</span>
<span id="cb76-4"><a href="intro-stat.html#cb76-4" tabindex="-1"></a></span>
<span id="cb76-5"><a href="intro-stat.html#cb76-5" tabindex="-1"></a><span class="co"># Display the plot</span></span>
<span id="cb76-6"><a href="intro-stat.html#cb76-6" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-16-3.png" width="672" /></p>
<p>Getting summary statistics by Sales Price and External Quality:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb77-1"><a href="intro-stat.html#cb77-1" tabindex="-1"></a>ames_py[<span class="st">&#39;Sale_Price&#39;</span>].describe()</span></code></pre></div>
<pre><code>## count      2930.000000
## mean     180796.060068
## std       79886.692357
## min       12789.000000
## 25%      129500.000000
## 50%      160000.000000
## 75%      213500.000000
## max      755000.000000
## Name: Sale_Price, dtype: float64</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb79-1"><a href="intro-stat.html#cb79-1" tabindex="-1"></a>ames_py.groupby(<span class="st">&#39;Exter_Qual&#39;</span>)[<span class="st">&#39;Sale_Price&#39;</span>].describe()</span></code></pre></div>
<pre><code>##              count           mean            std  ...       50%       75%       max
## Exter_Qual                                        ...                              
## Poor           0.0            NaN            NaN  ...       NaN       NaN       NaN
## Fair          35.0   89923.742857   38013.502946  ...   85000.0  115750.0  200000.0
## Typical     1799.0  143373.968316   41503.853558  ...  139000.0  163000.0  415000.0
## Good         989.0  230756.384226   70411.143067  ...  219500.0  267300.0  745000.0
## Excellent    107.0  377918.616822  106987.707970  ...  370967.0  442520.5  755000.0
## 
## [5 rows x 8 columns]
## 
## &lt;string&gt;:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.</code></pre>
<p>Overlay a density plot on top of a the Sales Price histogram:</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb81-1"><a href="intro-stat.html#cb81-1" tabindex="-1"></a></span>
<span id="cb81-2"><a href="intro-stat.html#cb81-2" tabindex="-1"></a>x<span class="op">=</span>r.ames[<span class="st">&quot;Sale_Price&quot;</span>]<span class="op">/</span><span class="dv">1000</span></span>
<span id="cb81-3"><a href="intro-stat.html#cb81-3" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> gaussian_kde</span>
<span id="cb81-4"><a href="intro-stat.html#cb81-4" tabindex="-1"></a></span>
<span id="cb81-5"><a href="intro-stat.html#cb81-5" tabindex="-1"></a></span>
<span id="cb81-6"><a href="intro-stat.html#cb81-6" tabindex="-1"></a><span class="co"># Create the histogram</span></span>
<span id="cb81-7"><a href="intro-stat.html#cb81-7" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb81-8"><a href="intro-stat.html#cb81-8" tabindex="-1"></a>ax.hist(x, bins<span class="op">=</span><span class="dv">30</span>, density<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">&#39;blue&#39;</span>, alpha<span class="op">=</span><span class="fl">0.6</span>, edgecolor<span class="op">=</span><span class="st">&#39;black&#39;</span>)</span>
<span id="cb81-9"><a href="intro-stat.html#cb81-9" tabindex="-1"></a></span>
<span id="cb81-10"><a href="intro-stat.html#cb81-10" tabindex="-1"></a><span class="co"># Add a KDE</span></span></code></pre></div>
<pre><code>## (array([6.89757215e-05, 3.44878608e-04, 1.60023674e-03, 3.22806377e-03,
##        7.22865562e-03, 7.93220798e-03, 5.65600917e-03, 3.82125497e-03,
##        3.04872689e-03, 2.17963280e-03, 1.40710472e-03, 9.51864957e-04,
##        9.10479524e-04, 4.82830051e-04, 4.55239762e-04, 3.17288319e-04,
##        2.48312597e-04, 1.37951443e-04, 1.24156299e-04, 6.89757215e-05,
##        0.00000000e+00, 8.27708658e-05, 0.00000000e+00, 4.13854329e-05,
##        5.51805772e-05, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
##        0.00000000e+00, 2.75902886e-05]), array([ 12.789     ,  37.52936667,  62.26973333,  87.0101    ,
##        111.75046667, 136.49083333, 161.2312    , 185.97156667,
##        210.71193333, 235.4523    , 260.19266667, 284.93303333,
##        309.6734    , 334.41376667, 359.15413333, 383.8945    ,
##        408.63486667, 433.37523333, 458.1156    , 482.85596667,
##        507.59633333, 532.3367    , 557.07706667, 581.81743333,
##        606.5578    , 631.29816667, 656.03853333, 680.7789    ,
##        705.51926667, 730.25963333, 755.        ]), &lt;BarContainer object of 30 artists&gt;)</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb83-1"><a href="intro-stat.html#cb83-1" tabindex="-1"></a>kde <span class="op">=</span> gaussian_kde(x)</span>
<span id="cb83-2"><a href="intro-stat.html#cb83-2" tabindex="-1"></a>x_vals <span class="op">=</span> np.linspace(<span class="bu">min</span>(x), <span class="bu">max</span>(x), <span class="dv">1000</span>)</span>
<span id="cb83-3"><a href="intro-stat.html#cb83-3" tabindex="-1"></a>kde_vals <span class="op">=</span> kde(x_vals)</span>
<span id="cb83-4"><a href="intro-stat.html#cb83-4" tabindex="-1"></a>ax.plot(x_vals, kde_vals, color<span class="op">=</span><span class="st">&#39;blue&#39;</span>)</span>
<span id="cb83-5"><a href="intro-stat.html#cb83-5" tabindex="-1"></a></span>
<span id="cb83-6"><a href="intro-stat.html#cb83-6" tabindex="-1"></a><span class="co"># Set labels and title</span></span>
<span id="cb83-7"><a href="intro-stat.html#cb83-7" tabindex="-1"></a>ax.set_xlabel(<span class="st">&#39;Value&#39;</span>)</span>
<span id="cb83-8"><a href="intro-stat.html#cb83-8" tabindex="-1"></a>ax.set_ylabel(<span class="st">&#39;Density&#39;</span>)</span>
<span id="cb83-9"><a href="intro-stat.html#cb83-9" tabindex="-1"></a>ax.set_title(<span class="st">&#39;Histogram with KDE&#39;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-18-5.png" width="672" /></p>
<p>Overlay of density plots (for Sales Price broken down by Central Air):</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb84-1"><a href="intro-stat.html#cb84-1" tabindex="-1"></a></span>
<span id="cb84-2"><a href="intro-stat.html#cb84-2" tabindex="-1"></a>sale_prices <span class="op">=</span> ames_py[<span class="st">&#39;Sale_Price&#39;</span>] <span class="op">/</span> <span class="dv">1000</span></span>
<span id="cb84-3"><a href="intro-stat.html#cb84-3" tabindex="-1"></a>central_air <span class="op">=</span> ames_py[<span class="st">&#39;Central_Air&#39;</span>]</span>
<span id="cb84-4"><a href="intro-stat.html#cb84-4" tabindex="-1"></a></span>
<span id="cb84-5"><a href="intro-stat.html#cb84-5" tabindex="-1"></a><span class="co"># Plotting histograms for each category in &#39;Central_Air&#39;</span></span>
<span id="cb84-6"><a href="intro-stat.html#cb84-6" tabindex="-1"></a>unique_categories <span class="op">=</span> central_air.unique()</span>
<span id="cb84-7"><a href="intro-stat.html#cb84-7" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">&#39;blue&#39;</span>, <span class="st">&#39;orange&#39;</span>]  <span class="co"># Define colors for each category</span></span>
<span id="cb84-8"><a href="intro-stat.html#cb84-8" tabindex="-1"></a></span>
<span id="cb84-9"><a href="intro-stat.html#cb84-9" tabindex="-1"></a><span class="cf">for</span> category, color <span class="kw">in</span> <span class="bu">zip</span>(unique_categories, colors):</span>
<span id="cb84-10"><a href="intro-stat.html#cb84-10" tabindex="-1"></a>    subset <span class="op">=</span> sale_prices[central_air <span class="op">==</span> category]</span>
<span id="cb84-11"><a href="intro-stat.html#cb84-11" tabindex="-1"></a>    plt.hist(subset, bins<span class="op">=</span><span class="dv">30</span>, alpha<span class="op">=</span><span class="fl">0.6</span>, color<span class="op">=</span>color, label<span class="op">=</span><span class="ss">f&#39;Central Air: </span><span class="sc">{</span>category<span class="sc">}</span><span class="ss">&#39;</span>, edgecolor<span class="op">=</span><span class="st">&#39;black&#39;</span>)</span>
<span id="cb84-12"><a href="intro-stat.html#cb84-12" tabindex="-1"></a></span>
<span id="cb84-13"><a href="intro-stat.html#cb84-13" tabindex="-1"></a><span class="co"># Set the labels and title</span></span></code></pre></div>
<pre><code>## (array([ 19.,  96., 281., 525., 459., 393., 243., 189., 148.,  98.,  67.,
##         63.,  37.,  31.,  23.,  21.,   8.,  10.,   5.,   3.,   2.,   4.,
##          2.,   3.,   2.,   0.,   0.,   0.,   0.,   2.]), array([ 50. ,  73.5,  97. , 120.5, 144. , 167.5, 191. , 214.5, 238. ,
##        261.5, 285. , 308.5, 332. , 355.5, 379. , 402.5, 426. , 449.5,
##        473. , 496.5, 520. , 543.5, 567. , 590.5, 614. , 637.5, 661. ,
##        684.5, 708. , 731.5, 755. ]), &lt;BarContainer object of 30 artists&gt;)
## (array([ 2.,  0.,  4.,  5.,  2., 13.,  9., 15., 23., 21., 19., 20., 13.,
##        15., 11.,  9.,  3.,  4.,  1.,  0.,  1.,  0.,  2.,  2.,  0.,  0.,
##         1.,  0.,  0.,  1.]), array([ 12.789     ,  21.22866667,  29.66833333,  38.108     ,
##         46.54766667,  54.98733333,  63.427     ,  71.86666667,
##         80.30633333,  88.746     ,  97.18566667, 105.62533333,
##        114.065     , 122.50466667, 130.94433333, 139.384     ,
##        147.82366667, 156.26333333, 164.703     , 173.14266667,
##        181.58233333, 190.022     , 198.46166667, 206.90133333,
##        215.341     , 223.78066667, 232.22033333, 240.66      ,
##        249.09966667, 257.53933333, 265.979     ]), &lt;BarContainer object of 30 artists&gt;)</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb86-1"><a href="intro-stat.html#cb86-1" tabindex="-1"></a>plt.xlabel(<span class="st">&#39;Sales Price (Thousands $)&#39;</span>)</span>
<span id="cb86-2"><a href="intro-stat.html#cb86-2" tabindex="-1"></a>plt.ylabel(<span class="st">&#39;Frequency&#39;</span>)</span>
<span id="cb86-3"><a href="intro-stat.html#cb86-3" tabindex="-1"></a>plt.legend()</span>
<span id="cb86-4"><a href="intro-stat.html#cb86-4" tabindex="-1"></a>plt.title(<span class="st">&#39;Histogram of Sales Price in Thousands of Dollars&#39;</span>)</span>
<span id="cb86-5"><a href="intro-stat.html#cb86-5" tabindex="-1"></a></span>
<span id="cb86-6"><a href="intro-stat.html#cb86-6" tabindex="-1"></a><span class="co"># Display the plot</span></span>
<span id="cb86-7"><a href="intro-stat.html#cb86-7" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-19-7.png" width="672" /></p>
<div class="sourceCode" id="cb87"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb87-1"><a href="intro-stat.html#cb87-1" tabindex="-1"></a></span>
<span id="cb87-2"><a href="intro-stat.html#cb87-2" tabindex="-1"></a><span class="co"># Get unique categories in &#39;Central_Air&#39;</span></span>
<span id="cb87-3"><a href="intro-stat.html#cb87-3" tabindex="-1"></a>unique_categories <span class="op">=</span> central_air.unique()</span>
<span id="cb87-4"><a href="intro-stat.html#cb87-4" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">&#39;blue&#39;</span>, <span class="st">&#39;orange&#39;</span>]  <span class="co"># Define colors for each category</span></span>
<span id="cb87-5"><a href="intro-stat.html#cb87-5" tabindex="-1"></a></span>
<span id="cb87-6"><a href="intro-stat.html#cb87-6" tabindex="-1"></a><span class="co"># Create a figure and axis</span></span>
<span id="cb87-7"><a href="intro-stat.html#cb87-7" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb87-8"><a href="intro-stat.html#cb87-8" tabindex="-1"></a></span>
<span id="cb87-9"><a href="intro-stat.html#cb87-9" tabindex="-1"></a><span class="co"># Plot KDE for each category</span></span>
<span id="cb87-10"><a href="intro-stat.html#cb87-10" tabindex="-1"></a><span class="cf">for</span> category, color <span class="kw">in</span> <span class="bu">zip</span>(unique_categories, colors):</span>
<span id="cb87-11"><a href="intro-stat.html#cb87-11" tabindex="-1"></a>    subset <span class="op">=</span> sale_prices[central_air <span class="op">==</span> category]</span>
<span id="cb87-12"><a href="intro-stat.html#cb87-12" tabindex="-1"></a>    kde <span class="op">=</span> gaussian_kde(subset, bw_method<span class="op">=</span><span class="st">&#39;scott&#39;</span>)</span>
<span id="cb87-13"><a href="intro-stat.html#cb87-13" tabindex="-1"></a>    x_vals <span class="op">=</span> np.linspace(subset.<span class="bu">min</span>(), subset.<span class="bu">max</span>(), <span class="dv">1000</span>)</span>
<span id="cb87-14"><a href="intro-stat.html#cb87-14" tabindex="-1"></a>    kde_vals <span class="op">=</span> kde(x_vals)</span>
<span id="cb87-15"><a href="intro-stat.html#cb87-15" tabindex="-1"></a>    ax.fill_between(x_vals, kde_vals, alpha<span class="op">=</span><span class="fl">0.6</span>, color<span class="op">=</span>color, label<span class="op">=</span><span class="ss">f&#39;Central Air: </span><span class="sc">{</span>category<span class="sc">}</span><span class="ss">&#39;</span>)</span>
<span id="cb87-16"><a href="intro-stat.html#cb87-16" tabindex="-1"></a></span>
<span id="cb87-17"><a href="intro-stat.html#cb87-17" tabindex="-1"></a><span class="co"># Set the labels and title</span></span>
<span id="cb87-18"><a href="intro-stat.html#cb87-18" tabindex="-1"></a>ax.set_xlabel(<span class="st">&#39;Sales Price (Thousands $)&#39;</span>)</span>
<span id="cb87-19"><a href="intro-stat.html#cb87-19" tabindex="-1"></a>ax.set_ylabel(<span class="st">&#39;Density&#39;</span>)</span>
<span id="cb87-20"><a href="intro-stat.html#cb87-20" tabindex="-1"></a>ax.set_title(<span class="st">&#39;KDE of Sales Price in Thousands of Dollars&#39;</span>)</span>
<span id="cb87-21"><a href="intro-stat.html#cb87-21" tabindex="-1"></a>ax.legend()</span>
<span id="cb87-22"><a href="intro-stat.html#cb87-22" tabindex="-1"></a></span>
<span id="cb87-23"><a href="intro-stat.html#cb87-23" tabindex="-1"></a><span class="co"># Display the plot</span></span>
<span id="cb87-24"><a href="intro-stat.html#cb87-24" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-20-9.png" width="672" /></p>
<p>QQ plots:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb88-1"><a href="intro-stat.html#cb88-1" tabindex="-1"></a>sma.qqplot(ames_py[<span class="st">&#39;Sale_Price&#39;</span>]<span class="op">/</span><span class="dv">1000</span>, line<span class="op">=</span><span class="st">&#39;45&#39;</span>,fit<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb88-2"><a href="intro-stat.html#cb88-2" tabindex="-1"></a>py.show()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-21-11.png" width="672" /></p>
<p>Boxplots:</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb89-1"><a href="intro-stat.html#cb89-1" tabindex="-1"></a></span>
<span id="cb89-2"><a href="intro-stat.html#cb89-2" tabindex="-1"></a><span class="co"># Create the boxplot</span></span>
<span id="cb89-3"><a href="intro-stat.html#cb89-3" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb89-4"><a href="intro-stat.html#cb89-4" tabindex="-1"></a>ax.boxplot(sale_prices, vert<span class="op">=</span><span class="va">False</span>, patch_artist<span class="op">=</span><span class="va">True</span>, boxprops<span class="op">=</span><span class="bu">dict</span>(facecolor<span class="op">=</span><span class="st">&#39;blue&#39;</span>))</span>
<span id="cb89-5"><a href="intro-stat.html#cb89-5" tabindex="-1"></a></span>
<span id="cb89-6"><a href="intro-stat.html#cb89-6" tabindex="-1"></a><span class="co"># Set the labels and title</span></span></code></pre></div>
<pre><code>## {&#39;whiskers&#39;: [&lt;matplotlib.lines.Line2D object at 0x00000176F6E81100&gt;, &lt;matplotlib.lines.Line2D object at 0x00000176F6E813A0&gt;], &#39;caps&#39;: [&lt;matplotlib.lines.Line2D object at 0x00000176F6E81640&gt;, &lt;matplotlib.lines.Line2D object at 0x00000176F6E818E0&gt;], &#39;boxes&#39;: [&lt;matplotlib.patches.PathPatch object at 0x00000176F6E74E20&gt;], &#39;medians&#39;: [&lt;matplotlib.lines.Line2D object at 0x00000176F6E81B80&gt;], &#39;fliers&#39;: [&lt;matplotlib.lines.Line2D object at 0x00000176F6E81E20&gt;], &#39;means&#39;: []}</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb91-1"><a href="intro-stat.html#cb91-1" tabindex="-1"></a>ax.set_xlabel(<span class="st">&#39;Sales Price (Thousands $)&#39;</span>)</span>
<span id="cb91-2"><a href="intro-stat.html#cb91-2" tabindex="-1"></a>ax.set_title(<span class="st">&#39;Boxplot of Sales Price in Thousands of Dollars&#39;</span>)</span>
<span id="cb91-3"><a href="intro-stat.html#cb91-3" tabindex="-1"></a></span>
<span id="cb91-4"><a href="intro-stat.html#cb91-4" tabindex="-1"></a><span class="co"># Display the plot</span></span>
<span id="cb91-5"><a href="intro-stat.html#cb91-5" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-22-13.png" width="672" /></p>
<div class="sourceCode" id="cb92"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb92-1"><a href="intro-stat.html#cb92-1" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb92-2"><a href="intro-stat.html#cb92-2" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb92-3"><a href="intro-stat.html#cb92-3" tabindex="-1"></a></span>
<span id="cb92-4"><a href="intro-stat.html#cb92-4" tabindex="-1"></a><span class="co"># Assuming &#39;ames_py&#39; is your DataFrame containing the &#39;Central_Air&#39; and &#39;Sale_Price&#39; columns</span></span>
<span id="cb92-5"><a href="intro-stat.html#cb92-5" tabindex="-1"></a><span class="co"># Create a list of data to plot</span></span>
<span id="cb92-6"><a href="intro-stat.html#cb92-6" tabindex="-1"></a>data_to_plot <span class="op">=</span> [ames_py[ames_py[<span class="st">&#39;Central_Air&#39;</span>] <span class="op">==</span> category][<span class="st">&#39;Sale_Price&#39;</span>] <span class="cf">for</span> category <span class="kw">in</span> ames_py[<span class="st">&#39;Central_Air&#39;</span>].unique()]</span>
<span id="cb92-7"><a href="intro-stat.html#cb92-7" tabindex="-1"></a></span>
<span id="cb92-8"><a href="intro-stat.html#cb92-8" tabindex="-1"></a><span class="co"># Create the box plot</span></span>
<span id="cb92-9"><a href="intro-stat.html#cb92-9" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb92-10"><a href="intro-stat.html#cb92-10" tabindex="-1"></a>ax.boxplot(data_to_plot, patch_artist<span class="op">=</span><span class="va">True</span>, boxprops<span class="op">=</span><span class="bu">dict</span>(facecolor<span class="op">=</span><span class="st">&#39;blue&#39;</span>))</span>
<span id="cb92-11"><a href="intro-stat.html#cb92-11" tabindex="-1"></a></span>
<span id="cb92-12"><a href="intro-stat.html#cb92-12" tabindex="-1"></a><span class="co"># Set the x-tick labels</span></span></code></pre></div>
<pre><code>## {&#39;whiskers&#39;: [&lt;matplotlib.lines.Line2D object at 0x00000176FD948AF0&gt;, &lt;matplotlib.lines.Line2D object at 0x00000176802720D0&gt;, &lt;matplotlib.lines.Line2D object at 0x0000017680280040&gt;, &lt;matplotlib.lines.Line2D object at 0x00000176802802E0&gt;], &#39;caps&#39;: [&lt;matplotlib.lines.Line2D object at 0x0000017680272370&gt;, &lt;matplotlib.lines.Line2D object at 0x0000017680272610&gt;, &lt;matplotlib.lines.Line2D object at 0x0000017680280580&gt;, &lt;matplotlib.lines.Line2D object at 0x0000017680280820&gt;], &#39;boxes&#39;: [&lt;matplotlib.patches.PathPatch object at 0x00000176FD948F40&gt;, &lt;matplotlib.patches.PathPatch object at 0x0000017680272CD0&gt;], &#39;medians&#39;: [&lt;matplotlib.lines.Line2D object at 0x00000176802728B0&gt;, &lt;matplotlib.lines.Line2D object at 0x0000017680280AC0&gt;], &#39;fliers&#39;: [&lt;matplotlib.lines.Line2D object at 0x0000017680272B50&gt;, &lt;matplotlib.lines.Line2D object at 0x0000017680280D60&gt;], &#39;means&#39;: []}</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb94-1"><a href="intro-stat.html#cb94-1" tabindex="-1"></a>ax.set_xticklabels(ames_py[<span class="st">&#39;Central_Air&#39;</span>].unique())</span>
<span id="cb94-2"><a href="intro-stat.html#cb94-2" tabindex="-1"></a></span>
<span id="cb94-3"><a href="intro-stat.html#cb94-3" tabindex="-1"></a><span class="co"># Set the labels and title</span></span>
<span id="cb94-4"><a href="intro-stat.html#cb94-4" tabindex="-1"></a>ax.set_xlabel(<span class="st">&#39;Central Air&#39;</span>)</span>
<span id="cb94-5"><a href="intro-stat.html#cb94-5" tabindex="-1"></a>ax.set_ylabel(<span class="st">&#39;Sale Price&#39;</span>)</span>
<span id="cb94-6"><a href="intro-stat.html#cb94-6" tabindex="-1"></a>ax.set_title(<span class="st">&#39;Boxplot of Sale Price by Central Air&#39;</span>)</span>
<span id="cb94-7"><a href="intro-stat.html#cb94-7" tabindex="-1"></a></span>
<span id="cb94-8"><a href="intro-stat.html#cb94-8" tabindex="-1"></a><span class="co"># Display the plot</span></span>
<span id="cb94-9"><a href="intro-stat.html#cb94-9" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-23-15.png" width="672" /></p>
</div>
</div>
<div id="pointest" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Point Estimates<a href="intro-stat.html#pointest" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>All the statistics discussed so far have been <em>point estimates</em>. They are our <em>best</em> estimate at what the population parameter might be, but since we’ve taken a random sample of data from that population, there must be some uncertainty surrounding that estimate. In statistics, our real interest lies in drawing inferences about an entire population (which we couldn’t possibly observe due to time, cost, and/or feasibility constraints) and our approach is to take a representative sample and try to understand what it might tell us about the population.</p>
<p>For the remainder of this text, we will assume our sample is representative of the population. Let’s review some common statistical notation of <em>population parameters</em> (the true values we are usually unable to observe) and <em>sample statistics</em> (those values we calculate based on our sample)</p>
<table>
<colgroup>
<col width="56%" />
<col width="43%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Population Parmeter</th>
<th align="center">Sample Statistic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Mean (<span class="math inline">\(\mu\)</span>)</td>
<td align="center">Sample Average(<span class="math inline">\(\bar{x}\)</span>)</td>
</tr>
<tr class="even">
<td align="center">Variance (<span class="math inline">\(\sigma^{2}\)</span>)</td>
<td align="center">Sample Variance(<span class="math inline">\(s^{2}_{x}\)</span>)</td>
</tr>
<tr class="odd">
<td align="center">Standard deviation (<span class="math inline">\(\sigma^{2}\)</span>)</td>
<td align="center">Sample standard deviation(<span class="math inline">\(s_{x}\)</span>)</td>
</tr>
</tbody>
</table>
<p>Calculating point estimates should lead us to a natural question, one that embodies the field of statistics which aims to quantify uncertainty: <em>What’s the margin of error for this estimate? </em>
This will be the subject of interest in the next section.</p>
</div>
<div id="ci" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Confidence Intervals<a href="intro-stat.html#ci" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s imagine that we want to calculate the average gas mileage of American cars on the road today in order to analyze the country’s carbon footprint. It should be clear to the reader that the calculation of the <em>population mean</em> would not be possible. The best we could do is take a large representative sample and calculate the sample average. Again, the next question should be: What is the margin of error for this estimate? If our sample average is 21.1 mpg, could the population mean reasonably be 21.2 mpg? how about 25 mpg? 42 mpg?</p>
<p>To answer this question, we reach for the notion of <em>confidence intervals</em>. A <strong>confidence interval</strong> is an interval that we believe contains the population mean with some degree of confidence. A confidence interval is associated with a <em>confidence level</em>, a percentage, which indicates the strength of our confidence that the interval created actually captured the true parameter.</p>
<p>It’s an important nuance to remember that the population mean is a fixed number. The source of randomness in our estimation is our sample. When we construct a 95% confidence interval, we are claiming that, upon repetition of the sampling and interval calculation process, we expect 95% of our created intervals to contain the population mean.</p>
<p>To obtain a confidence interval for a mean in R, we can use the <code>t.test()</code> function, as shown below.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="intro-stat.html#cb95-1" tabindex="-1"></a><span class="fu">t.test</span>(ames<span class="sc">$</span>Sale_Price, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  ames$Sale_Price
## t = 122.5, df = 2929, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  177902.3 183689.9
## sample estimates:
## mean of x 
##  180796.1</code></pre>
<p>We can gather based on the output that our 95% confidence interval for the mean of <code>Sale_Price</code> is [177902.3, 183689.9]. This function also outputs some extra information that relates to hypothesis testing which we will discuss in Section <a href="intro-stat.html#hypotest">1.4</a>. For now, if we only want to pull the output containing the confidence interval information, we can specify <code>$conf.int</code> to the object output from <code>t.test</code>:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="intro-stat.html#cb97-1" tabindex="-1"></a><span class="fu">t.test</span>(ames<span class="sc">$</span>Sale_Price, <span class="at">conf.level =</span> <span class="fl">0.95</span>)<span class="sc">$</span>conf.int</span></code></pre></div>
<pre><code>## [1] 177902.3 183689.9
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<p>To learn the labels of the various pieces of output, you can list them with the <code>ls()</code> function, or by saving the output as an object (below, <code>results</code> is the object that stores the output) and exploring it in your environment (upper right panel in RStudio):</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="intro-stat.html#cb99-1" tabindex="-1"></a><span class="fu">ls</span>(<span class="fu">t.test</span>(ames<span class="sc">$</span>Sale_Price, <span class="at">conf.level =</span> <span class="fl">0.95</span>))</span></code></pre></div>
<pre><code>##  [1] &quot;alternative&quot; &quot;conf.int&quot;    &quot;data.name&quot;   &quot;estimate&quot;    &quot;method&quot;     
##  [6] &quot;null.value&quot;  &quot;p.value&quot;     &quot;parameter&quot;   &quot;statistic&quot;   &quot;stderr&quot;</code></pre>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="intro-stat.html#cb101-1" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">t.test</span>(ames<span class="sc">$</span>Sale_Price, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<div id="python-code-1" class="section level3 hasAnchor" number="1.3.1">
<h3><span class="header-section-number">1.3.1</span> Python Code<a href="intro-stat.html#python-code-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Confidence intervals:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb102-1"><a href="intro-stat.html#cb102-1" tabindex="-1"></a>d <span class="op">=</span> sm.stats.weightstats.DescrStatsW(ames_py[<span class="st">&#39;Sale_Price&#39;</span>])</span>
<span id="cb102-2"><a href="intro-stat.html#cb102-2" tabindex="-1"></a>d.tconfint_mean(<span class="fl">0.05</span>)</span></code></pre></div>
<pre><code>## (177902.26200144587, 183689.85813507292)</code></pre>
</div>
</div>
<div id="hypotest" class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> Hypothesis Testing<a href="intro-stat.html#hypotest" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A confidence interval can help us test a hypothesis about the population mean. A <strong>hypothesis</strong> is merely a statement that we wish to investigate scientifically through the process of statistical inference. In Section <a href="intro-stat.html#ci">1.3</a> we proposed some potential hypotheses in the form of questions: If the sample average gas mileage is 21.1, is it possible that the population mean is 21.2? How about 42? The statistical <strong>hypothesis test</strong> can help us answer these questions.</p>
<p>To conduct a hypothesis test, we make an initial assumption. This initial assumption is called the <strong>null hypothesis</strong> and typically denoted as <span class="math inline">\(H_0\)</span>. We then analyze the data and determine whether our observations are likely, given our assumption of the null hypothesis. If we determine that our observed data was unlikely <em>enough</em> (beyond some threshold that we set before hand - or beyond a “reasonable doubt” in the justice system) then we <em>reject</em> our initial assumption in favor of the opposite statement, known as the <strong>alternative hypothesis</strong> denoted <span class="math inline">\(H_a\)</span>. The threshold or <strong>significance level</strong> that we use to determine how much evidence is required to reject the null hypothesis is a proportion, <span class="math inline">\(\alpha\)</span>, which specifies how often we’re willing to incorrectly reject the null hypothesis (this means that we are assuming the null hypothesis is true). Remember, in applied statistics there are no proofs. Every decision we make comes with some degree of uncertainty. <span class="math inline">\(\alpha\)</span> quantifies our allowance for that uncertainty. In statistical textbooks of years past, <span class="math inline">\(\alpha = 0.05\)</span> was the norm. Later in this text we will propose much smaller values for <span class="math inline">\(\alpha\)</span> depending on your sample size.</p>
<p>In order to quantify how unlikely it was that we observed a statistic as extreme or more extreme than we did, we calculate a <strong>p-value</strong>. The p-value is the area under the <strong>null distribution</strong> that represents the probability that we observed something as extreme or more extreme than we did (assuming the truth of the null hypothesis). If our p-value is less than our confidence level, <span class="math inline">\(\alpha\)</span>, we have enough evidence to reject the null hypothesis in favor of the alternative.</p>
<p><strong>Example</strong></p>
<p>Suppose now we obtain a new coin from a friend and our hypothesis is that it “feels unfair”. We decide that we want a conservative signficance level of 0.01 before we accuse our friend of cheating, so we conduct a hypothesis test. Our null hypothesis must generate a known distribution to which we can compare. Thus our null hypothesis is that the coin is fair:
<span class="math display">\[H_0 = \text{The coin is fair:}\quad P(Heads) = 0.5\]</span>
Our alternative hypothesis is the opposite of this:
<span class="math display">\[H_0 = \text{The coin is not fair:}\quad P(Heads) \neq 0.5\]</span>
Suppose we flip the coin 100 times and count 65 heads. How likely is it that we would have obtained a result as extreme or more extreme than this if the coin was fair? Here we introduce the notion of a <strong>two-tailed hypothesis test</strong>. Since our hypothesis is that the coin is simply unfair, we want to know how likely it is that we obtained a result <em>so different from 50</em>. This is quantified by the <em>absolute</em> difference between what we observed and what we expected. Thus, when considering our null distribution, we want to look at the probability we’d obtain something greater than or equal to 65 (<span class="math inline">\(=50+15\)</span>) heads, <em>or</em> less than or equal to 35 (<span class="math inline">\(=50-15\)</span>) heads.</p>
<div id="onesample" class="section level3 hasAnchor" number="1.4.1">
<h3><span class="header-section-number">1.4.1</span> One-Sample T-Test<a href="intro-stat.html#onesample" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If we want to test whether the mean of continuous variable is equal to hypothesized value, we can use the <code>t.test()</code> function. The following code tests whether the average sale price of homes from Ames, Iowa over the data time period is $178,000. For now, we’ll use the classic <span class="math inline">\(\alpha=0.05\)</span> as our significance level. If we have enough evidence to reject this null hypothesis, we will conclude that the mean sale price is significantly different than $178,000 for a two-tailed test (the default):</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="intro-stat.html#cb104-1" tabindex="-1"></a><span class="fu">t.test</span>(ames<span class="sc">$</span>Sale_Price, <span class="at">mu =</span> <span class="dv">178000</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  ames$Sale_Price
## t = 1.8945, df = 2929, p-value = 0.05825
## alternative hypothesis: true mean is not equal to 178000
## 95 percent confidence interval:
##  177902.3 183689.9
## sample estimates:
## mean of x 
##  180796.1</code></pre>
<p>Because our <em>p-value is greater than our alpha</em> level of 0.05, we <em>fail to reject</em> the null hypothesis. We do not quite have sufficient evidence to say the mean is different from 178,000.</p>
<p>If we’re instead interested in testing whether the <code>Sale_Price</code> is <em>higher</em> than $178,000, we can specify this in the <code>alternative=</code> option.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="intro-stat.html#cb106-1" tabindex="-1"></a><span class="fu">t.test</span>(ames<span class="sc">$</span>Sale_Price, <span class="at">mu =</span> <span class="dv">178000</span>, <span class="at">alternative =</span> <span class="st">&#39;greater&#39;</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  ames$Sale_Price
## t = 1.8945, df = 2929, p-value = 0.02913
## alternative hypothesis: true mean is greater than 178000
## 95 percent confidence interval:
##  178367.7      Inf
## sample estimates:
## mean of x 
##  180796.1</code></pre>
<p>In this second test, we see that we actually <em>do have enough evidence</em> to claim that the true mean is greater than $178,000 at the <span class="math inline">\(\alpha=0.05\)</span> level.</p>
</div>
<div id="python-code-2" class="section level3 hasAnchor" number="1.4.2">
<h3><span class="header-section-number">1.4.2</span> Python Code<a href="intro-stat.html#python-code-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Proportion test:</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb108-1"><a href="intro-stat.html#cb108-1" tabindex="-1"></a>count<span class="op">=</span><span class="dv">65</span></span>
<span id="cb108-2"><a href="intro-stat.html#cb108-2" tabindex="-1"></a>nobs<span class="op">=</span><span class="dv">100</span></span>
<span id="cb108-3"><a href="intro-stat.html#cb108-3" tabindex="-1"></a>value<span class="op">=</span><span class="fl">0.5</span></span>
<span id="cb108-4"><a href="intro-stat.html#cb108-4" tabindex="-1"></a>sm.stats.proportion.proportions_ztest(count,nobs,value,alternative<span class="op">=</span><span class="st">&#39;two-sided&#39;</span>,prop_var<span class="op">=</span><span class="fl">0.5</span>)</span></code></pre></div>
<pre><code>## (3.0000000000000004, 0.0026997960632601866)</code></pre>
<p>One sample mean test (two-sided):</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb110-1"><a href="intro-stat.html#cb110-1" tabindex="-1"></a>d <span class="op">=</span> sm.stats.weightstats.DescrStatsW(ames_py[<span class="st">&#39;Sale_Price&#39;</span>])</span>
<span id="cb110-2"><a href="intro-stat.html#cb110-2" tabindex="-1"></a>d.ttest_mean(value <span class="op">=</span> <span class="dv">178000</span>, alternative <span class="op">=</span> <span class="st">&#39;two-sided&#39;</span>)</span></code></pre></div>
<pre><code>## (1.89454911013789, 0.05825057277962961, 2929.0)</code></pre>
<p>One sample mean test (greater than):</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb112-1"><a href="intro-stat.html#cb112-1" tabindex="-1"></a>d <span class="op">=</span> sm.stats.weightstats.DescrStatsW(ames_py[<span class="st">&#39;Sale_Price&#39;</span>])</span>
<span id="cb112-2"><a href="intro-stat.html#cb112-2" tabindex="-1"></a>d.ttest_mean(value <span class="op">=</span> <span class="dv">178000</span>, alternative <span class="op">=</span> <span class="st">&#39;larger&#39;</span>)</span></code></pre></div>
<pre><code>## (1.89454911013789, 0.029125286389814806, 2929.0)</code></pre>
</div>
</div>
<div id="two-sample-t-tests" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> Two-Sample t-tests<a href="intro-stat.html#two-sample-t-tests" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If we have a hypothesis about a difference in the means of two groups of observations, a <strong>two-sample t-test</strong> can tell us whether that difference is statistically significant. By <em>statistically significant</em>, we mean the observed difference in sample means is greater than what we would expect to find if the population means were truly equal. In other words, statistical significance is a phrase that describes when our p-value falls below our significance level, <span class="math inline">\(\alpha\)</span>. Typically, the groups of interest are formed by levels of a binary variable, and the t-test is a way of testing whether there is a relationship between that binary variable and the continuous variable.</p>
<p>To conduct a two-sample t-test, our data should satisfy 2 fundamental assumptions:</p>
<ol style="list-style-type: decimal">
<li>The observations are independent</li>
<li>The data from each group is normally distributed</li>
</ol>
<p>If our data does not satisfy these assumptions, we must adapt our test to the situation. There are two different versions of this test: one in which we assume that the two variances are equal and one that we assume the two variances are not equal (we will do a hypothesis test to determine this). The default is the assumption that the variances are equal, if you decide they are not, you should add the option <code>var.equal=F</code> to the <code>t.test()</code> function to use the Welch or Satterthwaite approximation to degrees of freedom (it’s becoming increasingly common for practitioners to use this option even when variances are equal).</p>
<p>If the <span class="math inline">\(2^{nd}\)</span> assumption is not met, one must opt for a <em>nonparametric</em> test like the Mann-Whitney-U test (also called the Mann–Whitney–Wilcoxon or the Wilcoxon rank-sum test).</p>
<p>The <span class="math inline">\(1^{st}\)</span> assumption is not easily checked unless the data is generated over time (time-series) and is instead generally implied by careful data collect and the application of domain expertise.</p>
<div id="testnorm" class="section level3 hasAnchor" number="1.5.1">
<h3><span class="header-section-number">1.5.1</span> Testing Normality of Groups<a href="intro-stat.html#testnorm" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can test the normality assumption either graphically or through formal statistical tests. The best graphical test of normality is a QQ-Plot, though histograms are often used as well. For this example, we will use the cars data set. This data set shows the MPG for cars made in the US and cars made in Japan:</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="intro-stat.html#cb114-1" tabindex="-1"></a>cars<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/IAA-Faculty/statistical_foundations/master/cars.csv&quot;</span>)</span>
<span id="cb114-2"><a href="intro-stat.html#cb114-2" tabindex="-1"></a></span>
<span id="cb114-3"><a href="intro-stat.html#cb114-3" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> cars, <span class="fu">aes</span>(<span class="at">sample =</span> MPG, <span class="at">color =</span> Country)) <span class="sc">+</span></span>
<span id="cb114-4"><a href="intro-stat.html#cb114-4" tabindex="-1"></a>     <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb114-5"><a href="intro-stat.html#cb114-5" tabindex="-1"></a>     <span class="fu">stat_qq_line</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:qqplotcars"></span>
<img src="bookdownproj_files/figure-html/qqplotcars-1.png" alt="QQ-Plot: Quantiles of MPG vs. quantiles of a theoretical normal distribution with same mean and standard deviation, for each Country. " width="672" />
<p class="caption">
Figure 1.15: QQ-Plot: Quantiles of MPG vs. quantiles of a theoretical normal distribution with same mean and standard deviation, for each Country.
</p>
</div>
<p>For formal tests of normality, we most often use the Shapiro-Wilk test, although many other formal tests exist, each with their own advantages and disadvantages. All of these tests have the null hypothesis of normality:
<span class="math display">\[H_0: \text{ the data is normally distributed}\]</span>
<span class="math display">\[H_a: \text{ the data is NOT normally distributed}\]</span>
We conduct formal tests as follows:</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="intro-stat.html#cb115-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(cars<span class="sc">$</span>MPG[cars<span class="sc">$</span>Country<span class="sc">==</span><span class="st">&#39;US&#39;</span>])</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  cars$MPG[cars$Country == &quot;US&quot;]
## W = 0.98874, p-value = 0.04918</code></pre>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="intro-stat.html#cb117-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(cars<span class="sc">$</span>MPG[cars<span class="sc">$</span>Country<span class="sc">==</span><span class="st">&#39;Japanese&#39;</span>])</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  cars$MPG[cars$Country == &quot;Japanese&quot;]
## W = 0.97676, p-value = 0.1586</code></pre>
<p>Through visual inspection and hypothesis test, we can conclude that there are no significant departures from Normality.</p>
<p>We will discuss and illustrate an example later in which Normality does not hold (in this case, we will need to use a non-parametric <a href="intro-stat.html#wilcoxon">1.5.5</a>.</p>
</div>
<div id="ftest" class="section level3 hasAnchor" number="1.5.2">
<h3><span class="header-section-number">1.5.2</span> Testing Equality of Variances<a href="intro-stat.html#ftest" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can conduct a formal test to figure out which test we should use for the means. This test for equal variances is known as an F-Test. The null hypothesis is that the variances are equal, the alternative being that they are not:
<span class="math display">\[H_0: \sigma_1^2 = \sigma_2^2\]</span>
<span class="math display">\[H_a: \sigma_1^2 \neq \sigma_2^2\]</span></p>
<p>The F-Test is invoked with the <code>var.test</code> function, which takes as input a <code>formula</code>. A formula is an R object most often created using the <code>~</code> operator, for example <code>y ~ x + z</code>, interpreted as a specification that the response <code>y</code> is to be predicted with the inputs <code>x</code> and <code>z</code>. For our present discussion on two-sample t-tests, we might think of predicting our continuous attribute with our binary attribute.</p>
<p>The following code checks whether the distributions of MPG within each country have the same variance.</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="intro-stat.html#cb119-1" tabindex="-1"></a><span class="fu">var.test</span>(MPG<span class="sc">~</span>Country,<span class="at">data=</span>cars)</span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  MPG by Country
## F = 1.3949, num df = 78, denom df = 248, p-value = 0.05848
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.9882466 2.0380519
## sample estimates:
## ratio of variances 
##           1.394915</code></pre>
<p>The results from this test are very close to the level of significance. In this instance, I am going to opt for the <code>var.equal=FALSE</code> option in the <code>t.test()</code> procedure.</p>
</div>
<div id="tsttest" class="section level3 hasAnchor" number="1.5.3">
<h3><span class="header-section-number">1.5.3</span> Testing Equality of Means<a href="intro-stat.html#tsttest" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The two-sample t-test is performed by including a binary grouping variable along with the variable of interest into the <code>t.test()</code> function. Below we test whether the mean MPG is the same for cars made in the US versus cars made in Japan, and we include the <code>var.equal=FALSE</code>. The null hypothesis for the t-test is that the means of the two groups are equal:
<span class="math display">\[H_0: \mu_1 = \mu_2\]</span>
and the alternative hypothesis is <span class="math display">\[H_a: \mu_1 \neq \mu_2\]</span></p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="intro-stat.html#cb121-1" tabindex="-1"></a><span class="fu">t.test</span>(MPG<span class="sc">~</span>Country, <span class="at">data=</span>cars, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  MPG by Country
## t = 13.551, df = 115.64, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means between group Japanese and group US is not equal to 0
## 95 percent confidence interval:
##   8.808417 11.824291
## sample estimates:
## mean in group Japanese       mean in group US 
##               30.48101               20.16466</code></pre>
<p>Our final conclusion from the t-test is the <em>rejection of the null hypothesis</em> and the conclusion that <em>cars made in the US versus cars made in Japan have significantly different MPG. </em></p>
</div>
<div id="python-code-3" class="section level3 hasAnchor" number="1.5.4">
<h3><span class="header-section-number">1.5.4</span> Python Code<a href="intro-stat.html#python-code-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For testing the cars data set:</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb123-1"><a href="intro-stat.html#cb123-1" tabindex="-1"></a>py_cars <span class="op">=</span> r.cars</span>
<span id="cb123-2"><a href="intro-stat.html#cb123-2" tabindex="-1"></a>US <span class="op">=</span> py_cars[py_cars[<span class="st">&quot;Country&quot;</span>]<span class="op">==</span><span class="st">&quot;US&quot;</span>]</span>
<span id="cb123-3"><a href="intro-stat.html#cb123-3" tabindex="-1"></a>sma.qqplot(US[<span class="st">&quot;MPG&quot;</span>], line<span class="op">=</span><span class="st">&#39;45&#39;</span>,fit<span class="op">=</span><span class="va">True</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<div class="sourceCode" id="cb124"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb124-1"><a href="intro-stat.html#cb124-1" tabindex="-1"></a>Jap <span class="op">=</span> py_cars[py_cars[<span class="st">&quot;Country&quot;</span>]<span class="op">==</span><span class="st">&quot;Japanese&quot;</span>]</span>
<span id="cb124-2"><a href="intro-stat.html#cb124-2" tabindex="-1"></a>sma.qqplot(Jap[<span class="st">&quot;MPG&quot;</span>], line<span class="op">=</span><span class="st">&#39;45&#39;</span>,fit<span class="op">=</span><span class="va">True</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-37-3.png" width="672" /></p>
<p>Test for Normality:</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb125-1"><a href="intro-stat.html#cb125-1" tabindex="-1"></a>sma.stats.diagnostic.normal_ad(py_cars[py_cars[<span class="st">&quot;Country&quot;</span>] <span class="op">==</span> <span class="st">&#39;US&#39;</span>][<span class="st">&#39;MPG&#39;</span>])</span></code></pre></div>
<pre><code>## (1.0993725351195565, 0.006880028084693556)</code></pre>
<div class="sourceCode" id="cb127"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb127-1"><a href="intro-stat.html#cb127-1" tabindex="-1"></a>sma.stats.diagnostic.normal_ad(py_cars[py_cars[<span class="st">&quot;Country&quot;</span>] <span class="op">==</span> <span class="st">&#39;Japanese&#39;</span>][<span class="st">&#39;MPG&#39;</span>])</span></code></pre></div>
<pre><code>## (0.7338917066708177, 0.053548986754636846)</code></pre>
<p>Test for equality of variance (need to define a function for the F-test):</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb129-1"><a href="intro-stat.html#cb129-1" tabindex="-1"></a>US<span class="op">=</span>py_cars[py_cars[<span class="st">&quot;Country&quot;</span>]<span class="op">==</span><span class="st">&quot;US&quot;</span>]</span>
<span id="cb129-2"><a href="intro-stat.html#cb129-2" tabindex="-1"></a>Jap<span class="op">=</span>py_cars[py_cars[<span class="st">&quot;Country&quot;</span>]<span class="op">==</span><span class="st">&quot;Japanese&quot;</span>]</span>
<span id="cb129-3"><a href="intro-stat.html#cb129-3" tabindex="-1"></a></span>
<span id="cb129-4"><a href="intro-stat.html#cb129-4" tabindex="-1"></a>np.var(US[<span class="st">&quot;MPG&quot;</span>],ddof<span class="op">=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 26.742939499935222</code></pre>
<div class="sourceCode" id="cb131"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb131-1"><a href="intro-stat.html#cb131-1" tabindex="-1"></a>np.var(Jap[<span class="st">&quot;MPG&quot;</span>],ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb131-2"><a href="intro-stat.html#cb131-2" tabindex="-1"></a></span>
<span id="cb131-3"><a href="intro-stat.html#cb131-3" tabindex="-1"></a><span class="co">#define F-test function</span></span></code></pre></div>
<pre><code>## 37.30412203829925</code></pre>
<div class="sourceCode" id="cb133"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb133-1"><a href="intro-stat.html#cb133-1" tabindex="-1"></a><span class="kw">def</span> f_test(x, y):</span>
<span id="cb133-2"><a href="intro-stat.html#cb133-2" tabindex="-1"></a>    x <span class="op">=</span> np.array(x)</span>
<span id="cb133-3"><a href="intro-stat.html#cb133-3" tabindex="-1"></a>    y <span class="op">=</span> np.array(y)</span>
<span id="cb133-4"><a href="intro-stat.html#cb133-4" tabindex="-1"></a>    f <span class="op">=</span> np.var(x, ddof<span class="op">=</span><span class="dv">1</span>)<span class="op">/</span>np.var(y, ddof<span class="op">=</span><span class="dv">1</span>) <span class="co">#calculate F test statistic </span></span>
<span id="cb133-5"><a href="intro-stat.html#cb133-5" tabindex="-1"></a>    dfn <span class="op">=</span> x.size<span class="op">-</span><span class="dv">1</span> <span class="co">#define degrees of freedom numerator </span></span>
<span id="cb133-6"><a href="intro-stat.html#cb133-6" tabindex="-1"></a>    dfd <span class="op">=</span> y.size<span class="op">-</span><span class="dv">1</span> <span class="co">#define degrees of freedom denominator </span></span>
<span id="cb133-7"><a href="intro-stat.html#cb133-7" tabindex="-1"></a>    p <span class="op">=</span> <span class="dv">1</span><span class="op">-</span>stats.f.cdf(f, dfn, dfd) <span class="co">#find p-value of F test statistic </span></span>
<span id="cb133-8"><a href="intro-stat.html#cb133-8" tabindex="-1"></a>    <span class="cf">return</span> f, p</span>
<span id="cb133-9"><a href="intro-stat.html#cb133-9" tabindex="-1"></a>  </span>
<span id="cb133-10"><a href="intro-stat.html#cb133-10" tabindex="-1"></a>f_test(US[<span class="st">&quot;MPG&quot;</span>],Jap[<span class="st">&quot;MPG&quot;</span>])</span></code></pre></div>
<pre><code>## (0.7168896636269548, 0.9707618911603813)</code></pre>
<p>Or can do Levene’s test:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb135-1"><a href="intro-stat.html#cb135-1" tabindex="-1"></a>sp.stats.levene(py_cars[py_cars[<span class="st">&quot;Country&quot;</span>] <span class="op">==</span> <span class="st">&#39;US&#39;</span>][<span class="st">&#39;MPG&#39;</span>], py_cars[py_cars[<span class="st">&quot;Country&quot;</span>] <span class="op">==</span> <span class="st">&#39;Japanese&#39;</span>][<span class="st">&#39;MPG&#39;</span>])</span></code></pre></div>
<pre><code>## LeveneResult(statistic=2.698137119235061, pvalue=0.10142974483944626)</code></pre>
<p>T-test for two sample means:</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb137-1"><a href="intro-stat.html#cb137-1" tabindex="-1"></a>sp.stats.ttest_ind(py_cars[py_cars[<span class="st">&quot;Country&quot;</span>] <span class="op">==</span> <span class="st">&#39;US&#39;</span>][<span class="st">&#39;MPG&#39;</span>], py_cars[py_cars[<span class="st">&quot;Country&quot;</span>] <span class="op">==</span> <span class="st">&#39;Japanese&#39;</span>][<span class="st">&#39;MPG&#39;</span>], equal_var <span class="op">=</span> <span class="va">False</span>)</span></code></pre></div>
<pre><code>## TtestResult(statistic=-13.550646343940725, pvalue=1.2512223268375437e-25, df=115.63536911707112)</code></pre>
</div>
<div id="wilcoxon" class="section level3 hasAnchor" number="1.5.5">
<h3><span class="header-section-number">1.5.5</span> Mann-Whitney-Wilcoxon Test<a href="intro-stat.html#wilcoxon" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Looking at Figure <a href="intro-stat.html#fig:qqplotcentralair">1.16</a> we see that the Normality assumption within each level of Central Air does not hold:</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="intro-stat.html#cb139-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> ames, <span class="fu">aes</span>(<span class="at">sample =</span> Sale_Price, <span class="at">color =</span> Central_Air)) <span class="sc">+</span></span>
<span id="cb139-2"><a href="intro-stat.html#cb139-2" tabindex="-1"></a>     <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb139-3"><a href="intro-stat.html#cb139-3" tabindex="-1"></a>     <span class="fu">stat_qq_line</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:qqplotcentralair"></span>
<img src="bookdownproj_files/figure-html/qqplotcentralair-5.png" alt="QQ-Plot: Quantiles of Sales Price vs. quantiles of a theoretical normal distribution with same mean and standard deviation, for each level of Central Air. " width="672" />
<p class="caption">
Figure 1.16: QQ-Plot: Quantiles of Sales Price vs. quantiles of a theoretical normal distribution with same mean and standard deviation, for each level of Central Air.
</p>
</div>
<p>In this situation, the best way to proceed would be with a non-parametric test. The Mann-Whitney-Wilcoxon test is not identical to the t-test in its null and alternative hypotheses, but it aims to answer the same question about an association between the binary attribute and the continuous attribute.</p>
<p>The null and alternative hypotheses for this test are typically defined as follows, so long as the two groups <em>have</em> the same shape:
<span class="math display">\[H_0: \text{ the medians of the two groups are equal }  \]</span>
<span class="math display">\[H_a: \text{ the medians of the two groups are NOT equal }   \]</span>
If those distributions are also symmetric and have similar variance, then Mann-Whitney-Wilcoxon can be interpretted as testing for a difference in means. When the data does not have the same shape, Mann-Whitney-Wilcoxon is a test of <strong>dominance</strong> between distributions. <strong>Distributional dominance</strong> is the notion that one group’s distribution is located at larger values than another, probabilistically speaking. Formally, a random variable A has dominance over random variable B if <span class="math inline">\(P(A x) \geq P(B\geq x)\)</span> for all <span class="math inline">\(x\)</span>, and for some <span class="math inline">\(x\)</span>, <span class="math inline">\(P(A\geq x) &gt; P(B\geq x)\)</span>.</p>
<p>We summarize this information in the following table:</p>
<table style="width:auto; margin-left: auto; margin-right: auto;">
<tr>
<td>
Conditions
<td>
Interpretation of Significant <br> Mann-Whitney-Wilcoxon Test
<tr>
<td>
Group distributions are identical in shape,<br> variance, and symmetric
<td>
Difference in means
<tr>
<td>
Group distributions are identical in shape, but not symmetric
<td>
Difference in medians
<tr>
<td>
Group distributions are not identical in shape,<br> variance, and are not symmetric
<td>
Difference in location. <br> (distributional dominance)
</tr>
</table>
<p>To perform this test, we use the <code>wilcox.test()</code> function, whose inputs are identical to the <code>t.test()</code> function.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="intro-stat.html#cb140-1" tabindex="-1"></a><span class="fu">wilcox.test</span>(Sale_Price <span class="sc">~</span> Central_Air, <span class="at">data =</span> ames)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  Sale_Price by Central_Air
## W = 63164, p-value &lt; 2.2e-16
## alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
<div id="python-code-4" class="section level3 hasAnchor" number="1.5.6">
<h3><span class="header-section-number">1.5.6</span> Python Code<a href="intro-stat.html#python-code-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>QQ plots for those homes with Central Air and without Central Air:</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb142-1"><a href="intro-stat.html#cb142-1" tabindex="-1"></a>yes<span class="op">=</span>r.ames[r.ames[<span class="st">&quot;Central_Air&quot;</span>]<span class="op">==</span><span class="st">&quot;Y&quot;</span>]</span>
<span id="cb142-2"><a href="intro-stat.html#cb142-2" tabindex="-1"></a>sma.qqplot(yes[<span class="st">&quot;Sale_Price&quot;</span>], line<span class="op">=</span><span class="st">&#39;45&#39;</span>,fit<span class="op">=</span><span class="va">True</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<div class="sourceCode" id="cb143"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb143-1"><a href="intro-stat.html#cb143-1" tabindex="-1"></a>no<span class="op">=</span>r.ames[r.ames[<span class="st">&quot;Central_Air&quot;</span>]<span class="op">==</span><span class="st">&quot;N&quot;</span>]</span>
<span id="cb143-2"><a href="intro-stat.html#cb143-2" tabindex="-1"></a>sma.qqplot(no[<span class="st">&quot;Sale_Price&quot;</span>], line<span class="op">=</span><span class="st">&#39;45&#39;</span>,fit<span class="op">=</span><span class="va">True</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-44-3.png" width="672" /></p>
<p>Mann-Whitney Wilcoxon test:</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb144-1"><a href="intro-stat.html#cb144-1" tabindex="-1"></a>sp.stats.mannwhitneyu(ames_py[ames_py[<span class="st">&quot;Central_Air&quot;</span>] <span class="op">==</span> <span class="st">&#39;Y&#39;</span>][<span class="st">&#39;Sale_Price&#39;</span>], ames_py[ames_py[<span class="st">&quot;Central_Air&quot;</span>] <span class="op">==</span> <span class="st">&#39;N&#39;</span>][<span class="st">&#39;Sale_Price&#39;</span>])</span></code></pre></div>
<pre><code>## MannwhitneyuResult(statistic=472700.0, pvalue=1.2086496396714786e-71)</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="slr.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/IAA-Faculty/statistical_foundations.git/edit/master/01-introduction_statistics.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/IAA-Faculty/statistical_foundations.git/blob/master/01-introduction_statistics.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"toc": null
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
